Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2022-05, with the labels that each got.

#77 chore: fix dev meetings (1st/3rd Wed) and add calendar
  CONTRIBUTING.md
Labels: ok to merge

#81 fix(plugin): get the time only once to avoid directory time != zip time
  docs/src/cnpg-plugin.md
  internal/cmd/plugin/report/cluster.go
  internal/cmd/plugin/report/cluster_report.go
  internal/cmd/plugin/report/operator.go
  internal/cmd/plugin/report/operator_report.go
  internal/cmd/plugin/report/output.go
Labels: ok to merge

#70 fix: cnp report operator correctly handles multiple replicas operator deployments
  internal/cmd/plugin/report/deployments/deployments.go
  internal/cmd/plugin/report/logs.go
  internal/cmd/plugin/report/operator_report.go
Labels: ok to merge

#42 chore: enable CodeQL scanning
  .github/workflows/codeql-analysis.yml
  api/v1/cluster_configuration.go
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_controller.go
  controllers/cluster_create.go
  controllers/cluster_status.go
  controllers/cluster_upgrade.go
  controllers/replicas.go
  controllers/suite_test.go
  docs/src/api_reference.md
  internal/cmd/manager/walarchive/cmd.go
  pkg/cnpgerrors/errors.go
  pkg/configfile/configfile.go
  pkg/configfile/configfile_test.go
  pkg/management/barman/archiver/archiver.go
  pkg/management/barman/restorer/restorer.go
  pkg/management/postgres/backup.go
  pkg/specs/jobs.go
  pkg/specs/poddisruptionbudget.go
  pkg/specs/poddisruptionbudget_test.go
  pkg/specs/pods.go
  pkg/specs/pvcs.go
  pkg/utils/barman.go
  tests/e2e/asserts_test.go
  tests/e2e/failover_test.go
  tests/e2e/rolling_update_test.go
  tests/utils/cluster.go
Labels: ok to merge

#90 fix: wrong ClusterName property used
  controllers/backup_controller.go
Labels: ok to merge

#87 feat: allow configuration of `archive_timeout` setting
  docs/src/backup_recovery.md
  docs/src/postgresql_conf.md
  pkg/postgres/configuration.go
Labels: ok to merge

#95 fix: use invitation link for Slack
  CONTRIBUTING.md
Labels: ok to merge

#108 tests: enable upgrade tests again
  hack/e2e/run-e2e.sh
  tests/utils/release.go
  tests/utils/release_test.go
Labels: ok to merge

#102 doc: add an easy way to test the current development version
  Makefile
  docs/src/cnpg-plugin.md
Labels: do not merge

#111 chore: update version of woke and spellcheck
  Makefile
Labels: ok to merge

#112 docs: add dev environment
  CONTRIBUTING.md
  README.md
  contribute/README.md
  contribute/developer_environment_setup.md
  contribute/development_environment/README.md
  contribute/e2e_testing_environment/README.md
  contribute/images/docker_resources.png
  contribute/images/docker_settings.png
  contribute/to_be_classified.md
Labels: documentation, ok to merge

#106 fix: triggers a renconciliation loop if the RBAC for backups is not yet created
  internal/management/controller/cache.go
  internal/management/controller/instance_controller.go
Labels: ok to merge

#129 ci: clean up older images from testing package
  .github/workflows/registry-clean.yml
Labels: ok to merge

#105 feat: adds backupOwnerReference to scheduledBackup.spec
  .wordlist-en-custom.txt
  api/v1/scheduledbackup_types.go
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  controllers/scheduledbackup_controller.go
  docs/src/api_reference.md
  docs/src/backup_recovery.md
  docs/src/samples/scheduled-backup-example.yaml
Labels: ok to merge

#127 docs: Update README.md
  contribute/development_environment/README.md
Labels: ok to merge

#152 ci: do not run package cleanup on push
  .github/workflows/registry-clean.yml
Labels: ok to merge

#150 doc: fix helm chart URL for the install process
  docs/src/installation_upgrade.md
Labels: ok to merge

#124 feat: adding Krew support to GoReleaser
  .github/workflows/release-publish.yml
  .goreleaser.yml
Labels: ok to merge

#133 fix: enable CSV logpipe inside WithActiveInstance function
  pkg/management/postgres/instance.go
  pkg/management/postgres/logpipe/logpipe.go
Labels: bug, ok to merge

#176 doc: Add FAQ about time zone configuration
  .wordlist-en-custom.txt
  docs/src/faq.md
Labels: ok to merge

#158 tests: Improves E2E resiliency to transient network failures
  tests/e2e/asserts_test.go
Labels: chore

#123 fix: parse configmap name and secrets name from operator deployment
  internal/cmd/plugin/report/deployments/deployments.go
  internal/cmd/plugin/report/operator_report.go
Labels: bug, ok to merge

#156 refactor: backup and walarchive conditions in cluster status
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/backup_controller.go
  docs/src/api_reference.md
  internal/cmd/manager/manager.go
  internal/cmd/manager/walarchive/cmd.go
  pkg/management/postgres/backup.go
  tests/utils/backup.go
Labels: ok to merge :ok_hand:, ok to merge

#120 fix: Support updates of inherited labels and annotations on PVCs
  controllers/cluster_controller.go
  controllers/replicas.go
Labels: bug :bug:, ok to merge

#197 doc: Release notes for 1.15.1
  docs/src/release_notes.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, ok to merge

#204 docs: explaining webhook configuration rbac needs
  docs/src/security.md
Labels: ok to merge

#216 chore: add the release file to artifacts
  .github/workflows/release-publish.yml
Labels: ok to merge

#180 feat: avoid executing DDL to reconcile extensions when not needed
  internal/management/controller/instance_controller.go
Labels: ok to merge

#212 fix: CSV logpipe initialization order inside WithActiveInstance function
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:

#211 fix: serverName handling when restoring from a backup
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:
