Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2022-09, with the labels that each got.

#663 test: display failed test summary table
  .github/summarize_test_results.py
Labels: backport-requested :arrow_backward:, ready to test :elephant:

#655 Atomically check whether inplace instance upgrade is in progress
  internal/cmd/manager/instance/run/lifecycle/lifecycle.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/probes.go
  pkg/management/postgres/webserver/remote.go
  pkg/management/upgrade/upgrade.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#660 fix: use a temporary file to host the new instance manager binary
  pkg/management/upgrade/upgrade.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#680 chore: ensure that `cnpg.io/instanceName` and `cnpg.io/podRole` are correctly reconciled on existing resources
  controllers/cluster_controller.go
  controllers/replicas.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:

#668 chore: replaces connection driver `postgres` with `pgx`
  docs/src/database_import.md
  go.mod
  go.sum
  internal/cmd/manager/instance/run/lifecycle/run.go
  internal/management/controller/instance_controller.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/join.go
  pkg/management/postgres/logicalimport/database.go
  pkg/management/postgres/logicalimport/role.go
  pkg/management/postgres/logicalimport/roleinheritance.go
  pkg/management/postgres/pool/pool.go
  pkg/utils/db.go
Labels: ok to merge :ok_hand:

#684 fix: avoid creating Pods for an incomplete group of PVCs
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_controller.go
  controllers/cluster_status.go
  docs/src/api_reference.md
  pkg/specs/pvcs.go
Labels: bug :bug:, ok to merge :ok_hand:

#686 fix: avoid passing Instance by value
  pkg/management/postgres/instance.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:

#695 fix: Set the default datestyle to ISO
  pkg/utils/db.go
Labels: ready to test :elephant:

#692 chore: reduce resource consumption for PostgreSQL in E2E tests
  tests/e2e/fixtures/upgrade/cluster-restore.yaml.template
  tests/e2e/fixtures/upgrade/cluster1.yaml.template
  tests/e2e/fixtures/upgrade/cluster2.yaml.template
Labels: ok to merge :ok_hand:

#682 feat: replication slots for HA: manage slots in the primary
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_status.go
  docs/src/api_reference.md
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/management/controller/instance_controller.go
  internal/management/controller/instance_controller_test.go
  internal/management/controller/instance_startup.go
  internal/management/controller/replica.go
  internal/management/controller/replicationslot.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/instance_test.go
  pkg/management/postgres/join.go
  pkg/management/postgres/replicationslot.go
  pkg/management/postgres/restore.go
  pkg/specs/pvcs.go
  pkg/specs/pvcs_test.go
Labels: enhancement :magic_wand:

#711 ci: Nightly build kubectl plugin in case it breaks release
  .github/workflows/chatops-dispatcher.yml
  .github/workflows/chatops-receiver.yml
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:

#733 Update dependencies to Kubernetes 1.25
  .github/e2e-matrix-generator.py
  .github/workflows/continuous-delivery.yml
  Makefile
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  contribute/e2e_testing_environment/README.md
  controllers/cluster_controller.go
  controllers/cluster_create.go
  controllers/cluster_create_test.go
  docs/src/e2e.md
  go.mod
  go.sum
  hack/e2e/run-e2e-k3d.sh
  hack/e2e/run-e2e-kind.sh
  hack/e2e/run-e2e.sh
  hack/setup-cluster.sh
  pkg/multicache/multinamespaced_cache.go
  pkg/specs/poddisruptionbudget.go
Labels: ok to merge :ok_hand:, chore, ready to test :elephant:, do not backport

#746 doc: remove leftover references to K8S 1.19 and 1.20
  docs/k8s-api-docgen.yaml
  docs/src/api_reference.md
  docs/src/before_you_start.md
  hack/e2e/rke-ec2/README.md
  hack/e2e/rke-ec2/interface.tf
  hack/e2e/rke-ec2/versions.tf
Labels: no-issue

#748 test: fix misplaced parenthesis in unit tests
  pkg/postgres/configuration_test.go
Labels: ok to merge :ok_hand:

#737 fix: ensures that the promoted standby active connections are dropped after promotion
  internal/management/controller/instance_controller.go
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#706 test: dump operator log if it is restarted
  internal/cmd/plugin/report/logs.go
  pkg/utils/logs/logs.go
  tests/e2e/suite_test.go
  tests/utils/cluster.go
Labels: ok to merge :ok_hand:

#720 fix: ensure that the conditions contained in the cluster status are made compatible with metav1.Conditions struct
  api/v1/cluster_types.go
  controllers/cluster_controller.go
  controllers/cluster_status.go
  internal/cmd/manager/walarchive/cmd.go
  pkg/management/postgres/backup.go
  pkg/utils/conditions.go
Labels: ok to merge :ok_hand:

#763 ci: fix 'ok to merge' labeling
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, ready to test :elephant:

#716 doc: add instructions on how to inspect exported metrics
  .wordlist-en-custom.txt
  docs/src/monitoring.md
Labels: ok to merge :ok_hand:, ready to test :elephant:

#740 Replication slots for HA
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/manager/default-monitoring.yaml
  controllers/cluster_status.go
  docs/src/api_reference.md
  docs/src/index.md
  docs/src/operator_capability_levels.md
  docs/src/postgresql_conf.md
  docs/src/replication.md
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/cmd/manager/instance/run/cmd.go
  internal/management/controller/instance_controller.go
  internal/management/controller/instance_startup.go
  internal/management/controller/replica.go
  internal/management/controller/slots/infrastructure/contract.go
  internal/management/controller/slots/infrastructure/doc.go
  internal/management/controller/slots/infrastructure/postgresmanager.go
  internal/management/controller/slots/infrastructure/replicationslot.go
  internal/management/controller/slots/infrastructure/replicationslot_test.go
  internal/management/controller/slots/infrastructure/suite_test.go
  internal/management/controller/slots/reconciler/doc.go
  internal/management/controller/slots/reconciler/replicationslot.go
  internal/management/controller/slots/reconciler/replicationslot_test.go
  internal/management/controller/slots/reconciler/suite_test.go
  internal/management/controller/slots/runner/doc.go
  internal/management/controller/slots/runner/runner.go
  internal/management/controller/slots/runner/runner_test.go
  internal/management/controller/slots/runner/suite_test.go
  pkg/configfile/configfile.go
  pkg/configfile/configfile_test.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/instance_test.go
  pkg/management/postgres/join.go
  pkg/management/postgres/restore.go
  pkg/specs/pvcs.go
  pkg/specs/pvcs_test.go
  tests/e2e/asserts_test.go
  tests/e2e/fixtures/replication_slot/cluster-pg-replication-slot.yaml.template
  tests/e2e/replication_slot_test.go
  tests/utils/cluster.go
  tests/utils/replication_slots.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#735 test: Print more cluster info when assertClutsterReady timeout
  tests/e2e/asserts_test.go
  tests/utils/cluster.go
Labels: ok to merge :ok_hand:

#765 fix: honour MAPPEDMETRIC and DURATION metric types conversion
  pkg/management/postgres/metrics/collect_test.go
  pkg/management/postgres/metrics/collector.go
  pkg/management/postgres/metrics/collector_test.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#759 chore: enables the customization of leaseDuration and renewDeadline in the controller manager
  internal/cmd/manager/controller/cmd.go
  internal/cmd/manager/controller/controller.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#779 doc: FAQ about cluster impact during Operator outage
  .wordlist-en-custom.txt
  docs/src/faq.md
Labels: ok to merge :ok_hand:
