Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2022-11, with the labels that each got.

#920 test: add detail to flaky tests
  tests/e2e/asserts_test.go
  tests/e2e/replication_slot_test.go
  tests/utils/cluster.go
Labels: ok to merge :ok_hand:, no-issue, ready to test :elephant:

#974 fix: correctly manage `plpgsql` in database import
  pkg/management/postgres/logicalimport/database.go
  tests/e2e/fixtures/cluster_microservice/cluster-base.yaml.template
Labels: ready to test :elephant:

#968 docs: provide example monitoring instructions
  .wordlist-en-custom.txt
  docs/src/images/grafana-local.png
  docs/src/images/prometheus-local.png
  docs/src/monitoring.md
  docs/src/quickstart.md
  docs/src/samples/monitoring/alerts.yaml
  docs/src/samples/monitoring/cnpg-prometheusrule.yaml
  docs/src/samples/monitoring/grafana-configmap.yaml
  docs/src/samples/monitoring/grafana-dashboard.json
  docs/src/samples/monitoring/kube-stack-config.yaml
Labels: ok to merge :ok_hand:

#973 tests: avoid failures if FEATURE_TYPE is not set
  hack/e2e/run-e2e.sh
Labels: ok to merge :ok_hand:, no-issue

#979 fix: shellcheck is failing
  hack/e2e/run-e2e.sh
Labels: ok to merge :ok_hand:, ready to test :elephant:

#958 feat: create the pgbench command for kubectl plugin.
  cmd/kubectl-cnpg/main.go
  docs/mkdocs.yml
  docs/src/benchmarking.md
  docs/src/cnpg-plugin.md
  internal/cmd/plugin/pgbench/cmd.go
  internal/cmd/plugin/pgbench/doc.go
  internal/cmd/plugin/pgbench/pgbench.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#998 fix: automatic PostgreSQL version update regexp
  .github/workflows/latest-postgres-version-check.yml
Labels: ok to merge :ok_hand:

#1001 docs: enhance release procedure
  contribute/release_procedure.md
Labels: no-issue

#1002 test: handle remaining namespace deletions in DeferCleanup
  tests/e2e/hibernation_test.go
  tests/e2e/pg_basebackup_test.go
  tests/e2e/update_user_test.go
Labels: ok to merge :ok_hand:, no-issue, ready to test :elephant:

#965 ci: add backport pull request workflow
  .github/workflows/backport.yml
Labels: ok to merge :ok_hand:

#1029 test: set `KUBEBUILDER_CONTROLPLANE_STOP_TIMEOUT` and `KUBEBUILDER_CONTROLPLANE_START_TIMEOUT`
  Makefile
Labels: ok to merge :ok_hand:, ready to test :elephant:, backport-requested, release-1.16, release-1.17, release-1.18

#1039 ci: fix backport workflow failed to retrive the commit
  .github/workflows/backport.yml
Labels: ok to merge :ok_hand:

#1030 test: refine the envTest creation inside the controllers package (#1029)
  controllers/suite_test.go
Labels: ok to merge :ok_hand:, ready to test :elephant:, backport-requested, release-1.16, release-1.17, release-1.18

#1033 doc: document emeritus status for maintainers in GOVERNANCE.md
  GOVERNANCE.md
Labels: ok to merge :ok_hand:, backport-requested, release-1.16, release-1.17, release-1.18

#1026 fix: limit the orphan pvc list inner the cluster namespace
  controllers/cluster_restore.go
Labels: ok to merge :ok_hand:

#1037 ci: removing unused rook env and k8s version 1.21 support from unit test
  .github/workflows/continuous-delivery.yml
  docs/src/e2e.md
Labels: ok to merge :ok_hand:, ready to test :elephant:

#1045 ci: Getting Visibility Into Long-Running Specs
  hack/e2e/run-e2e.sh
Labels: ok to merge :ok_hand:, ready to test :elephant:, backport-requested, release-1.16, release-1.17, release-1.18

#1022 chore: replace `postgresql` with `cnpg.io/cluster` as service selector
  pkg/specs/services.go
  pkg/specs/services_test.go
Labels: ok to merge :ok_hand:, do not merge :no_good:, do not squash :warning:, backport-requested, release-1.18

#1052 chore: centralize instance corev1.ServicePort generation logic
  controllers/cluster_controller.go
  docs/src/monitoring.md
  pkg/specs/poddisruptionbudget.go
  pkg/specs/pods.go
  pkg/specs/services.go
Labels: ok to merge :ok_hand:, backport-requested, release-1.18

#1047 tests: fix tag detection
  tests/utils/release.go
Labels: ok to merge :ok_hand:, backport-requested, release-1.16, release-1.17, release-1.18

#1070 feat: add `stringset.Eq` method
  pkg/stringset/stringset.go
  pkg/stringset/stringset_test.go
Labels: backport-requested, release-1.16, release-1.17, release-1.18

#1064 ci: use ciclops for test summary
  .github/summarize_test_results.py
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, ready to test :elephant:, backport-requested, release-1.16, release-1.17, release-1.18

#961 test: get operator logs on failed specs
  config/manager/env_override.yaml
  internal/cmd/plugin/report/logs.go
  pkg/utils/logs/logs.go
  tests/e2e/asserts_test.go
  tests/e2e/hibernation_test.go
  tests/e2e/suite_test.go
  tests/utils/cluster.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#1073 ci: backport should not create issue if release branch not select
  .github/workflows/backport.yml
  contribute/release_procedure.md
Labels: ok to merge :ok_hand:, ready to test :elephant:, backport-requested, release-1.16, release-1.17, release-1.18

#1049 ci: use single file to control the e2e/unit test support versions
  .github/e2e-matrix-generator.py
  .github/k8s_versions_scope.json
  .github/kind_versions.json
  .github/workflows/continuous-delivery.yml
  .github/workflows/kind-k8s-versions-check.yml
Labels: ok to merge :ok_hand:, ready to test :elephant:, backport-requested, release-1.16, release-1.17, release-1.18

#1068 chore: added a few debug log
  controllers/cluster_controller.go
  controllers/pooler_controller.go
  controllers/scheduledbackup_controller.go
Labels: ok to merge :ok_hand:, backport-requested, release-1.16, release-1.17, release-1.18

#843 feat: allow fields remapping in JSON logs
  docs/src/logging.md
  pkg/management/log/flags.go
  pkg/specs/containers.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#1092 chore: remove ARMv7 support
  .github/workflows/continuous-delivery.yml
  .github/workflows/release-publish.yml
  .goreleaser.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1088 fix: missing ApiVersion and Kind in pgbench manifest using --dry-run and updating doc.
  docs/src/benchmarking.md
  internal/cmd/plugin/pgbench/pgbench.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:, release-1.18

#1009 ci: remove PostgreSQL 10 from supported versions.
  .github/pg_versions.json
  .github/postgres-versions-update.py
  docs/src/database_import.md
  docs/src/e2e.md
  docs/src/monitoring.md
  docs/src/replication.md
  internal/management/controller/instance_controller.go
  tests/e2e/asserts_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/replication_slot_test.go
  tests/e2e/scaling_test.go
  tests/e2e/switchover_test.go
Labels: ok to merge :ok_hand:, do not backport

#1107 chore: remove k8s version 1.25 from unit test and e2e
  .github/k8s_versions_scope.json
Labels: ok to merge :ok_hand:

#1108 chore: remove k8s version 1.25 from unit test and e2e in release
  .github/k8s_versions_scope.json
Labels: ok to merge :ok_hand:

#1105 feat: customize labels and annotations for the service account
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/common_types.go
  api/v1/pooler_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_create.go
  controllers/cluster_create_test.go
  docs/src/api_reference.md
  docs/src/backup_recovery.md
  pkg/specs/serviceaccount.go
  pkg/specs/serviceaccount_test.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, do not squash :warning:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1094 ci: Make the operator log level configurable in e2e test suite
  .github/workflows/chatops-dispatcher.yml
  .github/workflows/chatops-receiver.yml
  .github/workflows/continuous-delivery.yml
  hack/e2e/env_override_customized.yaml.template
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:, release-1.16, release-1.17, release-1.18

#1110 ci: create one ticket for backport failure
  .github/workflows/backport.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:, release-1.16, release-1.17, release-1.18
