Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2022-07, with the labels that each got.

#270 fix: use backup ID in Point in Time Recovery
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
  docs/src/bootstrap.md
  pkg/management/catalog/catalog.go
  pkg/management/catalog/catalog_test.go
  pkg/management/postgres/restore.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested

#292 fix: disable application database configuration in replica mode
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  docs/src/bootstrap.md
  pkg/management/postgres/restore.go
  tests/e2e/asserts_test.go
  tests/e2e/commons_test.go
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-basicauth.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-src.yaml.template
  tests/e2e/replica_mode_cluster_test.go
Labels: ok to merge :ok_hand:

#336 fix: avoid two patch in one reconcile loop
  controllers/cluster_status.go
Labels: ok to merge :ok_hand:

#338 feat(plugin): add nodename in the instance status section
  internal/cmd/plugin/status/status.go
Labels: ok to merge :ok_hand:

#341 ci: let's run less E2E
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:

#344 doc: Release Notes for 1.16.0
  docs/src/index.md
  docs/src/operator_capability_levels.md
  docs/src/release_notes.md
Labels: ok to merge :ok_hand:

#356 doc: improve release notes for the `withActiveInstance` logging patch
  docs/src/release_notes.md
Labels: documentation :book:, backport-requested :arrow_backward:

#340 fix: only healthy pods are electable as synchronous replica
  api/v1/cluster_configuration.go
Labels: bug :bug:

#346 Introduce release branches
  .github/workflows/release-pr.yml
  .github/workflows/release-tag.yml
  contribute/release_procedure.md
  contribute/to_be_classified.md
  docs/src/supported_releases.md
  hack/release.sh
Labels: ok to merge :ok_hand:

#357 fix: support application database monitoring for replica clusters
  api/v1/cluster_types.go
  docs/src/monitoring.md
  internal/management/controller/instance_controller.go
Labels: bug :bug:, ok to merge :ok_hand:

#368 refactor: remove current primary logic from reconcileOldPrimary
  internal/management/controller/instance_controller.go
Labels: ok to merge :ok_hand:

#370 test: CheckForExistingPostmaster implementation easier to test
  pkg/management/postgres/instance.go
  pkg/management/postgres/pidfile.go
  pkg/management/postgres/pidfile_test.go
Labels: risk :boom:

#374 fix: e2e in metrics collection with runonserver query created by user
  tests/e2e/fixtures/metrics/custom-queries.yaml
  tests/e2e/metrics_test.go
Labels: ok to merge :ok_hand:

#380 refactor: removes GetKubernetesObject method
  api/v1/backup_types.go
  api/v1/scheduledbackup_types.go
  controllers/scheduledbackup_controller.go
Labels: do not merge :no_good:

#411 fix: use `postgres` user while running pg_restore
  pkg/management/postgres/logicalimport/database.go
Labels: ok to merge :ok_hand:

#360 test: add coverage for synchronous replica election
  api/v1/cluster_configuration_test.go
  api/v1/suite_test.go
Labels: ok to merge :ok_hand:

#328 test(controllers): add support for custom k8sClient
  controllers/cluster_create_test.go
  controllers/cluster_delete_test.go
  controllers/cluster_scale_test.go
  controllers/cluster_status_test.go
  controllers/suite_test.go
Labels: ok to merge :ok_hand:

#415 chore: update operator manifest version in release script
  hack/release.sh
Labels: ok to merge :ok_hand:

#416 ci: refine ok to merge step to avoid failure
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:

#419 refactor: moving Azurite setup code to utils.
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/fixtures/backup/azurite/az-cli.yaml
  tests/e2e/fixtures/backup/azurite/azurite-deployment.yaml
  tests/e2e/fixtures/backup/azurite/azurite-secret.yaml
  tests/e2e/fixtures/backup/azurite/azurite-service.yaml
  tests/utils/azurite.go
Labels: ok to merge :ok_hand:

#454 fix: add google credentials to Backup CR and Role
  pkg/management/postgres/restore.go
  pkg/specs/roles.go
Labels: bug :bug:, backport-requested :arrow_backward:

#471 doc: explain how to contribute documentation
  CONTRIBUTING.md
  docs/README.md
Labels: ok to merge :ok_hand:

#135 fix: updating resizing status if resize is pending
  pkg/specs/pvcs.go
Labels: bug :bug:, ok to merge :ok_hand:

#467 fix: get latest WAL correctly for Postgres 15 in upgrade E2E test
  tests/e2e/upgrade_test.go
Labels: ok to merge :ok_hand:

#463 test: add backup object context logs in DumpNamespaceObjects
  tests/utils/cluster.go
  tests/utils/environment.go
Labels: ok to merge :ok_hand:

#481 ci: fix sorting of PostgreSQL pre-releases in E2E files
  .github/pg_versions.json
  .github/postgres-versions-update.py
Labels: ok to merge :ok_hand:

#459 feat: update Go version from 1.17 to 1.18
  .github/workflows/continuous-delivery.yml
  .github/workflows/release-publish.yml
  go.mod
  go.sum
Labels: ok to merge :ok_hand:

#475 doc: split release notes per minor release
  .github/workflows/release-publish.yml
  docs/src/release_notes.md
  docs/src/release_notes/edb-cloud-native-postgresql.md
  docs/src/release_notes/v1.15.md
  docs/src/release_notes/v1.16.md
Labels: ok to merge :ok_hand:

#362 refactor: reorganize addBarmanEndpointCAToJob function
  .wordlist-en-custom.txt
  api/v1/backup_types.go
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
  internal/cmd/manager/walrestore/cmd.go
  pkg/management/barman/backupdelete.go
  pkg/management/barman/commandbuilder.go
  pkg/management/barman/credentials/env.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/restore.go
  pkg/specs/jobs.go
  pkg/specs/jobs_test.go
  pkg/specs/pods.go
  pkg/specs/roles.go
  pkg/specs/roles_test.go
  tests/utils/backup.go
Labels: ok to merge :ok_hand:, chore

#408 ci: E2E test summary step
  .github/summarize-test-results.py
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:

#462 feat: add instances timeline id in cluster status
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_controller.go
  controllers/cluster_status.go
  docs/src/api_reference.md
  pkg/management/postgres/probes.go
Labels: ok to merge :ok_hand:

#429 feat: add ready-to-test command and independent container registry
  .github/e2e-matrix-generator.py
  .github/workflows/chatops-dispatcher.yml
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:

#501 fix: avoid updating CRD if TLS cert unchanged
  pkg/certs/k8s.go
Labels: ok to merge :ok_hand:

#506 ci: support running full E2E tests on release-* branches
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:

#371 feat: adds logs during switchover, failover and demotion
  api/v1/cluster_types.go
  internal/management/controller/instance_controller.go
  pkg/utils/time.go
  pkg/utils/time_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:

#489 test: adds unit tests for postgres/instance
  pkg/management/postgres/instance.go
  pkg/management/postgres/instance_test.go
Labels: ready to test :elephant:

#510 Update links to point to new topic locations for Secrets and Replication Clusters
  docs/src/backup_recovery.md
  docs/src/security.md
Labels: ok to merge :ok_hand:, ready to test :elephant:
