Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2022-06, with the labels that each got.

#174 fix: sensitive param decrease should not leads to switchover
  controllers/cluster_upgrade.go
  internal/management/controller/instance_controller.go
Labels: bug :bug:, ok to merge :ok_hand:

#207 feat: adds AWS_DEFAULT_REGION to barman env
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
  pkg/management/barman/credentials/env.go
Labels: ok to merge :ok_hand:

#221 test: add e2e test for recovery with custom serverName
  tests/e2e/backup_restore_test.go
  tests/e2e/fixtures/backup/cluster-from-restore-custom.yaml
  tests/e2e/fixtures/backup/minio/backup-minio-custom-servername.yaml
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-custom-servername.yaml.template
Labels: ok to merge :ok_hand:

#236 chore: add support for alpha, beta and rc images
  .github/postgres-versions-update.py
Labels: ok to merge :ok_hand:

#222 test: e2e for backup and safety
  tests/e2e/backup_restore_test.go
  tests/e2e/fixtures/backup/backup_restore_safety/.gitignore
  tests/e2e/fixtures/backup/backup_restore_safety/backup-cluster-2.yaml
  tests/e2e/fixtures/backup/backup_restore_safety/backup-source-cluster.yaml
  tests/e2e/fixtures/backup/backup_restore_safety/cluster-with-backup-minio.yaml.template
  tests/e2e/fixtures/backup/backup_restore_safety/external-clusters-minio-2.yaml.template
  tests/e2e/fixtures/backup/backup_restore_safety/external-clusters-minio-3.yaml.template
  tests/e2e/fixtures/backup/backup_restore_safety/external-clusters-minio-4.yaml.template
  tests/e2e/fixtures/backup/backup_restore_safety/external-clusters-minio.yaml.template
Labels: ok to merge :ok_hand:

#181 chore: add a verification issue link verification
  .github/workflows/pr_verify_linked_issue.yml
Labels: enhancement :magic_wand:

#76 feat: provide application database configuration for restore
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_create.go
  docs/src/api_reference.md
  docs/src/bootstrap.md
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/management/controller/instance_controller.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/restore.go
  pkg/specs/jobs.go
  pkg/specs/roles_test.go
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/fixtures/backup/azurite/cluster-from-restore.yaml.template
  tests/e2e/fixtures/backup/recovery_external_clusters/cluster-from-restore-sas.yaml.template
  tests/e2e/fixtures/backup/recovery_external_clusters/external-clusters-azurite-03.yaml.template
  tests/e2e/fixtures/pg_basebackup/cluster-dst-basic-auth.yaml.template
  tests/e2e/fixtures/pg_basebackup/cluster-src.yaml.template
  tests/e2e/pg_basebackup_test.go
  tests/utils/backup.go
Labels: ok to merge :ok_hand:

#262 doc: update architecture.md file
  docs/src/architecture.md
Labels: ok to merge :ok_hand:

#241 fix: add support to dump logs of multiple clusters in e2e.
  tests/e2e/apparmor_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/cluster_objectmeta_test.go
  tests/e2e/cluster_setup_test.go
  tests/e2e/cnpg_certificates_test.go
  tests/e2e/config_support_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/connection_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/eviction_test.go
  tests/e2e/failover_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fencing_test.go
  tests/e2e/initdb_test.go
  tests/e2e/logs_test.go
  tests/e2e/metrics_test.go
  tests/e2e/nodeselector_test.go
  tests/e2e/operator_ha_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/pg_basebackup_test.go
  tests/e2e/pg_data_corruption_test.go
  tests/e2e/pgbouncer_metrics_test.go
  tests/e2e/pgbouncer_test.go
  tests/e2e/pgbouncer_types_test.go
  tests/e2e/pvc_deletion_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/rolling_update_test.go
  tests/e2e/scaling_test.go
  tests/e2e/storage_expansion_test.go
  tests/e2e/switchover_test.go
  tests/e2e/syncreplicas_test.go
  tests/e2e/tolerations_test.go
  tests/e2e/update_user_test.go
  tests/e2e/upgrade_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/e2e/webhook_test.go
  tests/utils/cluster.go
Labels: ok to merge :ok_hand:

#219 fix: correct encryption parameters in Barman commands
  internal/cmd/manager/walrestore/cmd.go
  pkg/management/barman/backupdelete.go
  pkg/management/barman/backuplist.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:

#248 fix: search operator deployment from user namespace
  docs/src/cnpg-plugin.md
  internal/cmd/plugin/report/operator_objects.go
  internal/cmd/plugin/report/operator_report.go
Labels: do not merge :no_good:

#235 feat: introduce synchronous replicas constraints
  .wordlist-en-custom.txt
  api/v1/cluster_configuration.go
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_status.go
  docs/src/api_reference.md
  docs/src/replication.md
  docs/src/samples/cluster-example-sync-az.yaml
  docs/src/security.md
  internal/management/controller/instance_controller.go
  pkg/management/postgres/configuration.go
  pkg/postgres/configuration.go
  pkg/postgres/configuration_test.go
Labels: ok to merge :ok_hand:

#277 fix: escape role with double quotes when altering
  internal/management/controller/instance_controller.go
Labels: ok to merge :ok_hand:

#279 fix: webhook accepting image tags such as 15beta1
  api/v1/cluster_webhook_test.go
  pkg/postgres/version.go
  pkg/postgres/version_test.go
Labels: ok to merge :ok_hand:

#265 fix: compare TargetTime with backup EndTime when PITR (#264)
  pkg/management/catalog/catalog.go
Labels: bug :bug:

#232 fix: sort results before printing in cnpg status plugin
  internal/cmd/plugin/status/status.go
  pkg/management/postgres/probes.go
  pkg/postgres/status.go
Labels: ok to merge :ok_hand:

#289 chore: LC_ALL=C for consistent sorting of wordlist on linux
  Makefile
Labels: ok to merge :ok_hand:

#291 docs: clarify log storage is not in operator
  docs/src/logging.md
  docs/src/postgresql_conf.md
Labels: ok to merge :ok_hand:

#295 chore: downgrades skipped monitoring query messages to debug level
  config/manager/default-monitoring.yaml
  docs/src/samples/cnpg-basic-monitoring.yaml
  pkg/management/postgres/metrics/collector.go
Labels: ok to merge :ok_hand:

#267 test: fix backup restore e2e test failure
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/commons_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/utils/environment.go
  tests/utils/minio.go
Labels: ok to merge :ok_hand:

#299 fix: retry issue in `Prepare the enviroment` step
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:

#198 refactor: backup and walarchive conditions in cluster status
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/backup_controller.go
  docs/src/api_reference.md
  internal/cmd/manager/manager.go
  internal/cmd/manager/walarchive/cmd.go
  pkg/management/postgres/backup.go
  pkg/utils/conditions.go
  pkg/utils/conditions_test.go
  tests/utils/backup.go
Labels: ok to merge :ok_hand:

#305 chore: adds webhook validation for syncReplicaElectionConstraints
  api/v1/cluster_webhook.go
Labels: ok to merge :ok_hand:

#306 feat: improve instances status logging during switchover and failover
  controllers/replicas.go
  pkg/postgres/status.go
Labels: ok to merge :ok_hand:

#323 Clarify documentation on `syncReplicaElectionConstraint`
  .wordlist-en-custom.txt
  docs/mkdocs.yml
  docs/src/architecture.md
  docs/src/replica_cluster.md
  docs/src/replication.md
Labels: ok to merge :ok_hand:, do not squash

#326 test: ensure cache is indexed before testing dangling configmap
  controllers/cluster_delete_test.go
Labels: ok to merge :ok_hand:
