Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2022-10, with the labels that each got.

#798 fix: wrong action in the `do_not_skip` section
  .github/workflows/codeql-analysis.yml
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:

#760 test: e2e tests for replication slots
  docs/src/e2e.md
  tests/e2e/asserts_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fixtures/base/cluster-storage-class-with-rep-slots.yaml.template
  tests/e2e/fixtures/fastfailover/cluster-fast-failover-with-repl-slots.yaml.template
  tests/e2e/fixtures/fastswitchover/cluster-fast-switchover-with-repl-slots.yaml.template
  tests/e2e/fixtures/replication_slot/cluster-pg-replication-slot-disable.yaml.template
  tests/e2e/replication_slot_test.go
  tests/e2e/scaling_test.go
  tests/e2e/switchover_test.go
  tests/utils/environment.go
  tests/utils/replication_slots.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#813 security: update golang.org/x/net version
  go.mod
  go.sum
Labels: ok to merge :ok_hand:

#805 fix: create load-helper-images command for setup-cluster.sh
  hack/e2e/run-e2e-k3d.sh
  hack/e2e/run-e2e-kind.sh
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, ready to test :elephant:

#790 ci: reflect failing CI branches in Test Summary
  .github/generate-test-artifacts.py
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:

#819 chore: improve archive WAL check
  docs/src/release_notes/v1.15.md
  docs/src/release_notes/v1.16.md
  docs/src/release_notes/v1.17.md
  internal/cmd/manager/walarchive/cmd.go
  internal/management/controller/instance_controller.go
  pkg/management/barman/archiver/archiver.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:

#800 chore: persist manifest file for dev branch
  .github/workflows/continuous-delivery.yml
  Makefile
  contribute/README.md
  docs/src/installation_upgrade.md
Labels: ok to merge :ok_hand:

#840 fix: add the operator image env
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, ready to test :elephant:

#828 feat: adds skipEmptyWalArchiveCheck annotation
  internal/cmd/manager/walarchive/cmd.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, do not squash :warning:, ready to test :elephant:

#786 feat: adds hibernate off
  controllers/cluster_controller.go
  controllers/cluster_restore.go
  internal/cmd/plugin/hibernate/cmd.go
  internal/cmd/plugin/hibernate/off.go
  internal/cmd/plugin/hibernate/resources.go
  pkg/specs/jobs.go
  pkg/specs/pods.go
  pkg/specs/pvcs.go
Labels: ready to test :elephant:

#794 feat: adds hibernate status command
  docs/src/cnpg-plugin.md
  internal/cmd/plugin/hibernate/cmd.go
  internal/cmd/plugin/hibernate/output.go
  internal/cmd/plugin/hibernate/status.go
  internal/cmd/plugin/printer.go
Labels: ok to merge :ok_hand:

#856 fix: remove webhook check for backup overwriting
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  docs/src/backup_recovery.md
  tests/e2e/backup_restore_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:

#866 ci: fix krew release
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, no-issue

#880 refactor: improve instance manager liveness probe readability
  pkg/management/postgres/webserver/remote.go
Labels: ready to test :elephant:

#885 fix: use the right constant for retry logic in tests
  tests/utils/commons.go
Labels: ok to merge :ok_hand:, no-issue, ready to test :elephant:

#876 test: refactor deletion of namespaces in E2E tests
  tests/e2e/apparmor_test.go
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/cluster_monolithic_test.go
  tests/e2e/cluster_objectmeta_test.go
  tests/e2e/cluster_setup_test.go
  tests/e2e/cnpg_certificates_test.go
  tests/e2e/config_support_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/connection_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/eviction_test.go
  tests/e2e/failover_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fencing_test.go
  tests/e2e/initdb_test.go
  tests/e2e/logs_test.go
  tests/e2e/metrics_test.go
  tests/e2e/nodeselector_test.go
  tests/e2e/operator_ha_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/pg_basebackup_test.go
  tests/e2e/pg_data_corruption_test.go
  tests/e2e/pg_wal_volume_test.go
  tests/e2e/pgbouncer_metrics_test.go
  tests/e2e/pgbouncer_test.go
  tests/e2e/pgbouncer_types_test.go
  tests/e2e/pvc_deletion_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/replication_slot_test.go
  tests/e2e/rolling_update_test.go
  tests/e2e/scaling_test.go
  tests/e2e/storage_expansion_test.go
  tests/e2e/switchover_test.go
  tests/e2e/syncreplicas_test.go
  tests/e2e/tolerations_test.go
  tests/e2e/update_user_test.go
  tests/e2e/upgrade_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/e2e/webhook_test.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#903 doc: remove hibernate.md leftover file
  docs/src/hibernate.md
Labels: ok to merge :ok_hand:, ready to test :elephant:

#897 fix: ensure we have a WAL to archive for every newly created cluster
  controllers/scheduledbackup_controller.go
  pkg/management/postgres/backup.go
Labels: ready to test :elephant:

#873 feat: adds replication slot status to plugin `status`
  internal/cmd/plugin/status/cmd.go
  internal/cmd/plugin/status/status.go
  pkg/management/postgres/probes.go
  pkg/postgres/status.go
Labels: ready to test :elephant:

#918 doc: add a section about our custom controller
  .wordlist-en-custom.txt
  docs/mkdocs.yml
  docs/src/controller.md
  docs/src/faq.md
Labels: ready to test :elephant:

#895 chore: replace deprecated set-output command in workflow
  .github/e2e-matrix-generator.py
  .github/workflows/chatops-receiver.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/latest-postgres-version-check.yml
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:

#914 fix: allow omitting storage size if in pvcTemplate
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_controller.go
  docs/src/api_reference.md
  pkg/specs/pvcs.go
  pkg/specs/pvcs_test.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#930 chore: avoid setting seccompProfile when not supported
  internal/cmd/manager/controller/controller.go
  pkg/specs/containers.go
  pkg/specs/pods.go
  pkg/utils/discovery.go
  tests/utils/azurite.go
  tests/utils/curl.go
  tests/utils/environment.go
  tests/utils/minio.go
  tests/utils/webapp.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#855 test: adds E2E tests for the `cnpg plugin hibernate` command.
  tests/e2e/fixtures/hibernate/cluster-storage-class-without-wal.yaml.template
  tests/e2e/hibernation_test.go
  tests/utils/storage.go
Labels: ok to merge :ok_hand:

#883 Clarify ScheduledBackup.spec.schedule format
  api/v1/scheduledbackup_types.go
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  docs/src/api_reference.md
Labels: ok to merge :ok_hand:, no-issue, ready to test :elephant:

#945 doc: Group and Add E2E details under `End-to-End Tests` section.
  docs/src/e2e.md
Labels: ok to merge :ok_hand:, ready to test :elephant:
