Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2022-12, with the labels that each got.

#1071 test: PSQL client pod to verify service connectivity.
  tests/e2e/asserts_test.go
  tests/e2e/connection_test.go
  tests/e2e/suite_test.go
  tests/e2e/update_user_test.go
  tests/utils/psql_client.go
Labels: ok to merge :ok_hand:, backport-requested, release-1.16, release-1.17, release-1.18

#1120 doc: remove references to CNPG sandbox
  docs/src/monitoring.md
  docs/src/operator_capability_levels.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1084 Split the continuous-delivery pipeline
  .github/e2e-matrix-generator.py
  .github/workflows/chatops-dispatcher.yml
  .github/workflows/chatops-receiver.yml
  .github/workflows/chatops.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1134 fix: Give default value for schedule workflow
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1132 docs: about developing process
  CONTRIBUTING.md
  contribute/README.md
  contribute/e2e_testing_environment/README.md
Labels: backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1144 chore: add a fluent request client to ease API calls
  pkg/resources/doc.go
  pkg/resources/patchtype.go
  pkg/resources/request.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1145 fix: ensure that we create secret and services only when not found
  controllers/cluster_create.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1149 chore: upgrade to pgx v5.2.0
  go.mod
  go.sum
  internal/cmd/manager/instance/run/lifecycle/run.go
  internal/management/controller/instance_controller.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/join.go
  pkg/management/postgres/logicalimport/database.go
  pkg/management/postgres/logicalimport/role.go
  pkg/management/postgres/logicalimport/roleinheritance.go
  pkg/management/postgres/pool/pool.go
  pkg/utils/db.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1167 chore: Add Armando Ruocco (@armru) as a new maintainer
  .wordlist-en-custom.txt
  CODEOWNERS
  README.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1166 feat: update Go version from 1.18 to 1.19
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
  go.mod
Labels: ok to merge :ok_hand:

#1174 chore: take PostgreSQL image from the pkg/versions/versions.go
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1164 fix: permissions error on bootstrap
  internal/cmd/manager/bootstrap/cmd.go
Labels: backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1135 fix: wal pvc not deleted while scaling down.
  controllers/cluster_scale.go
  controllers/cluster_scale_test.go
  controllers/suite_test.go
  tests/e2e/asserts_test.go
  tests/e2e/scaling_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1161 chore: minor fixes for arm based macs
  Makefile
  contribute/development_environment/README.md
  hack/e2e/run-e2e-k3d.sh
  hack/e2e/run-e2e-kind.sh
  hack/install-cnpg-plugin.sh
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1184 doc: provide troubleshooting emergency backup instructions
  docs/src/troubleshooting.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1148 doc: link to the "Release updates" discussion
  contribute/README.md
  docs/src/supported_releases.md
Labels: backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1125 test: refactor e2e to use psql client pod.
  .github/workflows/continuous-delivery.yml
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/cluster_monolithic_test.go
  tests/e2e/cluster_setup_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/connection_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/failover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/hibernation_test.go
  tests/e2e/metrics_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/pg_basebackup_test.go
  tests/e2e/pg_data_corruption_test.go
  tests/e2e/pgbouncer_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/suite_test.go
  tests/e2e/syncreplicas_test.go
  tests/utils/environment.go
  tests/utils/postgres.go
  tests/utils/psql_client.go
  tests/utils/secrets.go
  tests/utils/service.go
  tests/utils/time.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#967 Better support for Istio
  .gitignore
  internal/cmd/manager/instance/initdb/cmd.go
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/cmd/manager/instance/restore/cmd.go
  internal/cmd/manager/instance/run/cmd.go
  internal/cmd/plugin/hibernate/on.go
  internal/management/istio/doc.go
  internal/management/istio/istio.go
  pkg/management/client.go
  pkg/resources/retry.go
Labels: backport-requested :arrow_backward:, ready to test :elephant:, release-1.17, release-1.18

#1182 feat: nodeAffinity support
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
  pkg/specs/pods.go
Labels: ok to merge :ok_hand:

#1130 docs: add notes of deprecated postgresql label
  docs/src/monitoring.md
  docs/src/quickstart.md
  docs/src/release_notes/edb-cloud-native-postgresql.md
  docs/src/troubleshooting.md
  pkg/postgres/testdata/lsn_overflow.json
  pkg/specs/pods.go
  pkg/utils/labels_annotations.go
  tests/e2e/asserts_test.go
  tests/e2e/logs_test.go
  tests/e2e/operator_unavailable_test.go
  tests/utils/cluster.go
Labels: backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1202 Remove docs reference to future functionality
  docs/src/bootstrap.md
Labels: backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1160 fix: IsPostgresqlReady condition inverted
  pkg/postgres/status.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1097 feat: Create the fio command for the kubectl plugin
  .wordlist-en-custom.txt
  cmd/kubectl-cnpg/main.go
  docs/src/benchmarking.md
  docs/src/cnpg-plugin.md
  docs/src/images/write_bw.1-2Draw.png
  internal/cmd/plugin/fio/cmd.go
  internal/cmd/plugin/fio/doc.go
  internal/cmd/plugin/fio/fio.go
  internal/cmd/plugin/plugin.go
Labels: ok to merge :ok_hand:

#1194 fix: filter out replicas and jobs from nodeToClusters map
  controllers/cluster_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1205 fix: use correct size to update WAL PVC
  api/v1/cluster_types.go
  controllers/cluster_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1216 fix: respect configured pg-wal when restoring
  internal/cmd/manager/instance/restore/cmd.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1217 fix: installation of ginkgo
  go.mod
  go.sum
  hack/e2e/run-e2e.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1223 ci: track ginkgo deps in internal/tools/tools.go
  go.mod
  go.sum
  hack/e2e/run-e2e.sh
  internal/tools/tools.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1222 fix: adding the SCC checks to 1.17
  tests/utils/environment.go
  tests/utils/psql_client.go
Labels: ok to merge :ok_hand:

#1219 doc: release notes for December release
  contribute/release_procedure.md
  docs/src/release_notes/v1.16.md
  docs/src/release_notes/v1.17.md
  docs/src/release_notes/v1.18.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, release-1.16, release-1.17, release-1.18

#1231 Amend 1.18.1 release notes
  docs/src/release_notes/v1.18.md
Labels: ok to merge :ok_hand:, no-issue, do not backport

#1232 doc: move 1.16 in old releases folder
  docs/src/release_notes.md
  docs/src/release_notes/old/v1.16.md
Labels: no-issue

#1213 fix: don't look for PodMonitor when not needed
  controllers/cluster_create.go
  docs/src/quickstart.md
  docs/src/samples/cluster-example-monitoring.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.16, release-1.17, release-1.18

#1238 fix: avoid PodMonitor reconcile on no Prometheus
  controllers/cluster_create.go
Labels: ok to merge :ok_hand:, no-issue

#1235 ci: smoke test release-* branches on a daily schedule basis
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:

#1261 ci: skip smoke test on EOLed version 1.16
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18

#1257 test: fix online upgrade test in 1.17
  tests/e2e/upgrade_test.go
Labels: no-issue

#1248 test: avoid starting postgres server in the psql pod
  tests/e2e/suite_test.go
  tests/utils/commons.go
  tests/utils/psql_client.go
  tests/utils/run.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1265 Improve testUtils.GetCredentials to support custom secrets
  tests/utils/secrets.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1247 test: enhance E2E test's observability
  hack/e2e/run-e2e.sh
  tests/e2e/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18
