Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2022-08, with the labels that each got.

#504 chore: set timestamps to RFC3339Micro
  pkg/utils/time.go
  pkg/utils/time_test.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#440 chore: forcing imports sorting using gci
  .golangci.yml
  api/v1/cluster_configuration_test.go
  api/v1/cluster_webhook_test.go
  api/v1/scheduledbackup_types_test.go
  api/v1/suite_test.go
  cmd/kubectl-cnpg/main.go
  controllers/cluster_delete_test.go
  controllers/cluster_status_test.go
  controllers/pooler_controller_test.go
  controllers/pooler_predicates_test.go
  controllers/pooler_resources_test.go
  controllers/pooler_status_test.go
  controllers/pooler_update_test.go
  controllers/suite_test.go
  internal/cmd/manager/manager.go
  internal/cmd/manager/show/cmd.go
  internal/cmd/manager/walarchive/cmd.go
  internal/cmd/manager/walrestore/cmd_test.go
  internal/cmd/plugin/maintenance/maintenance.go
  internal/cmd/plugin/report/logs.go
  internal/management/controller/instance_controller.go
  internal/management/controller/manager.go
  pkg/management/barman/credentials/env.go
  pkg/management/pgbouncer/config/config.go
  pkg/management/pgbouncer/config/secrets_test.go
  pkg/management/postgres/configuration_test.go
  pkg/postgres/status_test.go
  pkg/specs/jobs_test.go
  pkg/specs/pods_test.go
  pkg/utils/hash/hash.go
  pkg/utils/job_conditions_test.go
  pkg/utils/labels_annotations_test.go
  pkg/utils/ownership.go
  pkg/utils/time.go
  pkg/utils/time_test.go
Labels: go, ok to merge :ok_hand:, chore, backport-requested :arrow_backward:

#519 chore: remove redudant storage validation webhook
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
Labels: ready to test :elephant:

#526 fix(docs): wrong path to ssl certificate
  docs/src/ssl_connections.md
Labels: ready to test :elephant:

#531 fix: timeouts for restarts and switchovers
  internal/cmd/manager/instance/run/lifecycle/lifecycle.go
Labels: ok to merge :ok_hand:

#535 chore: use the new webtest location
  docs/src/ssl_connections.md
  tests/e2e/fixtures/fastfailover/webtest-syncreplicas.yaml
  tests/e2e/fixtures/fastfailover/webtest.yaml
  tests/e2e/fixtures/fastswitchover/webtest.yaml
  tests/utils/webapp.go
Labels: backport-requested :arrow_backward:

#549 chore: log pvc label update once the operation is done
  controllers/replicas.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:, backport-requested :arrow_backward:

#461 feat: set cluster condition ready when the phase is healthy
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  controllers/cluster_status.go
  docs/src/troubleshooting.md
  tests/e2e/asserts_test.go
  tests/e2e/cluster_setup_test.go
  tests/utils/cluster.go
Labels: enhancement :magic_wand:, go, ok to merge :ok_hand:, do not backport

#537 chore: use Apache benchmark instead of hey
  tests/e2e/asserts_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fixtures/fastfailover/apache-benchmark-webtest.yaml
  tests/e2e/fixtures/fastswitchover/apache-benchmark-webtest.yaml
Labels: ok to merge :ok_hand:, ready to test :elephant:

#543 chore: improve operator deployment security
  config/manager/manager.yaml
Labels: ok to merge :ok_hand:, ready to test :elephant:, do not backport

#553 chore: add basic script to report diffs release branch <-> main
  hack/show-release-diffs.sh
Labels: chore, backport-requested :arrow_backward:

#547 fix: use `RetryOnConflict` to update resources
  pkg/certs/k8s.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:

#534 chore: adds instanceName and clusterName labels on jobs, pods, pvcs
  controllers/cluster_create.go
  controllers/suite_test.go
  pkg/specs/jobs.go
  pkg/specs/pods.go
  pkg/specs/pvcs.go
  pkg/utils/labels_annotations.go
Labels: ready to test :elephant:

#560 refactor: allows the override of the default external secret directory
  pkg/management/external/utils.go
Labels: ok to merge :ok_hand:

#579 chore(linter): fix warnings in show-release-diffs.sh script
  hack/show-release-diffs.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:

#573 doc: release notes for 1.16.1 and 1.15.3
  docs/src/release_notes/v1.15.md
  docs/src/release_notes/v1.16.md
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:

#591 feat: use the Docker API while updating the PostgreSQL version list
  .github/postgres-versions-update.py
Labels: ok to merge :ok_hand:

#575 chore: pre-load helper images in testing cluster
  hack/setup-cluster.sh
Labels: ready to test :elephant:

#603 chore: skip Krew release if not the latest
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:

#584 feat: allow configuring log-level TCP parameters for PgBouncer
  api/v1/pooler_webhook.go
Labels: ready to test :elephant:

#567 chore: support multiarch for testing
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:

#513 feat: introduce WAL archive volume
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_controller.go
  controllers/cluster_create.go
  controllers/cluster_status.go
  controllers/cluster_upgrade.go
  controllers/suite_test.go
  docs/src/api_reference.md
  docs/src/failure_modes.md
  docs/src/operator_capability_levels.md
  docs/src/samples/cluster-example-wal-storage.yaml
  docs/src/storage.md
  docs/src/troubleshooting.md
  internal/cmd/manager/instance/initdb/cmd.go
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/cmd/manager/instance/restore/cmd.go
  pkg/fileutils/fileutils.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/join.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/restore_test.go
  pkg/specs/jobs.go
  pkg/specs/pvcs.go
  pkg/specs/volumes.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:

#588 fix(docs): fix spec.postgresql.ldap.tls field description
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
Labels: ok to merge :ok_hand:, ready to test :elephant:

#613 chore: add unit test coverage summary
  .github/workflows/continuous-delivery.yml
  Makefile
Labels: ok to merge :ok_hand:

#629 test: use fixtrues as e2e test yaml file directory
  tests/e2e/asserts_test.go
  tests/e2e/failover_test.go
  tests/e2e/fixtures/rolling_updates/cluster-single-instance.yaml
  tests/e2e/fixtures/rolling_updates/cluster-three-instances.yaml
  tests/e2e/fixtures/rolling_updates/cluster-using-primary-update-method.yaml
  tests/e2e/fixtures/upgrade/cluster2.yaml
  tests/e2e/suite_test.go
  tests/e2e/switchover_test.go
Labels: ok to merge :ok_hand:

#637 Improve compatibility with go 1.19
  api/v1/cluster_types.go
  controllers/cluster_controller.go
  controllers/cluster_status.go
  controllers/cluster_upgrade.go
  controllers/pooler_update.go
  docs/src/api_reference.md
  internal/cmd/manager/backup/cmd.go
  internal/cmd/manager/instance/run/lifecycle/reaper.go
  internal/cmd/manager/instance/status/cmd.go
  internal/cmd/plugin/report/cluster_report.go
  internal/cmd/plugin/report/operator_report.go
  internal/cmd/plugin/report/output.go
  internal/management/cache/client/client.go
  internal/management/controller/instance_controller.go
  pkg/certs/k8s_test.go
  pkg/configfile/configfile_test.go
  pkg/configparser/configparser.go
  pkg/fileutils/fileutils.go
  pkg/fileutils/fileutils_test.go
  pkg/fileutils/suite_test.go
  pkg/management/barman/spool/spool_test.go
  pkg/management/postgres/instance_test.go
  pkg/management/postgres/logpipe/linelogpipe.go
  pkg/management/postgres/logpipe/logpipe.go
  pkg/management/postgres/logpipe/logpipe_test.go
  pkg/management/postgres/pidfile_test.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/restore_test.go
  pkg/management/postgres/utils/version.go
  pkg/postgres/configuration.go
  pkg/postgres/version.go
  pkg/utils/hash/hash.go
  pkg/utils/imagename.go
  pkg/utils/pod_conditions.go
  tests/utils/environment.go
  tests/utils/release.go
Labels: ok to merge :ok_hand:

#651 Fix files referenced in E2E tests with wrong name
  tests/e2e/backup_restore_test.go
Labels: ok to merge :ok_hand:

#641 fix bug in GetAllAccessibleDatabases where a failed query triggers a panic
  pkg/management/postgres/utils/utils.go
Labels: ok to merge :ok_hand:, ready to test :elephant:

#627 chore: add comments to workflows for clarity
  .github/dependabot.yml
  .github/workflows/chatops-dispatcher.yml
  .github/workflows/chatops-receiver.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/latest-postgres-version-check.yml
  .github/workflows/registry-clean.yml
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:

#616 chore: split retry timeout for client and commands
  tests/e2e/suite_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/utils/commons.go
  tests/utils/environment.go
  tests/utils/run.go
Labels: ready to test :elephant:

#556 feat: refine stats in E2E summary
  .github/summarize-test-results.py
  .github/summarize_test_results.py
  .github/workflows/continuous-delivery.yml
Labels: backport-requested :arrow_backward:, ready to test :elephant:

#632 chore(pvc): add instance role on the pvc labels
  controllers/cluster_controller.go
  controllers/replicas.go
  pkg/specs/pvcs.go
Labels: ok to merge :ok_hand:

#642 Load additional libraries when initializing database
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance.go
Labels: backport-requested :arrow_backward:, ready to test :elephant:

#653 chore: load helper images during cluster creation
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:

#565 chore: reduce the amount of tests per push and pull_request
  .github/e2e-matrix-generator.py
  .github/workflows/chatops-dispatcher.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/continuous-delivery.yml
  Makefile
Labels: ok to merge :ok_hand:, chore, backport-requested :arrow_backward:, ready to test :elephant:

#643 feat: adding a destroy command to kubectl-cnpg
  cmd/kubectl-cnpg/main.go
  controllers/cluster_controller.go
  controllers/cluster_create.go
  controllers/cluster_predicates.go
  controllers/cluster_status.go
  controllers/cluster_status_test.go
  docs/src/cnpg-plugin.md
  internal/cmd/plugin/destroy/cmd.go
  internal/cmd/plugin/destroy/destroy.go
  pkg/specs/pvcs.go
Labels: ok to merge :ok_hand:
