Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-05, with the labels that each got.

#2000 chore: disable Dependabot
  .github/dependabot.yml
  .github/workflows/pr_verify_linked_issue.yml
Labels: backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2004 feat: use separate transactions to reconcile users' credentials
  internal/management/controller/instance_controller.go
  pkg/management/postgres/utils/roles.go
  pkg/management/postgres/utils/roles_test.go
  pkg/management/postgres/utils/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#1937 Prevent creating Kubernetes client when calling completion command
  cmd/kubectl-cnpg/main.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#1991 ci: update to CIclops 1.2.0
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2012 doc: cover `cnpg` plugin upgrade with `krew`
  docs/src/cnpg-plugin.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2018 chore: use pgbouncer 1.19 by default
  pkg/specs/pgbouncer/deployments.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2021 fix(doc): use correct metric name for example dashboard
  docs/src/samples/cluster-example-monitoring.yaml
Labels: backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2032 doc: update document with more information about in-place restart
  docs/src/rolling_update.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2007 Avoid space-dash-space pattern in section headings
  docs/src/operator_capability_levels.md
  docs/src/quickstart.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2040 fix: run controller cmd with `SilenceErrors`
  internal/cmd/manager/controller/cmd.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2013 feat: add option to override default kubernetes scheduler
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
  docs/src/api_reference.md
  internal/cmd/plugin/pgbench/pgbench.go
  pkg/specs/jobs.go
  pkg/specs/pods.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2015 test: deprecate CreateNamespace
  tests/e2e/apparmor_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/pgbouncer_test.go
  tests/e2e/pgbouncer_types_test.go
  tests/utils/environment.go
  tests/utils/namespace.go
  tests/utils/namespace_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2052 ci: disable setup-go caching when running golangci-lint
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2053 test: fix k3s images detection method
  hack/e2e/run-e2e-k3d.sh
  hack/e2e/run-e2e-kind.sh
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2045 fix: make logs in report plugin json parsable.
  internal/cmd/plugin/report/cluster.go
  internal/cmd/plugin/report/cluster_report.go
  internal/cmd/plugin/report/logs.go
  internal/cmd/plugin/report/operator.go
  internal/cmd/plugin/report/operator_report.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2072 test: add e2e-test-local make target
  Makefile
  hack/e2e/run-e2e-local.sh
  hack/e2e/run-e2e.sh
  tests/e2e/upgrade_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2048 chore: use createUniquenamespace
  tests/e2e/backup_restore_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/cluster_monolithic_test.go
  tests/e2e/cluster_objectmeta_test.go
  tests/e2e/cluster_setup_test.go
  tests/e2e/cnpg_certificates_test.go
  tests/e2e/config_support_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/connection_test.go
  tests/e2e/declarative_hibernation_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/eviction_test.go
  tests/e2e/failover_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fencing_test.go
  tests/e2e/hibernation_test.go
  tests/e2e/initdb_test.go
  tests/e2e/logs_test.go
  tests/e2e/managed_roles_test.go
  tests/e2e/metrics_test.go
  tests/e2e/nodeselector_test.go
  tests/e2e/operator_ha_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/pg_basebackup_test.go
  tests/e2e/pg_data_corruption_test.go
  tests/e2e/pg_wal_volume_test.go
  tests/e2e/pgbouncer_metrics_test.go
  tests/e2e/pvc_deletion_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/replication_slot_test.go
  tests/e2e/rolling_update_test.go
  tests/e2e/scaling_test.go
  tests/e2e/storage_expansion_test.go
  tests/e2e/switchover_test.go
  tests/e2e/syncreplicas_test.go
  tests/e2e/tolerations_test.go
  tests/e2e/update_user_test.go
  tests/e2e/upgrade_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/e2e/webhook_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2076 test: make sure minio-client config directory is writable
  tests/utils/minio.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2083 chore: avoid multiple casting of webhook.DefaultServer
  internal/cmd/manager/controller/controller.go
Labels: backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2128 test: fix unbound variable error in run-e2e-local.sh
  hack/e2e/run-e2e-local.sh
Labels: no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2051 test: use gracePeriodSeconds=1 in e2e test while deleting pod
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/failover_test.go
  tests/e2e/logs_test.go
  tests/e2e/operator_ha_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/pg_data_corruption_test.go
  tests/e2e/pvc_deletion_test.go
  tests/e2e/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#1960 feat: recovery from VolumeSnapshot, and kubectl-cnpg snapshot subcommand
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  cmd/kubectl-cnpg/main.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/cluster_create.go
  docs/src/api_reference.md
  docs/src/bootstrap.md
  docs/src/cnpg-plugin.md
  docs/src/samples/cluster-restore-pvc.yaml
  docs/src/samples/cluster-restore-snapshot.yaml
  go.mod
  go.sum
  internal/cmd/plugin/plugin.go
  internal/cmd/plugin/snapshot/cmd.go
  internal/cmd/plugin/snapshot/doc.go
  pkg/management/postgres/restore.go
  pkg/reconciler/persistentvolumeclaim/build.go
  pkg/reconciler/persistentvolumeclaim/instance.go
  pkg/reconciler/persistentvolumeclaim/reconciler_test.go
  pkg/reconciler/persistentvolumeclaim/resources.go
  pkg/resources/persistentvolumeclaim.go
Labels: ok to merge :ok_hand:, do not squash :warning:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2134 chore: update manifests
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2126 fix: report the correct PG version in the metrics
  pkg/management/postgres/webserver/metricserver/pg_collector.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2136 feat: improve logging when deleting Pods
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2067 ci: make test timeouts configurable
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/cluster_monolithic_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/eviction_test.go
  tests/e2e/failover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fencing_test.go
  tests/e2e/hibernation_test.go
  tests/e2e/pg_basebackup_test.go
  tests/e2e/pg_data_corruption_test.go
  tests/e2e/pg_wal_volume_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/rolling_update_test.go
  tests/e2e/suite_test.go
  tests/e2e/upgrade_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/levels.go
  tests/utils/backup.go
  tests/utils/nodes/drain.go
  tests/utils/timeouts.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2094 chore: improve signature and add unit test for getPassword
  internal/management/controller/roles/runnable.go
  internal/management/controller/roles/runnable_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2141 fix: kind version
  .github/renovate.json5
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2151 chore: fix renovate to properly use the kind version to update the CI
  .github/renovate.json5
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2140 docs: use the correct walStorage key
  docs/src/bootstrap.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2152 chore: add bash version requirement in development doc
  contribute/development_environment/README.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2057 feat: Add `pg_failover_slots` to managed extensions
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  docs/src/index.md
  docs/src/operator_capability_levels.md
  docs/src/postgresql_conf.md
  pkg/postgres/configuration.go
  pkg/postgres/configuration_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2157 fix: unbound variable with k3s engine
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2158 chore: add `nodeSelector` to `cnpg pgbench` jobs
  docs/src/benchmarking.md
  docs/src/cnpg-plugin.md
  internal/cmd/plugin/pgbench/cmd.go
  internal/cmd/plugin/pgbench/pgbench.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2166 doc: add `nodeSelector` in `kube-stack-config` example
  docs/src/samples/monitoring/kube-stack-config.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#1916 Update grafana-dashboard.json
  docs/src/quickstart.md
  docs/src/samples/monitoring/grafana-configmap.yaml
  docs/src/samples/monitoring/grafana-dashboard.json
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20
