Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-03, with the labels that each got.

#1605 chore(renovate): fix GOLANG_VERSION and GOLANGCI_LINT
  .github/renovate.json5
  internal/cmd/manager/controller/controller.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1637 docs: fix ADOPTERS.md link in README
  README.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1607 chore: removes rke-ec2 leftovers
  .github/vpc_destroy.py
  hack/e2e/eks-cluster.yaml.template
  hack/e2e/rke-ec2/.gitignore
  hack/e2e/rke-ec2/README.md
  hack/e2e/rke-ec2/aws/ami.tf
  hack/e2e/rke-ec2/aws/iam.tf
  hack/e2e/rke-ec2/aws/keys.tf
  hack/e2e/rke-ec2/aws/main.tf
  hack/e2e/rke-ec2/aws/nodes.tf
  hack/e2e/rke-ec2/aws/outputs.tf
  hack/e2e/rke-ec2/aws/variables.tf
  hack/e2e/rke-ec2/interface.tf
  hack/e2e/rke-ec2/provider.tf
  hack/e2e/rke-ec2/rke.tf
  hack/e2e/rke-ec2/storage-class.yaml
  hack/e2e/rke-ec2/versions.tf
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1583 chore: use patch instead of update for Backup reconciler and command
  controllers/backup_controller.go
  internal/cmd/manager/walarchive/cmd.go
  pkg/conditions/conditions.go
  pkg/management/postgres/backup.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1602 feat: support override default backup target policy in cluster
  api/v1/backup_types.go
  api/v1/scheduledbackup_types.go
  api/v1/scheduledbackup_types_test.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  controllers/backup_controller.go
  docs/src/api_reference.md
  docs/src/backup_recovery.md
  docs/src/cnpg-plugin.md
  internal/cmd/plugin/backup/cmd.go
  tests/e2e/backup_restore_test.go
  tests/e2e/fixtures/backup/minio/backup-minio-override-target.yaml
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-primary.yaml.template
  tests/utils/backup.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1647 fix: commit the completed backup changes during takeBackup execution
  pkg/management/postgres/backup.go
Labels: risk :boom:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1680 feat: improve compatibility with linkerd
  .wordlist-en-custom.txt
  internal/cmd/manager/instance/initdb/cmd.go
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/cmd/manager/instance/restore/cmd.go
  internal/cmd/manager/instance/run/cmd.go
  internal/management/linkerd/doc.go
  internal/management/linkerd/linkerd.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1716 fix: error handling in the probes
  pkg/management/postgres/probes.go
  pkg/management/postgres/probes_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1663 fix: ensure nodeAffinity is applied
  pkg/specs/pods.go
  pkg/specs/pods_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1728 feat: Introduce failover delay during OnlineUpgrading phase
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/replicas.go
  docs/src/api_reference.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1668 feat: kubectl-cnpg psql subcommand
  cmd/kubectl-cnpg/main.go
  docs/src/cnpg-plugin.md
  internal/cmd/plugin/psql/cmd.go
  internal/cmd/plugin/psql/doc.go
  internal/cmd/plugin/psql/psql.go
  internal/cmd/plugin/psql/psql_test.go
  internal/cmd/plugin/psql/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1650 feat: execute barman backup with `--name` flag when supported
  api/v1/backup_types.go
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  docs/src/api_reference.md
  pkg/management/barman/backupdelete.go
  pkg/management/barman/backuplist.go
  pkg/management/barman/backuplist_test.go
  pkg/management/barman/capabilities/constants.go
  pkg/management/barman/capabilities/detect.go
  pkg/management/barman/capabilities/type.go
  pkg/management/catalog/catalog.go
  pkg/management/catalog/catalog_test.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/backup_test.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/webserver/local.go
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-legacy.yaml.template
Labels: risk :boom:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1666 fix: fill probe archiver status on replicas too
  pkg/management/postgres/probes.go
  pkg/management/postgres/probes_test.go
  pkg/postgres/status.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1711 tests: relax E2E timeouts and make SQL statements idempotent
  tests/e2e/asserts_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/cluster_monolithic_test.go
  tests/e2e/cluster_setup_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/eviction_test.go
  tests/e2e/failover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fencing_test.go
  tests/e2e/logs_test.go
  tests/e2e/pg_data_corruption_test.go
  tests/e2e/pg_wal_volume_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/syncreplicas_test.go
  tests/e2e/update_user_test.go
  tests/e2e/upgrade_test.go
  tests/utils/environment.go
  tests/utils/postgres.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1746 fix: our implementation of hasName requires Barman 3.4
  pkg/management/barman/capabilities/detect.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1724 doc: release notes 1.19.1, 1.18.3, 1.17.5
  docs/src/release_notes.md
  docs/src/release_notes/old/v1.17.md
  docs/src/release_notes/v1.18.md
  docs/src/release_notes/v1.19.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1756 chore: golangci-lint 1.52 comes with a new version of revive linter
  api/v1/backup_webhook.go
  api/v1/pooler_webhook.go
  api/v1/scheduledbackup_webhook.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  internal/cmd/manager/controller/controller.go
  internal/cmd/manager/instance/initdb/cmd.go
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/cmd/manager/instance/restore/cmd.go
  internal/cmd/manager/instance/run/cmd.go
  internal/cmd/manager/instance/run/lifecycle/run.go
  internal/cmd/plugin/fio/cmd.go
  internal/cmd/plugin/fio/fio.go
  internal/management/controller/instance_controller.go
  internal/management/controller/instance_startup.go
  internal/management/controller/slots/reconciler/replicationslot_test.go
  internal/management/controller/slots/runner/runner_test.go
  pkg/management/postgres/logicalimport/database.go
  pkg/management/postgres/logicalimport/microservice.go
  pkg/management/postgres/logicalimport/monolith.go
  pkg/management/postgres/logicalimport/role.go
  pkg/management/postgres/probes.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/webserver/remote.go
  pkg/reconciler/persistentvolumeclaim/reconciler_test.go
  pkg/resources/retry.go
  pkg/utils/fencing.go
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19

#1730 chore: remove manager dependency from controller unit tests
  Makefile
  controllers/cluster_delete_test.go
  controllers/cluster_status_test.go
  controllers/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1769 chore: stop backporting or running tests on branch release-1.17
  .github/renovate.json5
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: backport-requested :arrow_backward:, release-1.18, release-1.19

#1762 fix: trigger reconcile loop when managed user secret changed
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_status.go
  docs/src/api_reference.md
  internal/management/controller/roles/contract.go
  internal/management/controller/roles/reconciler.go
  internal/management/controller/roles/roles.go
  internal/management/controller/roles/runnable.go
  internal/management/controller/roles/runnable_test.go
  tests/e2e/fixtures/managed_roles/cluster-managed-roles.yaml
Labels: no-issue

#1785 test: ensure that the scale-down behaviour remain consistent
  controllers/cluster_controller_test.go
  controllers/cluster_status_test.go
  controllers/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1780 ci: add code verification in auto backport
  .github/workflows/backport.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1799 ci: use the proper go version on the backport workflow
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19

#1657 feat: declarative hibernation
  .wordlist-en-custom.txt
  controllers/cluster_controller.go
  controllers/cluster_status.go
  docs/mkdocs.yml
  docs/src/declarative_hibernation.md
  internal/cmd/plugin/status/status.go
  pkg/reconciler/hibernation/doc.go
  pkg/reconciler/hibernation/reconciler.go
  pkg/reconciler/hibernation/reconciler_test.go
  pkg/reconciler/hibernation/status.go
  pkg/reconciler/hibernation/status_test.go
  pkg/reconciler/hibernation/suite_test.go
  tests/e2e/declarative_hibernation_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, ready to test :elephant:, release-1.18, release-1.19

#1811 chore: refactor stream log functions to easy handle options
  docs/src/cnpg-plugin.md
  internal/cmd/plugin/report/logs.go
  internal/cmd/plugin/report/operator_report.go
  pkg/utils/logs/logs.go
  pkg/utils/logs/logs_test.go
  pkg/utils/logs/suite_test.go
  tests/e2e/suite_test.go
  tests/utils/cluster.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1823 chore: make the postgres kind explicit in CI/CD
  .github/e2e-matrix-generator.py
  .github/generate-test-artifacts.py
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19

#1755 feat: configurable creation of the `-any` service
  controllers/cluster_create.go
  controllers/cluster_create_test.go
  docs/src/applications.md
  docs/src/operator_conf.md
  internal/configuration/configuration.go
  pkg/specs/jobs.go
  pkg/specs/pods.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19
