Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-08, with the labels that each got.

#2499 fix: add AppArmor only when the matching container is present
  pkg/reconciler/instance/metadata.go
  pkg/reconciler/instance/metadata_test.go
  pkg/reconciler/persistentvolumeclaim/metadata.go
  pkg/specs/jobs.go
  pkg/specs/pods.go
  pkg/utils/labels_annotations.go
  pkg/utils/labels_annotations_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2529 chore: ensure array cell exists during appArmor iteration
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2480 chore: add pool.Pooler interface to pgbouncer/metricsserver
  pkg/management/pgbouncer/metricsserver/metricsserver_test.go
  pkg/management/pgbouncer/metricsserver/pgbouncer_collector.go
  pkg/management/pgbouncer/metricsserver/pools_test.go
  pkg/management/pgbouncer/metricsserver/stats_test.go
  pkg/management/pgbouncer/metricsserver/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2416 doc: clarify cronjob syntax
  docs/src/backup_recovery.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2533 Adjust admonition calling out EOL versions in release notes
  docs/src/release_notes/old/v1.15.md
  docs/src/release_notes/old/v1.16.md
  docs/src/release_notes/old/v1.17.md
  docs/src/release_notes/old/v1.18.md
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2537 chore(docs): restructure backup/recovery documentation
  docs/mkdocs.yml
  docs/src/appendixes/object_stores.md
  docs/src/backup.md
  docs/src/backup_recovery.md
  docs/src/bootstrap.md
  docs/src/installation_upgrade.md
  docs/src/kubectl-plugin.md
  docs/src/recovery.md
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2540 ci: fix latest release branch pattern
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2544 fix: ensure that the primary instance is always recreated first
  controllers/cluster_create.go
  pkg/specs/pg_pods.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2526 test: E2E kind env configuration to support volumesnapshot
  .github/workflows/continuous-delivery.yml
  .wordlist-en-custom.txt
  hack/e2e/run-e2e-kind.sh
  hack/e2e/run-e2e-local.sh
  hack/setup-cluster.sh
  tests/e2e/asserts_test.go
  tests/e2e/fixtures/volume_snapshot/cluster_volume_snapshot.yaml.template
  tests/e2e/volume_snapshot_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2550 chore(docs): refactor `bootstrap.recovery` section
  docs/src/bootstrap.md
  docs/src/recovery.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20

#2569 fix(prometheus): set wal_write_time and wal_sync_time as float64
  docs/src/monitoring.md
  pkg/management/postgres/probes.go
  pkg/management/postgres/webserver/metricserver/wal.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2577 Fix typo in test
  pkg/management/postgres/instance_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2458 chore: align structs to reduce space usage
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  contribute/e2e_testing_environment/README.md
  contribute/e2e_testing_environment/pyroscope.png
  controllers/backup_controller.go
  controllers/cluster_controller_test.go
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
  controllers/replicas.go
  controllers/replicas_test.go
  docs/src/api_reference.md
  docs/src/operator_conf.md
  internal/cmd/plugin/status/status.go
  internal/configuration/configuration.go
  internal/management/controller/roles/contract.go
  pkg/concurrency/executed.go
  pkg/management/barman/capabilities/type.go
  pkg/management/postgres/logicalimport/role.go
  pkg/management/postgres/probes.go
  pkg/postgres/configuration.go
  pkg/postgres/status.go
  pkg/postgres/status_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2392 chore: update cert-manager CA injection scaffolding
  config/certmanager/certificate.yaml
  config/crd/kustomization.yaml
  config/crd/patches/webhook_in_poolers.yaml
  config/default/kustomization.yaml
  config/default/mutatingwebhookcainjection_patch.yaml
  config/default/validatingwebhookcainjection_patch.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2607 (docs): Add CNDI to ADOPTERS.md
  ADOPTERS.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2609 chore: fix linter errors in new version of golangci-lint
  .golangci.yml
  api/v1/cluster_webhook.go
  pkg/management/barman/backupdelete.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2243 chore: detect PodSpec drift in pod rollout, and clarify rollout code
  controllers/cluster_controller.go
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
  pkg/specs/pods.go
  pkg/utils/labels_annotations.go
  pkg/utils/operations.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2618 fix: encode podSpec annotation in JSON
  controllers/cluster_upgrade.go
  pkg/specs/pods.go
Labels: ok to merge :ok_hand:, no-issue

#2528 feat: declarative cold snapshot backup
  .wordlist-en-custom.txt
  api/v1/backup_types.go
  api/v1/backup_types_test.go
  api/v1/cluster_types.go
  api/v1/scheduledbackup_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  config/rbac/role.yaml
  controllers/backup_controller.go
  docs/mkdocs.yml
  docs/src/api_reference.md
  docs/src/backup.md
  docs/src/backup_barmanobjectstore.md
  docs/src/backup_recovery.md
  docs/src/backup_volumesnapshot.md
  docs/src/index.md
  docs/src/operator_capability_levels.md
  docs/src/recovery.md
  docs/src/replica_cluster.md
  docs/src/wal_archiving.md
  internal/cmd/plugin/backup/cmd.go
  internal/cmd/plugin/destroy/destroy.go
  internal/cmd/plugin/fence/fence.go
  internal/cmd/plugin/hibernate/on.go
  internal/cmd/plugin/snapshot/cmd.go
  internal/plugin/resources/instance.go
  internal/scheme/scheme.go
  pkg/management/postgres/backup.go
  pkg/reconciler/persistentvolumeclaim/resources.go
  pkg/resources/fencing.go
  pkg/utils/operations.go
  pkg/utils/operations_test.go
  pkg/utils/snapshot/doc.go
  pkg/utils/snapshot/executor.go
  tests/e2e/fixtures/volume_snapshot/cluster-pvc-snapshot.yaml.template
  tests/e2e/fixtures/volume_snapshot/declarative-backup-cluster-restore.yaml.template
  tests/e2e/fixtures/volume_snapshot/declarative-backup-cluster.yaml.template
  tests/e2e/fixtures/volume_snapshot/declarative-backup.yaml.template
  tests/e2e/volume_snapshot_test.go
  tests/utils/fence.go
Labels: ok to merge :ok_hand:, do not backport

#2591 fix: execute reconciliation of backups unless they're marked as `failed` or `completed`
  controllers/backup_controller.go
  controllers/backup_controller_test.go
  controllers/suite_test.go
Labels: risk :boom:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2627 feat: add the backupName label to the VolumeSnapshots
  controllers/backup_controller.go
  pkg/utils/labels_annotations.go
  tests/e2e/volume_snapshot_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2625 fix: ensure that `ContinuousArchiving` is set as failed in case of errors
  internal/cmd/manager/walarchive/cmd.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2606 chore: move api documentation generation from k8s-api-docgen to genref
  .github/workflows/continuous-integration.yml
  .wordlist-en-custom.txt
  Makefile
  api/v1/backup_types.go
  api/v1/cluster_types.go
  api/v1/doc.go
  api/v1/pooler_types.go
  api/v1/scheduledbackup_types.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  docs/config.yaml
  docs/k8s-api-docgen.yaml
  docs/markdown/members.tpl
  docs/markdown/pkg.tpl
  docs/markdown/type.tpl
  docs/mkdocs.yml
  docs/src/api_reference.md
  docs/src/api_reference.md.in
  docs/src/backup.md
  docs/src/backup_barmanobjectstore.md
  docs/src/backup_volumesnapshot.md
  docs/src/bootstrap.md
  docs/src/cloudnative-pg.v1.md
  docs/src/connection_pooling.md
  docs/src/declarative_role_management.md
  docs/src/postgis.md
  docs/src/quickstart.md
  docs/src/recovery.md
  docs/src/replication.md
  docs/src/resource_management.md
  docs/src/samples.md
  docs/src/scheduling.md
  docs/src/wal_archiving.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2644 Typo fix.
  docs/src/kubectl-plugin.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2647 chore: add documentation and E2E tests for Replica Clusters from VolumeSnapshot
  docs/src/replica_cluster.md
  docs/src/samples.md
  docs/src/samples/backup-with-volume-snapshot.yaml
  docs/src/samples/cluster-example-replica-from-volume-snapshot.yaml
  docs/src/samples/cluster-example-replica-streaming.yaml
  docs/src/samples/cluster-example-with-volume-snapshot.yaml
  tests/e2e/asserts_test.go
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-from-backup.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-from-snapshot.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-src-with-backup.yaml.template
  tests/e2e/metrics_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/volume_snapshot_test.go
  tests/utils/backup.go
  tests/utils/storage.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20
