Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-07, with the labels that each got.

#2398 revert: "tests: compatibility with latest Docker Desktop (#2394)"
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2334 fix: support infinity in Declarative Roles
  docs/src/declarative_role_management.md
  docs/src/samples/cluster-example-with-roles.yaml
  internal/management/controller/roles/contract.go
  internal/management/controller/roles/contract_test.go
  internal/management/controller/roles/postgres.go
  internal/management/controller/roles/postgres_test.go
  internal/management/controller/roles/reconciler_test.go
  internal/management/controller/roles/roles.go
  internal/management/controller/roles/runnable.go
  internal/management/controller/roles/runnable_test.go
  tests/e2e/fixtures/managed_roles/cluster-managed-roles.yaml.template
  tests/e2e/managed_roles_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2393 fix: check for nil value in the pod status
  internal/management/controller/instance_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2404 ci: allow setting a PR label to always push images on new commits
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, always push images

#2043 feat: support for specific priorityClassName in cluster pod
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
  pkg/specs/jobs.go
  pkg/specs/pods.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2412 changed the $cluster-.* regex
  docs/src/samples/monitoring/grafana-configmap.yaml
  docs/src/samples/monitoring/grafana-dashboard.json
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2347 doc: override table data css to wrap long sentences
  docs/mkdocs.yml
  docs/src/css/override.css
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2382 chore: do not add label backport-requested to PRs created by renovate
  .github/workflows/backport.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2418 ci: devcontainer configuration
  .devcontainer/devcontainer.json
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2384 fix: ensure PGDATA permissions after initdb and restore
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, always push images

#2454 fix: update CRD with controller-gen
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2436 chore: add Pooler interface and test coverage to logicalimports
  pkg/management/postgres/logicalimport/database.go
  pkg/management/postgres/logicalimport/database_test.go
  pkg/management/postgres/logicalimport/microservice.go
  pkg/management/postgres/logicalimport/monolith.go
  pkg/management/postgres/logicalimport/role.go
  pkg/management/postgres/logicalimport/role_test.go
  pkg/management/postgres/logicalimport/roleinheritance.go
  pkg/management/postgres/logicalimport/roleinheritance_test.go
  pkg/management/postgres/logicalimport/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2437 test: add unit test coverage to specs/pgbouncer
  api/v1/pooler_types.go
  pkg/specs/pgbouncer/deployments_test.go
  pkg/specs/pgbouncer/podmonitor_test.go
  pkg/specs/pgbouncer/rbac_test.go
  pkg/specs/pgbouncer/services_test.go
  pkg/specs/pgbouncer/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2455 fix: run the CRD check also when there's some changes in operator
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2456 fix: make `umask` call in initdb compatible with Windows plugin
  pkg/fileutils/compatibility/unix.go
  pkg/fileutils/compatibility/windows.go
  pkg/management/postgres/compatibility/doc.go
  pkg/management/postgres/compatibility/unix.go
  pkg/management/postgres/compatibility/windows.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2438 test: add metrics/mapping unit tests
  pkg/management/postgres/metrics/mapping_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2464 Add Tembo to ADOPTERS.md
  ADOPTERS.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2465 fix: fix windows compile issue
  pkg/fileutils/compatibility/windows.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2462 fix: add SA ownerMetadata only during creation
  api/v1/cluster_types.go
  controllers/cluster_create.go
  controllers/cluster_create_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2428 ci: enable cloud provider E2E tests
  .github/aks_versions.json
  .github/e2e-matrix-generator.py
  .github/eks_versions.json
  .github/gke_versions.json
  .github/k8s_versions_scope.json
  .github/vpc_destroy.py
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  hack/e2e/eks-cluster.yaml.template
  hack/e2e/storage-class-gp3.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2375 feat: read cluster pod logs in Go
  cmd/kubectl-cnpg/main.go
  docs/src/kubectl-plugin.md
  go.mod
  internal/cmd/plugin/logs/cluster.go
  internal/cmd/plugin/logs/cluster_logs.go
  internal/cmd/plugin/logs/cluster_logs_test.go
  internal/cmd/plugin/logs/cluster_test.go
  internal/cmd/plugin/logs/cmd.go
  internal/cmd/plugin/logs/cmd_test.go
  internal/cmd/plugin/logs/doc.go
  internal/cmd/plugin/logs/suite_test.go
  internal/cmd/plugin/plugin.go
  pkg/utils/logs/cluster_logs.go
  pkg/utils/logs/cluster_logs_test.go
  pkg/utils/logs/logs.go
  pkg/utils/logs/logs_test.go
  tests/e2e/cluster_setup_test.go
  tests/e2e/suite_test.go
  tests/utils/cluster.go
  tests/utils/environment.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2419 chore: add `LastCheckpointRedoWAL` check during restore process
  internal/cmd/manager/walrestore/cmd.go
  pkg/management/barman/commandbuilder.go
  pkg/management/barman/restorer/restorer.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2460 fix: by default recovery should be exclusive
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
  docs/src/bootstrap.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2484 test: E2E cloud env configuration to support volumesnapshot
  .github/workflows/continuous-delivery.yml
  hack/e2e/volumesnapshotclass-ebs-csi.yaml
  hack/e2e/volumesnapshotclass-pd-csi.yaml
  tests/e2e/fixtures/volume_snapshot/cluster_volume_snapshot.yaml.template
  tests/e2e/volume_snapshot_test.go
  tests/utils/backup.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2477 test: improve unit test coverage for slots pkg
  internal/management/controller/slots/infrastructure/postgresmanager_test.go
  internal/management/controller/slots/infrastructure/suite_test.go
  internal/management/controller/slots/reconciler/replicationslot_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#1390 Update troubleshooting.md
  .wordlist-en-custom.txt
  docs/src/troubleshooting.md
Labels: help wanted :sos:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2486 chore: reorganize collectShowPools variables
  pkg/management/pgbouncer/metricsserver/pools.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2492 feat: add `volume-snapshot-suffix` optional argument to snapshot command
  .github/workflows/continuous-delivery.yml
  contribute/e2e_testing_environment/README.md
  internal/cmd/plugin/snapshot/cmd.go
  tests/e2e/volume_snapshot_test.go
  tests/labels.go
  tests/utils/backup.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2503 chore: Improve error output on snapshot command
  internal/cmd/plugin/snapshot/cmd.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2502 doc: release notes 1.20.2, 1.19.4
  .wordlist-en-custom.txt
  docs/src/release_notes/v1.19.md
  docs/src/release_notes/v1.20.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, do not backport

#2521 fix: fix linter failed in ci workflow
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook_test.go
  internal/cmd/plugin/fio/fio.go
  internal/management/controller/slots/reconciler/replicationslot_test.go
  internal/management/controller/slots/runner/runner_test.go
  pkg/management/postgres/logicalimport/roleinheritance_test.go
  pkg/reconciler/persistentvolumeclaim/reconciler_test.go
  tests/utils/azurite.go
  tests/utils/curl.go
  tests/utils/minio.go
  tests/utils/psql_client.go
  tests/utils/replication_slots.go
  tests/utils/webapp.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2523 ci: enforce linter in ci always run as it is a required check
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20
