Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-12, with the labels that each got.

#3441 feat: reflect Postgres errors on Tablespaces in cluster status
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  internal/management/controller/tablespaces/actions.go
  internal/management/controller/tablespaces/controller_test.go
  internal/management/controller/tablespaces/reconciler.go
  internal/management/controller/tablespaces/storage.go
  internal/management/controller/tablespaces/tablespaces.go
Labels: no-issue

#3449 fix: evaluate 'immediate-checkpoint' and 'wait-for-archive' for backup command
  internal/cmd/plugin/backup/cmd.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3343 ci: expose workflow's input properties
  .github/e2e-matrix-generator.py
  .github/e2e_test_timeout.json
  .github/generate-test-artifacts.py
  .github/workflows/backport.yml
  .github/workflows/chatops.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/registry-clean.yml
  .github/workflows/require-labels.yml
  hack/e2e/run-e2e.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3461 feat: show tablespaces in status plugin
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  internal/cmd/plugin/status/status.go
  internal/management/controller/tablespaces/actions.go
  internal/management/controller/tablespaces/controller_test.go
Labels: no-issue

#3075 feat: add PodMonitor relabeling options
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/pooler_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  docs/src/cloudnative-pg.v1.md
  pkg/specs/pgbouncer/podmonitor.go
  pkg/specs/podmonitor.go
  pkg/specs/podmonitor_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3500 Edits to new tablespaces and samples content
  docs/src/samples.md
  docs/src/tablespaces.md
Labels: no-issue, do not backport

#3483 ci: fix workflow failed issue
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  hack/e2e/run-e2e.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3513 chore: add contribution question to GitHub feature issue
  .github/ISSUE_TEMPLATE/feature.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3523 test: fix go-sqlmock v1.5.1 compatibility
  internal/management/controller/roles/postgres_test.go
  pkg/management/postgres/logicalimport/database_test.go
  pkg/management/postgres/probes_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3473 docs: improve troubleshooting document
  docs/src/troubleshooting.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3453 ci: move image scan to cd workflow
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3525 doc: update Go and Kind version in contributing guide
  contribute/development_environment/README.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3446 docs: edits to operator capability levels topic
  docs/src/operator_capability_levels.md
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3517 fix: make pooler instances a pointer
  api/v1/pooler_types.go
  api/v1/zz_generated.deepcopy.go
  controllers/pooler_update_test.go
  controllers/suite_test.go
  pkg/specs/pgbouncer/deployments.go
  pkg/specs/pgbouncer/deployments_test.go
  tests/e2e/fixtures/upgrade/pgbouncer.yaml
  tests/e2e/upgrade_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3536 docs: update apidoc generator configuration
  docs/config.yaml
  docs/src/cloudnative-pg.v1.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3535 feat: allow users to disable ALTER SYSTEM
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/installation_upgrade.md
  docs/src/postgresql_conf.md
  internal/management/controller/instance_controller.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/instance_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3533 feat: reconciler for `externalClusters` entries
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/bootstrap.md
  docs/src/cloudnative-pg.v1.md
  internal/cmd/manager/instance/run/cmd.go
  internal/management/controller/externalservers/doc.go
  internal/management/controller/externalservers/manager.go
  internal/management/controller/externalservers/reconciler.go
  pkg/management/external/doc.go
  pkg/management/external/external.go
  pkg/management/external/internal/pgpass/conninfo.go
  pkg/management/external/internal/pgpass/conninfo_test.go
  pkg/management/external/internal/pgpass/doc.go
  pkg/management/external/internal/pgpass/pgpass.go
  pkg/management/external/internal/pgpass/pgpass_test.go
  pkg/management/external/internal/pgpass/suite_test.go
  pkg/management/external/utils.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3499 docs: copy edits to recovery topic
  docs/src/recovery.md
Labels: documentation :book:

#3545 feat: disable ALTER SYSTEM by default
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/installation_upgrade.md
Labels: ok to merge :ok_hand:, do not backport

#3567 docs: add k9s plugin (#3566)
  docs/src/kubectl-plugin.md
  docs/src/samples/k9s/plugin.yml
Labels: backport-requested :arrow_backward:, release-1.20, release-1.21

#3558 test: make docker server credentials available in e2e test cases
  .wordlist-en-custom.txt
  hack/e2e/run-e2e.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3573 fix: use the correct version of Go when building OLM catalog
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3561 ci: use latest go in 'olm-bundle' job of ci workflow
  .github/workflows/continuous-integration.yml
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3456 Verify candidate has active wal_receiver before targeting as primary
  controllers/replicas.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3580 chore(deps): update upload-artifact and download-artifact actions to v4
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
Labels: backport-requested :arrow_backward:, release-1.21

#3583 fix(e2e): avoid uploading multiple artifacts with same name
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3590 revert: "fix: adding shutdown delay to controller manager (#3354)"
  internal/cmd/manager/instance/run/cmd.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3472 test: add unit test for the online snapshot `prepare` method
  pkg/management/postgres/webserver/backup_client.go
  pkg/reconciler/backup/volumesnapshot/online.go
  pkg/reconciler/backup/volumesnapshot/online_test.go
  pkg/reconciler/backup/volumesnapshot/reconciler.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21

#3589 fix(doc): indentation of example in `recovery.md`
  docs/src/recovery.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3593 fix(ci): do not consider alpha version of KinD
  .github/renovate.json5
  .github/workflows/public-cloud-k8s-versions-check.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3546 fix(plugin): add cluster label to backups
  internal/cmd/plugin/backup/cmd.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3539 fix: Properly set ubi8 tag during the release process
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
  Dockerfile-ubi8
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21

#3570 fix: avoid considering old snapshots when creating a replica
  pkg/reconciler/persistentvolumeclaim/storagesource.go
  pkg/reconciler/persistentvolumeclaim/storagesource_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3477 feat: add gauges for the tablespace volumes in grafana
  docs/src/samples/monitoring/grafana-configmap.yaml
  docs/src/samples/monitoring/grafana-dashboard.json
Labels: ok to merge :ok_hand:, no-issue, do not backport

#3614 ci: fix olm bundle pull secrets name in makefile
  Makefile
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21

#3586 fix: set wal_sender_timeout to 5min when joining through pg_basebackup
  pkg/management/postgres/join.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3447 Fix example Grafana dashboard's "Last archived WAL" panel
  docs/src/samples/monitoring/grafana-configmap.yaml
  docs/src/samples/monitoring/grafana-dashboard.json
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, ready to test :elephant:, release-1.20, release-1.21

#3565 feat: watch secrets used by external clusters
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_status.go
  docs/src/cloudnative-pg.v1.md
  internal/management/controller/externalservers/manager.go
  pkg/management/external/internal/pgpass/pgpass_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3621 chore: remove useless code inside snapshot `finalize`
  pkg/reconciler/backup/volumesnapshot/online.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21

#3616 chore: remove direct error type assertions
  internal/management/controller/roles/postgres_errors.go
  internal/management/controller/roles/runnable.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3556 docs: Release notes for 1.22.0, 1.21.2, and 1.20.5
  .wordlist-en-custom.txt
  docs/src/index.md
  docs/src/installation_upgrade.md
  docs/src/operator_capability_levels.md
  docs/src/release_notes.md
  docs/src/release_notes/v1.20.md
  docs/src/release_notes/v1.21.md
  docs/src/release_notes/v1.22.md
  docs/src/supported_releases.md
  docs/src/tablespaces.md
Labels: ok to merge :ok_hand:, no-issue, do not backport

#3628 fix: release publish by setting up Go lang environment
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21

#3631 chore: add 1.22 to the workflows
  .github/ISSUE_TEMPLATE/bug.yml
  .github/renovate.json5
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  contribute/release_procedure.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3635 fix(docs): operator manifest link
  docs/src/installation_upgrade.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22

#3637 fix(doc): operator snapshot manifest link
  docs/src/installation_upgrade.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22

#3636 fix: release script must update the release branch in docs
  hack/release.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3643 Fix license header in some go files
  internal/management/controller/tablespaces/manager.go
  pkg/reconciler/persistentvolumeclaim/calculator.go
  pkg/system/system_test.go
  tests/utils/hibernate.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22
