Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-10, with the labels that each got.

#2851 chore: change webhook name from kb.io to cnpg.io
  api/v1/backup_webhook.go
  api/v1/cluster_webhook.go
  api/v1/pooler_webhook.go
  api/v1/scheduledbackup_webhook.go
  config/webhook/manifests.yaml
  internal/cmd/plugin/report/operator_utils.go
  tests/e2e/upgrade_test.go
  tests/e2e/webhook_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2971 Fix typo
  api/v1/pooler_types.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2956 fix(rbac): not adding `resourceNames` for `s3Credentials` `region` & `sessionToken`
  pkg/specs/roles.go
  pkg/specs/roles_test.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2975 fix: panic in serviceReconciler
  controllers/cluster_create.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2978 chore: make some order on the webhook list for the cnpg report command
  internal/cmd/plugin/report/operator_utils.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2915 feat: add `cnpg.io/instanceRole` label
  controllers/cluster_controller.go
  controllers/cluster_restore.go
  internal/cmd/plugin/psql/psql.go
  pkg/reconciler/instance/metadata.go
  pkg/reconciler/instance/metadata_test.go
  pkg/reconciler/persistentvolumeclaim/metadata.go
  pkg/reconciler/persistentvolumeclaim/reconciler_test.go
  pkg/specs/pg_pods.go
  pkg/specs/pods.go
  pkg/specs/services.go
  pkg/utils/labels_annotations.go
  tests/e2e/asserts_test.go
  tests/utils/cluster.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2982 fix: broken upgrade e2e
  pkg/postgres/testdata/lsn_overflow.json
  tests/e2e/logs_test.go
  tests/e2e/upgrade_test.go
  tests/utils/cluster.go
  tests/utils/replication_slots.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2936 feat: defer immediate snapshot backup until cluster is Ready
  controllers/scheduledbackup_controller.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2957 fix: defaults to `app` owner and database during recovery
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  docs/src/recovery.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2979 docs: remove any reference to cnp-bench
  docs/src/storage.md
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2869 feat: added default alert case for failing replication
  docs/src/samples/monitoring/alerts.yaml
  docs/src/samples/monitoring/prometheusrule.yaml
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2984 chore: add `cnpg.io/backupDate` to volume snapshots
  docs/src/labels_annotations.md
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  pkg/utils/labels_annotations.go
Labels: do not backport

#2981 fix: added name check to backup command
  internal/cmd/plugin/backup/cmd.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2993 fix: cnpg backup error message
  internal/cmd/plugin/backup/cmd.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2991 fix: metrics test should work with/without slots enabled
  tests/e2e/metrics_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2953 feat: add primary timestamp and uptime to cnpg status
  internal/cmd/plugin/status/status.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2996 fix(plugin): `status` to display `Fenced` status in `Replication role`
  internal/cmd/plugin/status/status.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#3001 fix(grafana): manage unavailable backups situations
  docs/src/samples/monitoring/grafana-configmap.yaml
  docs/src/samples/monitoring/grafana-dashboard.json
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:, release-1.19, release-1.20

#3004 docs: PostgreSQL parameters to be strings
  docs/src/postgresql_conf.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#3007 feat: add backup method in the printed columns
  api/v1/backup_types.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
Labels: do not backport

#2593 fix(docs): Cron schedule expression in ScheduledBackup
  docs/src/backup.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#3010 docs: add Enix in ADOPTERS.md
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2987 chore: use a map in the backup status of volume snapshots
  .wordlist-en-custom.txt
  api/v1/backup_types.go
  api/v1/backup_types_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  controllers/backup_controller.go
  docs/src/cloudnative-pg.v1.md
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/volume_snapshot_test.go
Labels: do not backport

#2926 chore: add default seccompProfile to operator
  config/manager/manager.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2734 feat: add OLM support
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
  .gitignore
  .wokeignore
  Dockerfile
  Makefile
  config/olm-default/kustomization.yaml
  config/olm-default/olm_changes.yaml
  config/olm-default/webhook_mutating_port_patch.yaml
  config/olm-default/webhook_validating_port_patch.yaml
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
  config/olm-manifests/kustomization.yaml
  config/olm-samples/kustomization.yaml
  config/olm-samples/postgresql_v1_backup.yaml
  config/olm-samples/postgresql_v1_cluster.yaml
  config/olm-samples/postgresql_v1_pooler.yaml
  config/olm-samples/postgresql_v1_scheduledbackup.yaml
  config/olm-scorecard/bases/config.yaml
  config/olm-scorecard/kustomization.yaml
  config/olm-scorecard/patches/basic.config.yaml
  config/olm-scorecard/patches/olm.config.yaml
  docs/src/index.md
  docs/src/installation_upgrade.md
  docs/src/operator_capability_levels.md
Labels: ok to merge :ok_hand:, always push images

#3012 doc: add operator-sdk in the development environment requirements
  contribute/development_environment/README.md
Labels: do not backport

#2977 fix: cold snapshot backup on primary leaves cluster stuck
  controllers/backup_controller.go
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  tests/e2e/fixtures/volume_snapshot/declarative-backup-on-primary.yaml.template
  tests/e2e/volume_snapshot_test.go
Labels: ok to merge :ok_hand:, do not backport

#2905 feat: disable `postgres` super user access by default
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/security.md
Labels: ok to merge :ok_hand:, do not backport

#2830 feat: add ephemeral-storage limit for emptyDir's
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/cluster_conf.md
  docs/src/postgresql_conf.md
  pkg/specs/volumes.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#3019 fix: typo
  pkg/management/postgres/instance.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2594 docs: S3 lifecycle policies
  docs/src/appendixes/object_stores.md
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2946 feat: include replicas in volume snapshot recovery
  api/v1/backup_types.go
  api/v1/backup_types_test.go
  controllers/cluster_create.go
  docs/src/samples/cluster-restore-snapshot.yaml
  internal/cmd/manager/instance/restoresnapshot/cmd.go
  pkg/management/postgres/restore.go
  pkg/reconciler/persistentvolumeclaim/instance.go
  pkg/reconciler/persistentvolumeclaim/reconciler_test.go
  pkg/reconciler/persistentvolumeclaim/resources.go
  pkg/reconciler/persistentvolumeclaim/storagesource.go
  pkg/reconciler/persistentvolumeclaim/storagesource_test.go
  pkg/specs/jobs.go
  tests/e2e/fixtures/volume_snapshot/cluster-pvc-snapshot-restore.yaml.template
  tests/e2e/fixtures/volume_snapshot/declarative-backup-cluster-restore.yaml.template
  tests/e2e/volume_snapshot_test.go
  tests/utils/job.go
Labels: ok to merge :ok_hand:, do not backport, always push images

#3022 fix: ciclops unable to slack for alerts
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#3039 feat: move shutdown logic to instance management
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/instance_manager.md
  internal/cmd/manager/instance/run/lifecycle/lifecycle.go
  internal/cmd/manager/instance/run/lifecycle/shutdown.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/instance_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2545 Fix PoolerTypeRO comment
  api/v1/pooler_types.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#3030 chore: rename `smartStopDelay` to `smartShutdownTimeout`
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/fencing.md
  docs/src/instance_manager.md
  internal/management/controller/instance_controller.go
  pkg/management/postgres/instance.go
  tests/e2e/fixtures/fastfailover/cluster-fast-failover-with-repl-slots.yaml.template
  tests/e2e/fixtures/fastfailover/cluster-fast-failover.yaml.template
  tests/e2e/fixtures/fastfailover/cluster-syncreplicas-fast-failover.yaml.template
Labels: do not merge :no_good:

#2670 docs: document write amplification issue
  .wordlist-en-custom.txt
  docs/src/storage.md
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#3044 test: accept any replica as new primary in rolling update E2Es
  tests/e2e/rolling_update_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2463 fix: local E2E tests in a pristine environment
  hack/e2e/run-e2e-local.sh
Labels: no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#3045 ci: improve devcontainer environment
  .devcontainer/devcontainer.json
Labels: no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2247 ci: use snapshot mode when no tags exist
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#3048 fix: check for nil map in multi namespaced cache
  pkg/multicache/multinamespaced_cache.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#3052 fix: license header for backup_webhook_test.go file
  api/v1/backup_webhook_test.go
Labels: no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#3002 docs: upgrade instructions to 1.21.0, 1.20.3 and 1.19.5
  .wordlist-en-custom.txt
  docs/src/installation_upgrade.md
  docs/src/instance_manager.md
Labels: do not backport

#3051 feat: use fast shutdown for fencing
  docs/src/fencing.md
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#3059 doc: update the information on volume snapshots
  docs/src/backup.md
  docs/src/backup_volumesnapshot.md
  docs/src/kubectl-plugin.md
  docs/src/recovery.md
  internal/cmd/plugin/snapshot/cmd.go
Labels: ok to merge :ok_hand:, do not backport

#3055 ci: raise goreleaser cnpg plugin build timeout
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#3061 doc: clarify backup type on the operator capability level page
  docs/src/operator_capability_levels.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#3069 docs: add link to recommended architectures article
  README.md
  docs/src/architecture.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#3067 docs: release notes for 1.21.0, 1.20.3 and 1.19.5
  .wordlist-en-custom.txt
  docs/src/release_notes.md
  docs/src/release_notes/v1.19.md
  docs/src/release_notes/v1.20.md
  docs/src/release_notes/v1.21.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, do not backport

#3080 ci: 403 pushing images in continuous-integration workflow
  .github/workflows/continuous-integration.yml
Labels: no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3090 fix installation_upgrade.md link
  docs/src/release_notes/v1.21.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#3095 ci: add release-1.21 support in workflow
  .github/renovate.json5
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#3085 ci: fixing the release of olm
  .github/workflows/release-publish.yml
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#3107 fix: `schemaOnly` import doesn't need a default value
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3057 chore: update minimum version of Go required
  go.mod
  go.sum
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3063 chore: encapsulate `InstanceCommand` implementations
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#3065 chore: use `contextLogger` in the instance when possible
  internal/cmd/manager/instance/run/lifecycle/lifecycle.go
  internal/cmd/manager/instance/run/lifecycle/run.go
  internal/management/controller/instance_controller.go
  internal/management/controller/instance_startup.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/instance_test.go
  pkg/management/postgres/promote.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#3083 fix: krew publish process using new location created by GoReleaser
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2812 feat: stop using postgresql.auto.conf to control Postgres
  pkg/configfile/configfile.go
  pkg/configfile/configfile_test.go
  pkg/configfile/utils.go
  pkg/configfile/utils_test.go
  pkg/fileutils/fileutils.go
  pkg/fileutils/fileutils_test.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/constants/constants.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance_replica.go
  pkg/management/postgres/instance_test.go
  pkg/management/postgres/restore.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3133 chore: add bug report issue template
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: no-issue, do not backport

#3138 chore: add feature issue report
  .github/ISSUE_TEMPLATE/feature.yml
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3130 chore: install common golang version in the CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3140 docs: provide a link to the list of CSI drivers
  docs/src/backup.md
  docs/src/storage.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3079 chore: adjust log levels of the instance endpoints
  pkg/management/postgres/webserver/remote.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3127 chore: add a new check `run-govulncheck`
  .github/workflows/continuous-integration.yml
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3150 refactor: encapsulate instance shutdown logic
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3101 feat: enhance the `plugin status` command
  internal/cmd/plugin/status/status.go
  internal/plugin/resources/instance.go
  pkg/management/postgres/probes.go
  pkg/management/postgres/probes_test.go
  pkg/management/url/url.go
  pkg/postgres/status.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3155 fix: make ErrNoConnectionEstablished public
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3157 docs: GetClusterPrimary deprecation
  tests/utils/cluster.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3152 feat: use extended query protocol for PostgreSQL
  internal/pgbouncer/management/controller/instance.go
  pkg/management/pgbouncer/metricsserver/pgbouncer_collector.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/join.go
  pkg/management/postgres/pool/connection.go
  pkg/management/postgres/pool/pool.go
  pkg/management/postgres/pool/pool_test.go
  pkg/management/postgres/pool/profiles.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3156 perf: avoid allocations with `(*regexp.Regexp).MatchString`
  pkg/management/postgres/webserver/metricserver/pg_collector.go
  pkg/utils/conditions.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3151 fix: avoid cluttering `VolumeSnapshots` with labels
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  pkg/reconciler/backup/volumesnapshot/reconciler_test.go
  tests/utils/storage.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3143 fix: ensure to use local synchronous_commit in managed role
  internal/cmd/manager/instance/run/lifecycle/run.go
  internal/management/controller/instance_controller.go
  pkg/management/postgres/pool/profiles.go
  pkg/management/postgres/utils/roles.go
  pkg/management/postgres/utils/roles_test.go
Labels: do not merge :no_good:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3117 chore: enable automatic release process to OperatorHub.io
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3160 fix: move the install path of opm and operator-sdk to localbin
  Makefile
Labels: backport-requested :arrow_backward:, release-1.21

#3167 fix: typo in operator-sdk path
  Makefile
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21

#3174 feat: allow max_preparement_statements pgbouncer setting
  api/v1/pooler_webhook.go
  docs/src/connection_pooling.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3176 chore: improve logging when a failover is happening
  controllers/cluster_controller.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3162 fix: check if currentPrimaryTimestamp is empty
  internal/cmd/plugin/status/doc.go
  internal/cmd/plugin/status/status.go
  internal/cmd/plugin/status/status_test.go
  internal/cmd/plugin/status/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3102 feat: PostgreSQL online/hot backup with volume snapshots
  .wordlist-en-custom.txt
  api/v1/backup_types.go
  api/v1/backup_webhook.go
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/backup_controller.go
  controllers/backup_controller_test.go
  controllers/cluster_create.go
  docs/src/backup.md
  docs/src/backup_volumesnapshot.md
  docs/src/cloudnative-pg.v1.md
  docs/src/operator_capability_levels.md
  docs/src/recovery.md
  internal/cmd/manager/instance/restoresnapshot/cmd.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/constants/constants.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/webserver/backup_client.go
  pkg/management/postgres/webserver/backup_connection.go
  pkg/management/postgres/webserver/remote.go
  pkg/management/postgres/webserver/webserver.go
  pkg/management/url/url.go
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  pkg/reconciler/backup/volumesnapshot/reconciler_test.go
  pkg/reconciler/backup/volumesnapshot/resources.go
  pkg/specs/jobs.go
  pkg/utils/labels_annotations.go
  tests/e2e/fixtures/volume_snapshot/cluster-pvc-hot-restore.yaml.template
  tests/e2e/fixtures/volume_snapshot/cluster-pvc-hot-snapshot.yaml.template
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/volume_snapshot_test.go
  tests/utils/backup.go
  tests/utils/storage.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21

#3183 ci: avoid pushing container images if we are running from an external PR
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3204 chore: add documentation issue template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3208 feat: add `online` and `onlineConfiguration` to backup
  api/v1/backup_types.go
  api/v1/backup_types_test.go
  api/v1/backup_webhook.go
  api/v1/backup_webhook_test.go
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  docs/src/backup_volumesnapshot.md
  docs/src/cloudnative-pg.v1.md
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  tests/e2e/volume_snapshot_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3226 feat: add `online` and `onlineConfiguration` to ScheduledBackup
  api/v1/scheduledbackup_types.go
  api/v1/scheduledbackup_types_test.go
  api/v1/scheduledbackup_webhook.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  docs/src/backup_volumesnapshot.md
  docs/src/cloudnative-pg.v1.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3210 fix: reduce fencing window for snapshot backups
  api/v1/backup_types.go
  controllers/backup_controller.go
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  pkg/reconciler/backup/volumesnapshot/reconciler_test.go
  pkg/reconciler/backup/volumesnapshot/resources.go
  pkg/reconciler/backup/volumesnapshot/resources_test.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3227 fix: defer WAL archiving until the switchover have been completed
  internal/cmd/manager/walarchive/cmd.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3175 fix: Keep the psql-client pod running
  tests/utils/psql_client.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3209 fix: accept provided replication client secret
  controllers/cluster_pki.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3232 docs: fix major Postgres version in FAQ
  docs/src/faq.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3225 feat(plugin): command options for volume snapshots hot/cold backups
  docs/src/kubectl-plugin.md
  internal/cmd/plugin/backup/cmd.go
  internal/cmd/plugin/backup/doc.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3239 fix: Migrate recovery_target_timeline to prevent restarting
  pkg/management/postgres/configuration.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3205 chore: add OpenShift annotations to the bundle metadata
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3238 feat: volume snapshot validation
  api/v1/cluster_webhook.go
  controllers/cluster_controller.go
  controllers/cluster_create.go
  docs/src/security.md
  pkg/reconciler/persistentvolumeclaim/validation.go
  pkg/reconciler/persistentvolumeclaim/validation_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3248 test: adjust the `cluster_webhook` tests to the new validator
  api/v1/cluster_webhook_test.go
Labels: no-issue, backport-requested :arrow_backward:, release-1.21

#3250 chore(deps): update kubernetes-csi components
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3246 chores: add document for arm64 architecure in development guide
  contribute/e2e_testing_environment/README.md
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3251 fix: defer WAL archiving during a recovery job
  pkg/management/postgres/restore.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21
