Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-04, with the labels that each got.

#1841 chore: remove postgres 10 from test metrics
  .github/pg_versions.json
  .github/postgres-versions-update.py
Labels: ok to merge :ok_hand:, do not backport

#1842 docs: remove postgres 10 support from document
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1827 feat: add SeccompProfile customization
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
  pkg/specs/containers.go
  pkg/specs/containers_test.go
  pkg/specs/jobs.go
  pkg/specs/pgbouncer/deployments.go
  pkg/specs/pods.go
  pkg/specs/pods_test.go
  pkg/utils/discovery.go
  pkg/utils/discovery_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1815 chore: show unrealizable role configurations
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
  docs/src/declarative_role_management.md
  internal/management/controller/roles/contract.go
  internal/management/controller/roles/postgres.go
  internal/management/controller/roles/postgres_errors.go
  internal/management/controller/roles/postgres_test.go
  internal/management/controller/roles/reconciler.go
  internal/management/controller/roles/reconciler_test.go
  internal/management/controller/roles/roles.go
  internal/management/controller/roles/runnable.go
  internal/management/controller/roles/runnable_test.go
  tests/e2e/fixtures/managed_roles/cluster-managed-roles.yaml.template
  tests/e2e/managed_roles_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1860 chore: bump plugin ExecCommand request timeouts
  internal/cmd/plugin/hibernate/on.go
  internal/cmd/plugin/status/status.go
  internal/plugin/resources/instance.go
Labels: backport-requested :arrow_backward:, release-1.18, release-1.19

#1883 chore: disable logLevel trace on E2E tests using replication slots
  tests/e2e/fixtures/base/cluster-storage-class-with-rep-slots.yaml.template
  tests/e2e/fixtures/fastfailover/cluster-fast-failover-with-repl-slots.yaml.template
  tests/e2e/fixtures/fastswitchover/cluster-fast-switchover-with-repl-slots.yaml.template
  tests/e2e/fixtures/replication_slot/cluster-pg-replication-slot-disable.yaml.template
  tests/e2e/fixtures/switchover/cluster-switchover-with-rep-slots.yaml.template
  tests/utils/import_db.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19

#1861 chore: reconciling for validUntil option changed
  api/v1/cluster_types.go
  internal/management/controller/roles/contract.go
  internal/management/controller/roles/contract_test.go
  internal/management/controller/roles/postgres.go
  internal/management/controller/roles/postgres_test.go
  tests/e2e/managed_roles_test.go
Labels: ok to merge :ok_hand:, do not backport

#1891 fix: make managedRolesStatus optional in the status section
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
  internal/management/controller/roles/postgres.go
  internal/management/controller/roles/postgres_test.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#1904 test: always run E2Es in unique namespaces
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fixtures/upgrade/cluster-restore.yaml.template
  tests/e2e/fixtures/upgrade/cluster1.yaml.template
  tests/e2e/fixtures/upgrade/cluster2.yaml.template
  tests/e2e/scaling_test.go
  tests/e2e/switchover_test.go
  tests/e2e/update_user_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1858 fix: apply the full configuration during the init job
  internal/management/controller/instance_controller.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1954 ci: test K8s 1.27
  .github/k8s_versions_scope.json
  .github/kind_versions.json
Labels: ok to merge :ok_hand:, do not backport

#1958 chore: important changes to default values
  api/v1/backup_types.go
  api/v1/cluster_types.go
  api/v1/scheduledbackup_types.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  docs/src/api_reference.md
  docs/src/backup_recovery.md
  docs/src/installation_upgrade.md
  docs/src/replication.md
  docs/src/rolling_update.md
  tests/e2e/fixtures/backup/azure_blob/cluster-with-backup-azure-blob.yaml.template
  tests/e2e/fixtures/backup/azurite/cluster-backup.yaml.template
  tests/e2e/fixtures/backup/backup_restore_safety/cluster-with-backup-minio.yaml.template
  tests/e2e/fixtures/backup/backup_restore_safety/external-clusters-minio-2.yaml.template
  tests/e2e/fixtures/backup/backup_restore_safety/external-clusters-minio-3.yaml.template
  tests/e2e/fixtures/backup/backup_restore_safety/external-clusters-minio-4.yaml.template
  tests/e2e/fixtures/backup/backup_restore_safety/external-clusters-minio.yaml.template
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-custom-servername.yaml.template
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-legacy.yaml.template
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-with-wal-max-parallel.yaml.template
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio.yaml.template
  tests/e2e/fixtures/backup/recovery_external_clusters/cluster-with-backup-azure-blob-sas.yaml.template
  tests/e2e/fixtures/backup/recovery_external_clusters/source-cluster-azure-blob-01.yaml.template
  tests/e2e/fixtures/backup/recovery_external_clusters/source-cluster-minio-01.yaml.template
  tests/e2e/fixtures/base/cluster-storage-class.yaml.template
  tests/e2e/fixtures/rolling_updates/cluster-three-instances.yaml.template
  tests/e2e/fixtures/upgrade/cluster1.yaml.template
  tests/e2e/fixtures/upgrade/cluster2.yaml.template
Labels: ok to merge :ok_hand:, do not backport

#1976 doc: fix eol date for 1.20
  docs/src/supported_releases.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19

#1978 doc: note backup requirement on metric
  docs/src/monitoring.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1974 fix: drop misleading metadata from examples
  docs/src/samples/monitoring/cnpg-prometheusrule.yaml
  docs/src/samples/monitoring/grafana-configmap.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1967 docs: provide sample for operator PodMonitor
  docs/src/samples/monitoring/cnpg-operator-podmonitor.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1977 chore: add 1.20 to backporting, deps and CI/CD
  .github/renovate.json5
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19

#1983 feat: make pgbouncer deployment strategy configurable
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/pooler_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  docs/src/api_reference.md
  docs/src/samples/pooler-deployment-strategy.yaml
  pkg/specs/pgbouncer/deployments.go
  tests/e2e/asserts_test.go
  tests/e2e/fixtures/pgbouncer/pgbouncer-pooler-basic-auth-ro.yaml
  tests/e2e/pgbouncer_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#1987 fix: ensure fencing is not present during cluster restore process
  controllers/cluster_restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20
