Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-09, with the labels that each got.

#2656 fix(docs): broken links
  docs/src/backup_volumesnapshot.md
  docs/src/wal_archiving.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2642 fix: remove azure 'retentionPolicy' as it is deprecated
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2666 test: pitr restore failed with invalid timestamp
  tests/utils/time.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2657 chore: add `ClusterManifestAnnotationName` and `PgControldataAnnotationName`to hibernate cmd
  controllers/cluster_restore.go
  internal/cmd/plugin/hibernate/off.go
  internal/cmd/plugin/hibernate/on.go
  tests/e2e/hibernation_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2680 chore: avoid using the cnpg prefix if redundant
  docs/src/monitoring.md
  docs/src/quickstart.md
  docs/src/samples/monitoring/podmonitor.yaml
  docs/src/samples/monitoring/prometheusrule.yaml
  tests/e2e/certificates_test.go
  tests/e2e/declarative_hibernation_test.go
  tests/e2e/fixtures/certificates/cluster-ssl-enabled.yaml.template
  tests/e2e/fixtures/certificates/cluster-user-supplied-certificates.yaml.template
  tests/e2e/fixtures/certificates/cluster-user-supplied-client-certificates.yaml.template
  tests/e2e/fixtures/certificates/cluster-user-supplied-client-server-certificates.yaml.template
  tests/e2e/hibernation_test.go
  tests/utils/namespace_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2621 Removed nbsp from code block header
  docs/src/benchmarking.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2663 chore: add webhook validation for the `resources` stanza
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2653 feat: add `label-backup-name` flag to snapshot command
  internal/cmd/plugin/snapshot/cmd.go
  tests/e2e/volume_snapshot_test.go
  tests/utils/backup.go
Labels: ok to merge :ok_hand:

#2691 chore: properly quote the values inside LDAP fields for pg_hba.conf
  pkg/management/postgres/configuration.go
  pkg/management/postgres/configuration_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2706 fix: new version of controller-tools changed some lines
  api/v1/zz_generated.deepcopy.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2690 fix: instances always restarting on operator upgrade
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2686 tests: add a timeout before gathering the targetTime in volumeSnapshot E2Es
  tests/e2e/volume_snapshot_test.go
  tests/utils/time.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2675 chore: ensure the secret for pulling image is created
  hack/e2e/run-e2e.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2723 fix(monitoring): run `pg_replication_slots` metric on primary only
  config/manager/default-monitoring.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2697 Add new adopter
  ADOPTERS.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2702 docs: fix broken links in the monitoring section
  docs/src/monitoring.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2737 fix(docs): how to inspect PgBouncer metrics
  docs/src/connection_pooling.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2628 chore: remove `postgresql` label name
  pkg/specs/pods.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, do not backport

#2744 fix(monitoring): improve accuracy of replica lag
  docs/src/samples/cluster-example-monitoring.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2731 fix: evaluate `IsEmptyWalArchiveCheckEnabled` during restore
  docs/src/recovery.md
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2750 fix(monitoring): improve accuracy of replica lag
  config/manager/default-monitoring.yaml
  docs/src/samples/cluster-example-monitoring.yaml
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2741 docs: add predefined labels and annotations
  docs/src/labels_annotations.md
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, do not backport

#2802 chore: fix slack invitation link
  CONTRIBUTING.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2733 chore: add coredumpFilter annotation
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  docs/src/labels_annotations.md
  docs/src/troubleshooting.md
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/management/controller/instance_controller.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/join.go
  pkg/management/postgres/restore.go
  pkg/system/compatibility/darwin.go
  pkg/system/compatibility/unix.go
  pkg/system/compatibility/windows.go
  pkg/system/suite_test.go
  pkg/system/system.go
  pkg/system/system_test.go
  pkg/utils/labels_annotations.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2816 fix: Skip replication slot reconciliation if fenced
  internal/management/controller/slots/runner/runner.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2822 fix: use alertInstanceLabelFilter instead of alertName
  docs/src/images/grafana-local.png
  docs/src/samples/monitoring/grafana-configmap.yaml
  docs/src/samples/monitoring/grafana-dashboard.json
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:, release-1.19, release-1.20

#2823 chore: skip `architecture` checks on fenced instances
  controllers/cluster_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2804 refactor: Centralized annotations and labels, and updated doc
  api/v1/cluster_types.go
  controllers/cluster_controller.go
  controllers/cluster_create.go
  controllers/cluster_predicates.go
  controllers/cluster_restore.go
  controllers/cluster_status.go
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
  controllers/pooler_predicates_test.go
  controllers/pooler_update.go
  controllers/pooler_update_test.go
  controllers/replicas_test.go
  controllers/scheduledbackup_controller.go
  docs/src/labels_annotations.md
  internal/cmd/plugin/destroy/destroy.go
  internal/cmd/plugin/hibernate/off.go
  internal/cmd/plugin/psql/psql.go
  internal/cmd/plugin/psql/psql_test.go
  internal/cmd/plugin/reload/reload.go
  internal/cmd/plugin/restart/restart.go
  pkg/reconciler/hibernation/reconciler_test.go
  pkg/reconciler/hibernation/status.go
  pkg/reconciler/hibernation/status_test.go
  pkg/reconciler/instance/metadata.go
  pkg/reconciler/instance/metadata_test.go
  pkg/reconciler/persistentvolumeclaim/build.go
  pkg/reconciler/persistentvolumeclaim/create_test.go
  pkg/reconciler/persistentvolumeclaim/metadata.go
  pkg/reconciler/persistentvolumeclaim/reconciler_test.go
  pkg/reconciler/persistentvolumeclaim/status.go
  pkg/reconciler/persistentvolumeclaim/suite_test.go
  pkg/resources/labels_annotations.go
  pkg/specs/pg_pods.go
  pkg/specs/pgbouncer/deployments.go
  pkg/specs/pgbouncer/deployments_test.go
  pkg/specs/pgbouncer/podmonitor.go
  pkg/specs/pgbouncer/podmonitor_test.go
  pkg/specs/pgbouncer/services.go
  pkg/specs/pgbouncer/services_test.go
  pkg/specs/poddisruptionbudget.go
  pkg/specs/pods.go
  pkg/specs/secrets.go
  pkg/specs/serviceaccount.go
  pkg/specs/serviceaccount_test.go
  pkg/specs/services.go
  pkg/specs/services_test.go
  pkg/utils/fencing.go
  pkg/utils/labels_annotations.go
  tests/e2e/asserts_test.go
  tests/e2e/declarative_hibernation_test.go
  tests/e2e/pgbouncer_metrics_test.go
  tests/e2e/pgbouncer_types_test.go
  tests/utils/environment.go
  tests/utils/pod.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2846 feat!: change default value of `switchoverDelay` to `3600`
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/instance_manager.md
Labels: enhancement :magic_wand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2847 feat: support startupProbe in instance pod
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  pkg/specs/pods.go
  pkg/specs/pods_test.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20, always push images

#2855 chore: align apidoc
  docs/src/cloudnative-pg.v1.md
Labels: ok to merge :ok_hand:, no-issue

#2864 Update ADOPTERS.md
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2848 feat: Introduce 'smartStopDelay' for managing PG smart shutdown timeout
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/fencing.md
  docs/src/instance_manager.md
  internal/cmd/manager/instance/run/lifecycle/lifecycle.go
  internal/management/controller/instance_controller.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/instance_test.go
  tests/e2e/asserts_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fixtures/fastfailover/cluster-fast-failover-with-repl-slots.yaml.template
  tests/e2e/fixtures/fastfailover/cluster-fast-failover.yaml.template
  tests/e2e/fixtures/fastfailover/cluster-syncreplicas-fast-failover.yaml.template
  tests/e2e/pg_wal_volume_test.go
  tests/e2e/switchover_test.go
  tests/utils/nodes/drain.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2840 chore: add webhook validation for `shared_buffers`
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2873 fix: fix unit test failed
  api/v1/cluster_webhook_test.go
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2877 chore: update license headers
  internal/cmd/manager/instance/restoresnapshot/doc.go
  internal/cmd/plugin/backup/cmd.go
  internal/cmd/plugin/install/doc.go
  pkg/management/postgres/backup_test.go
  pkg/reconciler/backup/volumesnapshot/resources.go
  pkg/utils/logs/cluster_logs.go
  pkg/utils/logs/logs_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2870 tests: ensure client certificate is always being created
  tests/e2e/certificates_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2858 tests: allow to expect reaching one or multiple Cluster phases
  tests/e2e/asserts_test.go
  tests/e2e/pg_wal_volume_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2875 fix: cleans up the resources lists in the generated Role
  pkg/specs/roles.go
  pkg/specs/roles_test.go
  pkg/stringset/stringset.go
  pkg/stringset/stringset_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2850 chore: always push a new image after merging on main
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2854 feat: avoid fencing instance unnecessarily in volume snapshots
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  pkg/reconciler/backup/volumesnapshot/reconciler_test.go
  pkg/reconciler/backup/volumesnapshot/suite_test.go
Labels: ok to merge :ok_hand:, do not backport

#2894 test: fix volumesnapshot unit test
  pkg/reconciler/backup/volumesnapshot/reconciler_test.go
Labels: ok to merge :ok_hand:, do not backport

#2892 docs: explain `snapshotOwnerReference` field
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/backup_volumesnapshot.md
  docs/src/cloudnative-pg.v1.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2884 fix: avoid write-read concurrency on cached cluster
  internal/management/cache/cache.go
  internal/management/controller/cache.go
  pkg/management/postgres/webserver/local.go
  pkg/management/postgres/webserver/metricserver/pg_collector.go
  pkg/management/postgres/webserver/metricserver/wal.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2895 docs: integrate README and FAQ
  .wordlist-en-custom.txt
  ADOPTERS.md
  README.md
  docs/src/faq.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2888 chore: enforce `standard_conforming_strings` in metric collection
  pkg/management/postgres/metrics/collector.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2630 fix: use correct endpointURL in Linode example (#2629)
  docs/src/appendixes/object_stores.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2885 feat: change naming convention for backup VolumeSnapshots
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  pkg/reconciler/backup/volumesnapshot/reconciler_test.go
Labels: ok to merge :ok_hand:, do not backport

#2911 docs: document how to simulate a failover
  docs/src/failure_modes.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2879 fix: ensure that restore snapshot cmd omits excluded files
  docs/src/samples/cluster-restore-snapshot-full.yaml
  internal/cmd/manager/instance/restoresnapshot/cmd.go
  pkg/fileutils/fileutils.go
  pkg/fileutils/fileutils_test.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, do not backport

#2897 fix: make `pg_replication_slots` default metric run on replicas
  config/manager/default-monitoring.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2913 fix: ensure condition is false until the restart is complete
  controllers/cluster_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2886 feat: standardize backup suffix between plugin backup and scheduledbackup
  controllers/scheduledbackup_controller.go
  internal/cmd/plugin/backup/cmd.go
  pkg/management/postgres/backup.go
  pkg/utils/time.go
  pkg/utils/time_test.go
Labels: risk :boom:, ok to merge :ok_hand:, do not backport

#2918 feat: reconcile cluster services
  controllers/cluster_create.go
  controllers/cluster_create_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, always push images

#2923 chore: add build-plugin to only build the plugin binary
  Makefile
  hack/e2e/run-e2e-local.sh
  hack/e2e/run-e2e.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2927 chore: improve logging of PGDATA cleanup after recovery
  pkg/fileutils/fileutils.go
  pkg/fileutils/fileutils_test.go
  pkg/management/postgres/restore.go
Labels: do not backport

#2932 fix: makes VolumeSnapshot CRD optional
  controllers/backup_controller.go
  internal/cmd/manager/controller/controller.go
  pkg/utils/discovery.go
  pkg/utils/discovery_test.go
Labels: do not backport

#2933 fix: linter
  controllers/backup_controller.go
Labels: do not backport

#2903 feat: enable replications slots for HA by default
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/replication.md
Labels: ok to merge :ok_hand:, do not backport

#2934 chore: forbid `volumeSnapshot` backups when CRDs are missing
  api/v1/backup_webhook.go
  api/v1/backup_webhook_test.go
  api/v1/scheduledbackup_webhook.go
  api/v1/scheduledbackup_webhook_test.go
  controllers/backup_controller.go
  controllers/scheduledbackup_controller.go
  pkg/utils/discovery.go
Labels: ok to merge :ok_hand:, do not backport

#2937 fix: avoid logging the full Pod definition
  controllers/cluster_controller.go
Labels: no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2945 fix: slack invitation link in README
  README.md
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20

#2839 Grafana Dashboard: add WAL pvc usage
  docs/src/samples/monitoring/grafana-configmap.yaml
  docs/src/samples/monitoring/grafana-dashboard.json
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20
