Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-01, with the labels that each got.

#1270 ci: fix the label/unlabel ok-to-merge precondition
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1274 chore: check if there's any dirty change for go mod tidy
  .github/workflows/continuous-integration.yml
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1289 docs: add an example of the DigitalOcean S3-compatible Spaces for the…
  docs/src/backup_recovery.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18

#1291 chore: update controller-tools to version 0.11.0
  Makefile
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18

#1269 feat: support to mount projected volume in cnpg cluster
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_upgrade.go
  docs/mkdocs.yml
  docs/src/api_reference.md
  docs/src/cluster_conf.md
  docs/src/samples.md
  docs/src/samples/cluster-example-projected-volume.yaml
  pkg/postgres/configuration.go
  pkg/specs/volumes.go
Labels: ok to merge :ok_hand:

#1275 chore: add support for environment variables
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
  docs/src/api_reference.md
  docs/src/cluster_conf.md
  go.mod
  go.sum
  pkg/specs/jobs.go
  pkg/specs/pods.go
Labels: ok to merge :ok_hand:

#1288 refactor: add pkg/reconciler/persistentvolumeclaim
  api/v1/cluster_types.go
  controllers/cluster_controller.go
  controllers/cluster_create.go
  controllers/cluster_restore.go
  controllers/cluster_scale.go
  controllers/cluster_scale_test.go
  controllers/cluster_status.go
  controllers/cluster_upgrade.go
  controllers/replicas.go
  controllers/scheduledbackup_controller.go
  controllers/suite_test.go
  internal/cmd/plugin/destroy/destroy.go
  internal/plugin/resources/instance.go
  pkg/reconciler/persistentvolumeclaim/build.go
  pkg/reconciler/persistentvolumeclaim/build_test.go
  pkg/reconciler/persistentvolumeclaim/doc.go
  pkg/reconciler/persistentvolumeclaim/reconciler.go
  pkg/reconciler/persistentvolumeclaim/resources.go
  pkg/reconciler/persistentvolumeclaim/resources_test.go
  pkg/reconciler/persistentvolumeclaim/status.go
  pkg/reconciler/persistentvolumeclaim/suite_test.go
  pkg/resources/labels_annotations.go
  pkg/resources/metadatabuilder.go
  pkg/resources/persistentvolumeclaim.go
  pkg/specs/pvcs.go
  pkg/specs/pvcs_test.go
  tests/e2e/hibernation_test.go
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18

#1242 fix: ensure ExecCommand obeys timeout
  pkg/utils/exec.go
  tests/e2e/asserts_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/failover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fencing_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/syncreplicas_test.go
  tests/e2e/update_user_test.go
  tests/e2e/upgrade_test.go
  tests/utils/environment.go
  tests/utils/postgres.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18

#1312 chore: fixing MoveDirectoryContent to work with subdirectories
  internal/pgbouncer/management/controller/manager.go
  pkg/certs/k8s.go
  pkg/fileutils/fileutils.go
  pkg/fileutils/fileutils_test.go
  pkg/fileutils/suite_test.go
  pkg/management/barman/spool/spool.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/logicalimport/constants.go
  pkg/management/postgres/logpipe/linelogpipe.go
  pkg/management/postgres/logpipe/logpipe.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/restore_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18

#1315 fix: permit walStorage resize when using pvcTemplate
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  pkg/reconciler/persistentvolumeclaim/reconciler.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1310 chore: add two new fields to the plugin install generation process
  internal/cmd/plugin/install/generate.go
Labels: backport-requested :arrow_backward:, release-1.18

#1330 refactor: improve readability of persistentvolumeclaim.EnrichStatus
  pkg/reconciler/persistentvolumeclaim/resources_test.go
  pkg/reconciler/persistentvolumeclaim/status.go
  pkg/reconciler/persistentvolumeclaim/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1066 feat: allowing walStorage to be changed on existing cluster
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  controllers/cluster_upgrade.go
  docs/src/storage.md
  internal/cmd/manager/instance/run/cmd.go
  internal/management/controller/instance_startup.go
  pkg/reconciler/persistentvolumeclaim/status.go
  pkg/specs/jobs.go
  pkg/specs/volumes.go
  tests/e2e/pg_wal_volume_test.go
Labels: ok to merge :ok_hand:, do not squash :warning:, do not backport

#1305 test: e2e for adding wal storage on existing cluster.
  tests/e2e/asserts_test.go
  tests/e2e/fixtures/pg_wal_volume/cluster-with-pg-wal-volume.yaml.template
  tests/e2e/fixtures/pg_wal_volume/cluster-without-pg-wal-volume.yaml.template
  tests/e2e/pg_wal_volume_test.go
  tests/e2e/scaling_test.go
Labels: ok to merge :ok_hand:, do not backport

#1323 fix: fix unlabel-ok-to-merge in workflow not work
  .github/workflows/continuous-delivery.yml
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18

#1337 chore: update controller-tools from 0.11.0 to 0.11.1
  Makefile
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1342 ci: restore a proper workflow-dispatch action tag
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18

#1344 doc: define a PVC group
  docs/src/before_you_start.md
  docs/src/storage.md
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18

#1349 feat: comment streaming_replica user
  internal/cmd/manager/instance/run/lifecycle/run.go
Labels: ok to merge :ok_hand:

#1348 feat: add `backup` command to the `cnpg` plugin
  cmd/kubectl-cnpg/main.go
  docs/src/cnpg-plugin.md
  internal/cmd/plugin/backup/cmd.go
Labels: ok to merge :ok_hand:

#1352 ci: implement workaround for push failures on ghcr
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18

#1355 doc: specify Postgres versions supported by each minor release
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1357 doc: add instructions on installing plugin using packages
  .wordlist-en-custom.txt
  docs/src/cnpg-plugin.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1363 chore: updating Philippe Scorsolini's company
  README.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18

#1211 doc: note about postgresql.conf in `recovery`
  docs/src/backup_recovery.md
  docs/src/bootstrap.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18
