Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-02, with the labels that each got.

#1380 fix: ensure that the pvc roles are always consistent
  pkg/reconciler/persistentvolumeclaim/reconciler.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1364 docs: document webhooks' issues on GKE
  docs/src/installation_upgrade.md
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18

#1201 chore: Bump pgbouncer from 1.17.0 to 1.18.0
  pkg/management/pgbouncer/metricsserver/pools.go
  pkg/specs/pgbouncer/deployments.go
  tests/e2e/pgbouncer_metrics_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1385 fix: ensure that we update environment variables only when needed
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
  pkg/specs/jobs.go
  pkg/specs/pods.go
  pkg/specs/pods_test.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:

#1366 feat: add failoverDelay cluster parameter
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
  controllers/replicas.go
  controllers/suite_test.go
  docs/src/api_reference.md
  docs/src/failover.md
  pkg/utils/discovery.go
  tests/e2e/failover_test.go
  tests/e2e/fixtures/failover/cluster-failover-delay.yaml.template
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1397 test(e2e): change github action which clean the runner disk space
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1394 test: verify storage configured correctly
  api/v1/cluster_webhook_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1378 fix: verify max/min wal size setting with wal storageSize
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1382 feat: enhance cnpg_collector_pg_wal metrics for default exporter
  docs/src/monitoring.md
  pkg/management/postgres/metrics/collector.go
  pkg/management/postgres/webserver/metricserver/pg_collector.go
  pkg/management/postgres/webserver/metricserver/suite_test.go
  pkg/management/postgres/webserver/metricserver/wal.go
  pkg/management/postgres/webserver/metricserver/wal_test.go
  pkg/utils/math.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18

#1409 ci: drop workaround for buildx
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1408 fix: do not run CHECKPOINT as streaming_replica user
  pkg/management/postgres/backup.go
  pkg/management/postgres/wal.go
  pkg/management/postgres/wal_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1434 doc: add Star History Chart
  README.md
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18

#1425 fix: update role labels of unattached PVCs
  pkg/reconciler/persistentvolumeclaim/build_test.go
  pkg/reconciler/persistentvolumeclaim/reconciler.go
  pkg/reconciler/persistentvolumeclaim/reconciler_test.go
  pkg/reconciler/persistentvolumeclaim/resources_test.go
  pkg/reconciler/persistentvolumeclaim/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1432 doc: extend the architecture page covering the Kubernetes layer
  .wordlist-en-custom.txt
  docs/graffle/k8s-architecture-2-az.graffle
  docs/graffle/k8s-architecture-3-az.graffle
  docs/graffle/k8s-architecture-multi.graffle
  docs/graffle/k8s-pg-architecture.graffle
  docs/src/architecture.md
  docs/src/images/k8s-architecture-2-az.png
  docs/src/images/k8s-architecture-3-az.png
  docs/src/images/k8s-architecture-multi.png
  docs/src/images/k8s-pg-architecture.png
  docs/src/replica_cluster.md
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18

#1429 docs: add missing scheme for s3 endpoint example
  docs/src/backup_recovery.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18

#1439 ci: golangci-lint github action reports error
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18

#1413 doc: release notes Feb 2023
  docs/src/release_notes.md
  docs/src/release_notes/v1.17.md
  docs/src/release_notes/v1.18.md
  docs/src/release_notes/v1.19.md
  docs/src/supported_releases.md
Labels: do not backport

#1444 chore: add release 1.19 to backport workflow
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  contribute/release_procedure.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18

#1395 feat: support ipv6 and custom pg_hba for pgbouncer
  api/v1/pooler_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  docs/src/api_reference.md
  pkg/management/pgbouncer/config/config.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1460 ci: optimize the cleanup disk github action
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1473 chore: improve renovate configurations
  .github/renovate.json5
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1484 fix: Added missing branch release-1.19 to the renovate workflow
  .github/renovate.json5
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1485 chore: Deprecate GoReleaser versions older than 1.14.0
  .goreleaser.yml
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1428 feat: add `cnp_collector_last_available_backup_timestamp` and `cnp_collector_last_failed_backup_timestamp` metric
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
  pkg/management/postgres/backup.go
  pkg/management/postgres/backup_test.go
  pkg/management/postgres/webserver/metricserver/pg_collector.go
  pkg/management/postgres/webserver/metricserver/pg_collector_test.go
  pkg/management/postgres/webserver/suite_test.go
  pkg/utils/time.go
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/metrics_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19

#1509 chore: update controller-gen 0.11.1 to 0.11.3
  Makefile
Labels: ok to merge :ok_hand:, no-issue

#1511 chore: change distroless/static image for distroless/static-debian11
  Dockerfile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1442 chore: add support for http json logs
  pkg/management/log/flags.go
  pkg/management/log/log.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1466 refactor: clarify the code to retry backups
  pkg/management/postgres/backup.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1503 feat: enable debug option for initdb job
  pkg/specs/jobs.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1513 chore: add all the operator binary to the operator container
  .goreleaser.yml
  Dockerfile
Labels: ok to merge :ok_hand:

#1529 fix: error message when generating streaming replication certificate
  controllers/cluster_pki.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1530 chore: remove PGK (old instance manager name) from code comments
  internal/management/controller/manager.go
  internal/pgbouncer/management/controller/manager.go
  pkg/management/log/log.go
  pkg/management/logtest/logtest.go
  pkg/management/postgres/initdb.go
  pkg/specs/rolebinding.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1534 Validation webhooks for managed roles
  api/v1/cluster_webhook.go
  docs/src/api_reference.md
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1505 doc: clarify deployment name via Helm
  docs/src/installation_upgrade.md
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1533 fix: backup_controller checks if cluster.spec.backup section is present
  api/v1/backup_types.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  controllers/backup_controller.go
  docs/src/api_reference.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1518 ci: ensure branches missing Gingko report are accounted
  .github/generate-test-artifacts.py
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1536 fix: update the backup status in case of errors
  controllers/backup_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1563 ci: always add backport labels for new created pr
  .github/workflows/backport.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1575 Clustermarket Ltd. added to ADOPTERS.md
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1573 doc: fix resource customization example in the pooler page
  docs/src/connection_pooling.md
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1576 Update ADOPTERS.md
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1570 fix: adding WAL storage to a cluster with a single instance is not working
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1564 fix: ensure backup command updates the resources status in case of errors
  pkg/management/postgres/backup.go
  pkg/management/postgres/backup_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1578 chore: use patch instead of update inside scheduledbackup_controller
  controllers/scheduledbackup_controller.go
Labels: backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1538 Create runner to manage roles on the database
  docs/src/samples/cluster-example-with-roles.yaml
  internal/cmd/manager/instance/run/cmd.go
  internal/management/controller/instance_controller.go
  internal/management/controller/roles/contract.go
  internal/management/controller/roles/doc.go
  internal/management/controller/roles/postgres.go
  internal/management/controller/roles/runnable.go
  pkg/management/postgres/instance.go
Labels: backport-requested :arrow_backward:, do not backport, release-1.17, release-1.18, release-1.19

#1568 ci: fix the upload process of development operator manifests
  .github/workflows/continuous-delivery.yml
  docs/src/installation_upgrade.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1589 ci: fix continuos-delivery missing token
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19

#1588 fix: commit successful backup during the backup maintance step
  pkg/management/postgres/backup.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.17, release-1.18, release-1.19
