Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-06, with the labels that each got.

#2172 doc: fix instructions to install latest snapshot
  docs/src/installation_upgrade.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2153 chore: deprecating ubuntu-20.04 in favor of ubuntu-22.04 for GitHub actions
  .github/workflows/backport.yml
  .github/workflows/chatops.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/kind-k8s-versions-check.yml
  .github/workflows/latest-postgres-version-check.yml
  .github/workflows/release-pr.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-tag.yml
  .github/workflows/require-labels.yml
  .github/workflows/spellcheck.yml
  tests/e2e/asserts_test.go
  tests/e2e/operator_unavailable_test.go
  tests/utils/cluster.go
  tests/utils/operator.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2155 test: read stderr consistently
  tests/e2e/asserts_test.go
  tests/e2e/fastswitchover_test.go
  tests/utils/run.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2182 feat: add initialize and scale flags to pgbench command
  .wordlist-en-custom.txt
  docs/src/benchmarking.md
  docs/src/samples/monitoring/kube-stack-config.yaml
  internal/cmd/plugin/pgbench/cmd_test.go
  internal/cmd/plugin/pgbench/pgbench.go
  internal/cmd/plugin/pgbench/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2127 test: cleanup the backup-restore tests
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/cluster_monolithic_test.go
  tests/utils/backup.go
  tests/utils/commons.go
  tests/utils/import_db.go
  tests/utils/namespace.go
  tests/utils/operator.go
  tests/utils/pod.go
  tests/utils/secrets.go
  tests/utils/upgrade.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2203 doc: fix some_query syntax
  docs/src/monitoring.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2221 chore: avoid executing multiple times `SetupLogger`
  controllers/cluster_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2189 chore: add `clean` target in Makefile
  Makefile
  contribute/development_environment/README.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2193 doc: fix instructions to install latest snapshot
  docs/src/installation_upgrade.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2156 test: create backups with kubectl apply for safety
  tests/utils/backup.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2178 test: reuse core functions to fetch clusters and execute commands
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/cnpg_certificates_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/declarative_hibernation_test.go
  tests/e2e/failover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/hibernation_test.go
  tests/e2e/initdb_test.go
  tests/e2e/logs_test.go
  tests/e2e/managed_roles_test.go
  tests/e2e/metrics_test.go
  tests/e2e/pg_basebackup_test.go
  tests/e2e/pg_data_corruption_test.go
  tests/e2e/pg_wal_volume_test.go
  tests/e2e/rolling_update_test.go
  tests/e2e/syncreplicas_test.go
  tests/e2e/update_user_test.go
  tests/e2e/upgrade_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/utils/backup.go
  tests/utils/cluster.go
  tests/utils/pod.go
  tests/utils/storage.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2216 chore: stop testing on K8S 1.22
  .github/k8s_versions_scope.json
  .github/kind_versions.json
  .github/workflows/kind-k8s-versions-check.yml
  docs/src/e2e.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2205 test: use variable to check the running cloud vendor and cache the value
  .github/workflows/continuous-delivery.yml
  hack/e2e/run-e2e-k3d.sh
  hack/e2e/run-e2e-kind.sh
  tests/e2e/apparmor_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/commons_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/eviction_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/suite_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/utils/cloud_vendor.go
  tests/utils/environment.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2234 feat: add schemaOnly to the import section
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/api_reference.md
  docs/src/samples/cluster-import-schema-only-basicauth.yaml
  pkg/management/postgres/logicalimport/database.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2236 doc: explain static pre-provisioning of volumes
  .wordlist-en-custom.txt
  docs/src/storage.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2145 fix: halt the failover if status extraction has failed
  controllers/cluster_controller.go
  controllers/replicas.go
  pkg/postgres/status.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2233 doc: add content on networking
  .wordlist-en-custom.txt
  docs/mkdocs.yml
  docs/src/networking.md
  docs/src/samples/networkpolicy-example.yaml
  docs/src/security.md
  docs/src/troubleshooting.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2240 chore: add Snyk scanning
  .github/workflows/snyk.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2245 fix: snyk golang action to proper version tag
  .github/workflows/snyk.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2202 feat: add TopologySpreadConstraints
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
  docs/src/api_reference.md
  docs/src/operator_capability_levels.md
  pkg/specs/jobs.go
  pkg/specs/pods.go
Labels: risk :boom:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2242 fix: always reconcile metadata
  controllers/cluster_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.18, release-1.19, release-1.20

#2256 fix: remove E2E test for non-backported feature
  tests/e2e/backup_restore_test.go
Labels: no-issue, do not backport

#2270 chore: deprecate release branch 1.18
  .github/renovate.json5
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2254 chore: added Snyk exclude rules
  .snyk
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#1751 fix(alerts): refine LastFailedArchiveTime to not trigger if a new backup has been successful in the meantime
  docs/src/samples/monitoring/alerts.yaml
  docs/src/samples/monitoring/cnpg-prometheusrule.yaml
Labels: backport-requested :arrow_backward:, release-1.18, release-1.19

#2227 chore: encapsulate configurationReload and refreshReplicaConfiguration logic
  internal/management/controller/instance_controller.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/instance_replica.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2269 chore: remove the deprecated cloud detected code
  tests/e2e/backup_restore_test.go
  tests/e2e/eviction_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/utils/cloud_vendor.go
  tests/utils/environment.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2336 fix: restrict read service to instance pods only
  pkg/specs/services.go
  pkg/specs/services_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2201 chore: add ginkgolinter to the golangci-lint linters list
  .golangci.yml
  api/v1/cluster_configuration_test.go
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook_test.go
  api/v1/scheduledbackup_webhook_test.go
  controllers/cluster_controller_test.go
  controllers/cluster_status_test.go
  controllers/pooler_controller_test.go
  controllers/pooler_resources_test.go
  controllers/pooler_status_test.go
  controllers/pooler_update_test.go
  controllers/suite_test.go
  internal/cmd/manager/pgbouncer/run/log_test.go
  internal/cmd/plugin/psql/psql_test.go
  internal/configuration/configuration_test.go
  internal/management/controller/roles/postgres_test.go
  internal/management/controller/slots/runner/runner_test.go
  pkg/certs/certs_test.go
  pkg/certs/k8s_test.go
  pkg/certs/operator_deployment_test.go
  pkg/executablehash/executablehash_test.go
  pkg/fileutils/fileutils_test.go
  pkg/fileutils/suite_test.go
  pkg/management/barman/spool/spool_test.go
  pkg/management/catalog/catalog_test.go
  pkg/management/execlog/writer_test.go
  pkg/management/pgbouncer/config/secrets_test.go
  pkg/management/postgres/logpipe/logpipe_test.go
  pkg/management/postgres/metrics/collector_test.go
  pkg/management/postgres/metrics/parser_test.go
  pkg/management/postgres/pidfile_test.go
  pkg/management/postgres/pool/pool_test.go
  pkg/management/postgres/probes_test.go
  pkg/management/postgres/restore_test.go
  pkg/management/postgres/utils/version_test.go
  pkg/management/postgres/wal_test.go
  pkg/postgres/configuration_test.go
  pkg/postgres/lsn_test.go
  pkg/postgres/version_test.go
  pkg/reconciler/persistentvolumeclaim/reconciler_test.go
  pkg/specs/roles_test.go
  pkg/specs/serviceaccount_test.go
  pkg/utils/barman_test.go
  pkg/utils/time_test.go
  tests/e2e/asserts_test.go
  tests/e2e/logs_test.go
  tests/e2e/managed_roles_test.go
  tests/e2e/nodeselector_test.go
  tests/e2e/tolerations_test.go
  tests/e2e/update_user_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/utils/release_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2278 chore: set Kubernetes 1.27 as default in docs and E2E tests
  docs/k8s-api-docgen.yaml
  docs/src/api_reference.md
  hack/e2e/run-e2e-k3d.sh
  hack/e2e/run-e2e-kind.sh
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2344 doc: add a few more entries in FAQs
  docs/src/faq.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2324 doc: update release procedure
  contribute/release_procedure.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2352 doc: minor fix in `pg_failover_slots` documentation
  docs/src/postgresql_conf.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2330 docs: rename doc file cnpg-plugin to kubectl-plugin
  docs/mkdocs.yml
  docs/src/connection_pooling.md
  docs/src/declarative_hibernation.md
  docs/src/installation_upgrade.md
  docs/src/kubectl-plugin.md
  docs/src/operator_capability_levels.md
  docs/src/rolling_update.md
  docs/src/ssl_connections.md
  docs/src/troubleshooting.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2307 refactor: reorganize instance metadata patch procedure
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
  controllers/replicas.go
  pkg/reconciler/instance/doc.go
  pkg/reconciler/instance/metadata.go
  pkg/reconciler/instance/metadata_test.go
  pkg/reconciler/instance/suite_test.go
Labels: risk :boom:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2257 feat: add `NodesUsed` metric and status field
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_status.go
  docs/src/api_reference.md
  docs/src/monitoring.md
  pkg/management/postgres/webserver/metricserver/pg_collector.go
  pkg/management/postgres/webserver/metricserver/pg_collector_test.go
  tests/e2e/asserts_test.go
  tests/e2e/metrics_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2300 chore: Implement internal log constructor to handle SetLogger error
  pkg/management/log/flags.go
  tests/utils/environment.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2368 chore: do not add label `backport-requested` to `do not backport` PRs
  .github/workflows/backport.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20

#2363 chore: introduce Pooler interface for improved unit testing
  internal/management/controller/slots/infrastructure/postgresmanager.go
  internal/pgbouncer/management/controller/instance.go
  internal/pgbouncer/management/controller/instance_test.go
  internal/pgbouncer/management/controller/refresh.go
  internal/pgbouncer/management/controller/refresh_test.go
  internal/pgbouncer/management/controller/secrets_test.go
  internal/pgbouncer/management/controller/suite_test.go
  pkg/management/postgres/pool/pool.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20

#2394 fix: allow setup-cluster.sh to work with containerd
  hack/setup-cluster.sh
  tests/utils/version_test.go
Labels: no-issue
