Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2023-11, with the labels that each got.

#3260 fix: always close backup connection
  pkg/management/postgres/webserver/backup_connection.go
Labels: backport-requested :arrow_backward:, release-1.21

#3263 chore: clarify error messages in VolumeSnapshots E2e tests
  pkg/management/postgres/webserver/remote.go
  tests/e2e/volume_snapshot_test.go
Labels: backport-requested :arrow_backward:, release-1.21

#3214 feat: support recovering from a volume snapshot backup object
  api/v1/backup_types.go
  api/v1/backup_types_test.go
  api/v1/cluster_webhook_test.go
  api/v1/common_types.go
  controllers/cluster_create.go
  docs/src/recovery.md
  pkg/reconciler/persistentvolumeclaim/storagesource.go
  pkg/reconciler/persistentvolumeclaim/storagesource_test.go
Labels: backport-requested :arrow_backward:, release-1.21

#3261 docs: review commercial support and connection pooling
  .wordlist-en-custom.txt
  docs/src/commercial_support.md
  docs/src/connection_pooling.md
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3267 fix: retry when external-snapshotter controller failed on a conflict
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  pkg/reconciler/backup/volumesnapshot/resources.go
  pkg/reconciler/backup/volumesnapshot/resources_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3276 chore: allow one more connection to PostgreSQL from the instance manager
  pkg/management/postgres/pool/pool.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3274 fix: skip podSpec rollout checker if pod annotation is invalid
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3258 docs: review certificates and instance pod configuration
  .wordlist-en-custom.txt
  docs/src/certificates.md
  docs/src/cluster_conf.md
Labels: backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3278 docs: clarify limitation of replica cloning with scale up
  docs/src/recovery.md
Labels: no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3241 chore: document usage of hashed passwords
  docs/src/declarative_role_management.md
  tests/e2e/fixtures/managed_roles/cluster-managed-roles.yaml.template
  tests/e2e/managed_roles_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3249 docs: release notes for 1.21.1, 1.20.4, and 1.19.6 (EOL)
  docs/src/release_notes.md
  docs/src/release_notes/old/v1.19.md
  docs/src/release_notes/v1.20.md
  docs/src/release_notes/v1.21.md
  docs/src/supported_releases.md
Labels: backport-requested :arrow_backward:, release-1.21

#3283 ci: do not update the install latest code link
  hack/release.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3294 chore: deprecate release branch 1.19
  .github/renovate.json5
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3334 docs: typo fix
  contribute/e2e_testing_environment/README.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3300 chore: scan operator image using Dockle and Snyk
  .github/workflows/continuous-integration.yml
  .wokeignore
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3321 fix: correctly evaluate the request and response for the backup mode
  controllers/backup_controller.go
  pkg/management/postgres/webserver/backup_client.go
  pkg/management/postgres/webserver/backup_connection.go
  pkg/management/postgres/webserver/remote.go
  pkg/management/postgres/webserver/webserver.go
  pkg/reconciler/backup/volumesnapshot/offline.go
  pkg/reconciler/backup/volumesnapshot/online.go
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  pkg/reconciler/backup/volumesnapshot/reconciler_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21

#3316 fix: reconcile the metadata of the managed credentials secret
  controllers/cluster_create.go
  controllers/cluster_create_test.go
  pkg/resources/patchtype.go
  pkg/resources/request.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3351 fix: ensure we always use the latest go compiler in CI
  .github/workflows/backport.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3310 chore: add `RoleManager` section to `cnpg status`
  docs/src/declarative_role_management.md
  internal/cmd/plugin/status/status.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3360 ci: require read and security-events permissions for upload-sarif
  .github/workflows/continuous-integration.yml
Labels: backport-requested :arrow_backward:, release-1.20, release-1.21

#3364 docs: fix x-mark inaccessibility
  docs/src/backup.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3306 feat: add UBI image for OLM bundle
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
  Dockerfile-ubi
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3356 Add Shinkansen in ADOPTERS.md
  ADOPTERS.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3375 chore: start running unit test in 1.28
  .github/k8s_versions_scope.json
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3312 fix: reconcile `pdb` metadata
  controllers/cluster_create.go
  controllers/cluster_create_test.go
  pkg/specs/poddisruptionbudget.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.19, release-1.20, release-1.21

#3349 fix: reconcile `Pooler` service and add labels.
  controllers/pooler_resources_test.go
  controllers/pooler_update.go
  controllers/pooler_update_test.go
  pkg/specs/pgbouncer/services.go
  pkg/specs/pgbouncer/services_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3350 fix: add proper labels to the `Pooler` deployment
  pkg/specs/pgbouncer/deployments.go
  pkg/specs/pgbouncer/deployments_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3357 feat: add PVC yamls to cluster report from plugin
  internal/cmd/plugin/report/cluster_report.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3389 fix: reconcile `Pooler` `imagePullSecret`
  controllers/pooler_update.go
  controllers/pooler_update_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3392 Edits to labels and annotations and logging content
  docs/src/labels_annotations.md
  docs/src/logging.md
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3405 chore: update versions in issue template for bugs
  .github/ISSUE_TEMPLATE/bug.yml
  contribute/release_procedure.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3391 fix: reconcile `Pooler` `RoleBinding`
  controllers/pooler_update.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3396 fix: add `podRole` label to Pooler deployment
  docs/src/labels_annotations.md
  pkg/specs/pgbouncer/deployments.go
  pkg/specs/pgbouncer/deployments_test.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3408 feat: default Postgres SSL protocol version to TLSv1.3
  .wordlist-en-custom.txt
  docs/src/postgresql_conf.md
  docs/src/security.md
  docs/src/ssl_connections.md
  pkg/postgres/configuration.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3420 test: make unit tests work in a pristine golang container
  Makefile
  internal/cmd/plugin/logs/cluster_logs_test.go
  internal/pgbouncer/management/controller/refresh_test.go
  tests/utils/version_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21

#3419 test: test for cluster restore use volumesnapshot with tablespace
  tests/e2e/fixtures/tablespaces/cluster-volume-snapshot-tablespaces-pitr.yaml.template
  tests/e2e/fixtures/tablespaces/cluster-volume-snapshot-tablespaces-restore.yaml.template
  tests/e2e/fixtures/tablespaces/cluster-volume-snapshot-tablespaces.yaml.template
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/tablespaces_test.go
  tests/e2e/volume_snapshot_test.go
  tests/utils/storage.go
Labels: ok to merge :ok_hand:

#2940 chore: include volume snapshots in cluster status computation
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/backup_controller.go
  controllers/backup_controller_test.go
  docs/src/cloudnative-pg.v1.md
  pkg/management/catalog/catalog.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/backup_test.go
  pkg/reconciler/backup/volumesnapshot/catalog.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21

#3428 fix: watch the secrets owned by a given `Pooler`
  controllers/pooler_controller.go
  controllers/pooler_controller_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21
