Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-02, with the labels that each got.

#3768 docs: fix example in quickstart
  docs/src/quickstart.md
Labels: no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3766 docs: move Grafana dashboard in the `charts` project
  docs/src/monitoring.md
  docs/src/operator_capability_levels.md
  docs/src/quickstart.md
  docs/src/samples/monitoring/grafana-configmap.yaml
  docs/src/samples/monitoring/grafana-dashboard.json
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3667 test: add Openshift as a new CloudVendor in the E2E suite
  .github/workflows/continuous-delivery.yml
  hack/e2e/run-e2e-ocp.sh
  hack/e2e/run-e2e.sh
  tests/e2e/backup_restore_test.go
  tests/e2e/commons_test.go
  tests/e2e/openshift_upgrade_test.go
  tests/e2e/upgrade_test.go
  tests/utils/cloud_vendor.go
  tests/utils/openshift.go
  tests/utils/operator.go
  tests/utils/pod.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3763 docs: Release notes for 1.22.1, 1.21.3, and 1.20.6 (EOL)
  docs/src/release_notes/v1.20.md
  docs/src/release_notes/v1.21.md
  docs/src/release_notes/v1.22.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22

#3773 fix: prune `override.conf` settings from `postgresql.auto.conf`
  docs/src/release_notes/v1.21.md
  docs/src/release_notes/v1.22.md
  pkg/management/postgres/configuration.go
  pkg/management/postgres/instance_replica.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3789 fix: add some missing exceptions
  .github/e2e-matrix-generator.py
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3710 feat: synchronize user-defined physical replication slots
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/index.md
  docs/src/installation_upgrade.md
  docs/src/operator_capability_levels.md
  docs/src/replication.md
  internal/management/controller/slots/infrastructure/postgresmanager.go
  internal/management/controller/slots/infrastructure/postgresmanager_test.go
  internal/management/controller/slots/infrastructure/replicationslot.go
  internal/management/controller/slots/reconciler/replicationslot.go
  internal/management/controller/slots/reconciler/replicationslot_test.go
  internal/management/controller/slots/runner/runner.go
  tests/e2e/asserts_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/replication_slot_test.go
  tests/e2e/scaling_test.go
  tests/e2e/switchover_test.go
  tests/utils/replication_slots.go
Labels: ok to merge :ok_hand:

#3794 chore: deprecate release branch 1.20
  .github/ISSUE_TEMPLATE/bug.yml
  .github/renovate.json5
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  docs/src/release_notes.md
  docs/src/release_notes/old/v1.20.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3786 fix: only test latest version of PostgreSQL
  .github/e2e-matrix-generator.py
  .github/kind_versions.json
  .github/openshift_versions.json
  .github/workflows/public-cloud-k8s-versions-check.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3803 fix: use the ROOT_DIR to execute make and get the version
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3812 test: ensure to use `gomega` assertion in the tablespace tests
  tests/e2e/tablespaces_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3817 Add Ænix to the Adopters list
  ADOPTERS.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3797 test: fixes for E2Es cleanup operations
  .github/workflows/continuous-delivery.yml
  tests/e2e/upgrade_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3800 fix: add the OCP version to the cluster name when creating for testing
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3808 feat: add operator hooks for backups
  .wordlist-en-custom.txt
  api/v1/backup_types.go
  api/v1/backup_webhook.go
  api/v1/cluster_types.go
  api/v1/scheduledbackup_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_backups.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  controllers/backup_controller.go
  controllers/cluster_plugins.go
  docs/src/cloudnative-pg.v1.md
  go.mod
  go.sum
  internal/cnpi/plugin/client/backup.go
  internal/cnpi/plugin/client/connection.go
  internal/cnpi/plugin/client/contracts.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/webserver/local.go
  pkg/management/postgres/webserver/plugin_backup.go
  pkg/resources/retry.go
  pkg/resources/retry_test.go
  pkg/resources/suite_test.go
Labels: ok to merge :ok_hand:, no-issue

#3687 fix: Order tests label in alphabetical order
  tests/e2e/tablespaces_test.go
  tests/labels.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3708 feat: add catalog of available architectures to the Cluster status
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_status.go
  docs/src/cloudnative-pg.v1.md
  internal/cmd/manager/controller/controller.go
  pkg/executablehash/executablehash.go
  pkg/executablehash/executablehash_test.go
  pkg/utils/discovery.go
  pkg/utils/discovery_test.go
  tests/e2e/architecture_test.go
  tests/e2e/fixtures/architectures/cluster-architectures.yaml.template
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3838 fix: properly compare error against syscall.ECHILD
  internal/cmd/manager/instance/run/lifecycle/reaper.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3815 chore: make clear which Dockerfile use every build process
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3833 chore: lint the project with the latest `golangci-lint` version
  cmd/kubectl-cnpg/main.go
  cmd/manager/main.go
  controllers/backup_controller.go
  controllers/backup_predicates.go
  controllers/cluster_cleanup_test.go
  controllers/cluster_predicates.go
  controllers/cluster_upgrade_test.go
  controllers/pooler_predicates_test.go
  internal/cmd/manager/backup/cmd.go
  internal/cmd/manager/controller/cmd.go
  internal/cmd/manager/instance/cmd.go
  internal/cmd/manager/instance/initdb/cmd.go
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/cmd/manager/instance/restore/cmd.go
  internal/cmd/manager/instance/restoresnapshot/cmd.go
  internal/cmd/manager/instance/run/cmd.go
  internal/cmd/manager/instance/status/cmd.go
  internal/cmd/manager/pgbouncer/cmd.go
  internal/cmd/manager/pgbouncer/run/cmd.go
  internal/cmd/manager/show/walarchivequeue/cmd.go
  internal/cmd/plugin/fio/cmd.go
  internal/cmd/plugin/install/generate.go
  internal/cmd/plugin/pgadmin/cmd.go
  internal/cmd/plugin/promote/cmd.go
  internal/cmd/plugin/reload/cmd.go
  internal/cmd/plugin/report/operator.go
  internal/cmd/plugin/snapshot/cmd.go
  internal/cmd/plugin/status/status.go
  internal/cmd/versions/cmd.go
  pkg/management/postgres/instance.go
  pkg/reconciler/backup/volumesnapshot/online_test.go
  pkg/utils/discovery_test.go
  tests/e2e/cluster_setup_test.go
  tests/e2e/logs_test.go
  tests/e2e/suite_test.go
  tests/e2e/tablespaces_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3867 fix: add operator-sdk to the renovate updates
  .github/renovate.json5
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3835 test: fix some rough edges of E2E test scripts
  .github/renovate.json5
  Makefile
  contribute/e2e_testing_environment/README.md
  hack/e2e/run-e2e-k3d.sh
  hack/e2e/run-e2e-kind.sh
  hack/e2e/run-e2e-local.sh
  hack/setup-cluster.sh
  tests/e2e/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3855 fix(olm): use `Role` instead of `ClusterRole` for operator permissions
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3857 fix: avoid logging the entire primary pod object
  controllers/replicas.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3911 fix: reduce the time required for the tablespaces test
  tests/e2e/backup_restore_test.go
  tests/e2e/tablespaces_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3964 Add IBM as CloudNativePG adopter
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22

#3852 ci: alert systematic failures only from main or release branches
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3931 fix: correctly populate barman google capabilities
  pkg/management/barman/capabilities/detect.go
  pkg/management/barman/capabilities/detect_test.go
  pkg/management/barman/capabilities/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22
