Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-07, with the labels that each got.

#4973 chore: add 4.16 to the OpenShift versions list
  .github/openshift_versions.json
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4955 test(e2e): introduce a common interface for test environment capabilities
  tests/e2e/apparmor_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/commons_test.go
  tests/e2e/disk_space_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/operator_ha_test.go
  tests/e2e/volume_snapshot_test.go
  tests/utils/cloud_vendor.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4960 docs: remove strflocaltime from troubleshooting.md
  docs/src/troubleshooting.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4952 feat(managed-services): add support for `updateStrategy`
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/service_management.md
  internal/controller/cluster_controller.go
  internal/controller/cluster_create.go
  pkg/specs/services.go
  pkg/utils/labels_annotations.go
  tests/e2e/fixtures/managed_services/cluster-managed-services-replace-strategy.yaml.template
  tests/e2e/managed_services_test.go
Labels: ok to merge :ok_hand:, do not backport

#4988 fix: linter
  tests/utils/proxy.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#4989 fix: linter
  tests/utils/proxy.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#4984 chore: dismiss support for OpenShift 4.11
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4897 chore: deprecate `role` label
  internal/cmd/plugin/psql/psql_test.go
  internal/cmd/plugin/status/status.go
  internal/controller/cluster_controller.go
  internal/controller/cluster_create_test.go
  pkg/reconciler/hibernation/reconciler_test.go
  pkg/reconciler/instance/metadata.go
  pkg/reconciler/instance/metadata_test.go
  pkg/reconciler/persistentvolumeclaim/suite_test.go
  pkg/specs/poddisruptionbudget.go
  pkg/specs/pods.go
  pkg/specs/services.go
  pkg/specs/services_test.go
  tests/e2e/asserts_test.go
  tests/utils/cluster.go
Labels: risk :boom:, ok to merge :ok_hand:, do not backport

#4834 docs: Cluster-Wide Permissions and Operator Deployment
  docs/src/security.md
Labels: documentation :book:, ok to merge :ok_hand:, release-1.22, release-1.23

#5013 chore: exclude pkg/versions from renovate
  .github/renovate.json5
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#4974 chore: use a proxy to the pod instead of exec a command inside the pod
  internal/cmd/plugin/status/status.go
  internal/plugin/resources/instance.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5010 chore: fix Dockerfile warning related to uppercase and lowercase mix
  Dockerfile
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#4967 fix(pooler): do not reconcile resouces that aren't owned
  internal/controller/pooler_controller.go
  internal/controller/pooler_controller_test.go
  internal/controller/pooler_predicates.go
  internal/controller/pooler_update.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4900 chore: add support for Release Candidates
  .github/workflows/release-pr.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-tag.yml
  contribute/release_procedure.md
  docs/src/supported_releases.md
  hack/release.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5006 fix(pooler): enhance rollout control during operator upgrade
  internal/controller/pooler_update.go
  pkg/specs/pgbouncer/deployments.go
  pkg/specs/pgbouncer/deployments_test.go
  pkg/utils/hash/hash.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5037 chore: remove seccomp detection, drop support of k8s < 1.25
  internal/cmd/manager/controller/controller.go
  pkg/specs/containers.go
  pkg/specs/containers_test.go
  pkg/specs/pods.go
  pkg/specs/pods_test.go
  pkg/utils/discovery.go
  pkg/utils/discovery_test.go
  tests/utils/azurite.go
  tests/utils/environment.go
  tests/utils/minio.go
  tests/utils/psql_client.go
  tests/utils/webapp.go
Labels: ok to merge :ok_hand:

#5051 test: fix logging for EKS e2e runs
  .github/workflows/continuous-delivery.yml
  hack/e2e/eks-cluster.yaml.template
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5057 fix(docs): require `backupID` for non-time-based recovery targets
  docs/src/recovery.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23

#5054 fix(tests): kubectl cnpg status unit tests
  internal/cmd/plugin/status/status.go
  internal/cmd/plugin/status/status_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5049 ci: ensure default value is correct in workflow ui
  .github/workflows/continuous-delivery.yml
  contribute/e2e_testing_environment/README.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5065 docs: add ParadeDB to ADOPTERS.md
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23

#4921 feat: add support for `allow_alter_system` in PostgreSQL 17
  api/v1/cluster_webhook.go
  docs/src/postgresql_conf.md
  internal/management/controller/instance_controller.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/instance_test.go
  pkg/postgres/configuration.go
  pkg/postgres/configuration_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#2056 fix: improve handling terminated and unschedulable pods
  internal/controller/cluster_controller.go
  internal/controller/cluster_upgrade.go
  internal/controller/cluster_upgrade_test.go
  pkg/utils/pod_conditions.go
  pkg/utils/pod_conditions_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5041 chore: enable regional cluster for GKE test
  .github/workflows/continuous-delivery.yml
  tests/e2e/apparmor_test.go
  tests/e2e/commons_test.go
  tests/e2e/disk_space_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/operator_ha_test.go
  tests/utils/cloud_vendor.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5061 test: fix replica mode test failure
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5101 fix: always return a ctx when invoking `NewTLSConfigForContext`
  pkg/certs/tls.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4424 feat: Add plugin method to ScheduledBackup
  api/v1/scheduledbackup_types.go
  config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
  docs/src/cloudnative-pg.v1.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.23

#5082 test(e2e): check if replicas are connected via streaming
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5074 feat: add SQLRefs support for PostInit and PostInitTemplate
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/bootstrap.md
  docs/src/cloudnative-pg.v1.md
  internal/cmd/manager/instance/initdb/cmd.go
  pkg/management/postgres/initdb.go
  pkg/specs/jobs.go
  pkg/specs/jobs_test.go
  pkg/specs/volumes.go
  pkg/specs/volumes_test.go
  tests/e2e/fixtures/initdb/cluster-postinit-sql.yaml.template
  tests/e2e/fixtures/initdb/cluster_post_init_application_configmap.yaml
  tests/e2e/fixtures/initdb/cluster_post_init_application_secret.yaml
  tests/e2e/fixtures/initdb/cluster_post_init_template_configmap.yaml
  tests/e2e/fixtures/initdb/cluster_post_init_template_secret.yaml
  tests/e2e/initdb_test.go
Labels: ok to merge :ok_hand:, do not backport

#5069 feat: support the annotation `reconcilePodSpec` on Cluster
  docs/src/connection_pooling.md
  docs/src/labels_annotations.md
  internal/controller/cluster_upgrade.go
  internal/controller/cluster_upgrade_test.go
  internal/controller/pooler_update.go
  internal/controller/pooler_update_test.go
  internal/controller/suite_test.go
  pkg/utils/labels_annotations_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5110 chore: reduce `current.Configuration` global variable usage
  internal/cmd/manager/controller/cmd.go
  internal/cmd/manager/controller/controller.go
Labels: ok to merge :ok_hand:, no-issue

#5106 fix: restrict plugin listener to the operator namespace
  internal/cmd/manager/controller/controller.go
  internal/controller/plugin_controller.go
  internal/controller/plugin_predicates.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#5139 doc: remove references to delayed replicas
  docs/src/index.md
  docs/src/operator_capability_levels.md
  docs/src/replica_cluster.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5031 chore: improve OLM environment detection
  internal/cmd/plugin/report/olm.go
  internal/cmd/plugin/report/operator_objects.go
  internal/cmd/plugin/report/operator_report.go
  pkg/utils/discovery.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5115 fix(docs): clarify usage of distroless images for the operator
  .wordlist-en-custom.txt
  docs/src/index.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5133 docs: distributed topology through replica clusters
  .wordlist-en-custom.txt
  docs/src/architecture.md
  docs/src/index.md
  docs/src/installation_upgrade.md
  docs/src/operator_capability_levels.md
  docs/src/replica_cluster.md
Labels: ok to merge :ok_hand:, do not backport

#5112 fix: cleanup PGDATA before initializing a PVC
  internal/cmd/manager/instance/initdb/cmd.go
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/restore/cmd.go
  pkg/fileutils/fileutils.go
  pkg/fileutils/fileutils_test.go
  pkg/management/postgres/initdb.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5161 chore: woke linting
  pkg/management/postgres/initdb.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5158 chore(security): use a known path to execute manager
  pkg/management/upgrade/upgrade.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4927 feat: add optional TLS communication for the metrics exporter on the instances
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/monitoring.md
  docs/src/security.md
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/run/cmd.go
  internal/management/controller/manager.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/webserver/local.go
  pkg/management/postgres/webserver/metricserver/metrics.go
  pkg/management/postgres/webserver/remote.go
  pkg/management/postgres/webserver/webserver.go
  pkg/specs/podmonitor.go
  pkg/specs/podmonitor_test.go
  pkg/specs/pods.go
Labels: ok to merge :ok_hand:, do not backport

#5160 chore: enable unit tests on Kubernetes 1.30
  .github/k8s_versions_scope.json
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5109 fix(scheduled-backups): manage unsatisfiable schedules
  internal/controller/scheduledbackup_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5137 chore(deps): automate update of Openshift supported versions
  .github/workflows/k8s-versions-check.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5149 feat(plugin): display `demotionToken` in `cnpg status`
  docs/src/replica_cluster.md
  internal/cmd/plugin/status/status.go
Labels: ok to merge :ok_hand:, do not backport

#5113 feat(plugin): enable customizing the remote dbname in subscriptions and publications
  internal/cmd/plugin/logical/externalcluster.go
  internal/cmd/plugin/logical/publication/create/cmd.go
  internal/cmd/plugin/logical/publication/drop/cmd.go
  internal/cmd/plugin/logical/subscription/create/cmd.go
  pkg/management/external/external.go
Labels: ok to merge :ok_hand:, do not backport

#5156 fix: PG instances anti-affinity configuration
  docs/src/scheduling.md
  pkg/specs/pods.go
  tests/e2e/affinity_test.go
  tests/e2e/fixtures/affinity/cluster-affinity.yaml
  tests/e2e/fixtures/affinity/pooler-affinity.yaml
  tests/e2e/upgrade_test.go
Labels: ok to merge :ok_hand:, do not backport

#5180 docs: remove obsolete references for older versions
  docs/src/applications.md
  docs/src/backup.md
  docs/src/backup_recovery.md
  docs/src/backup_volumesnapshot.md
  docs/src/declarative_role_management.md
  docs/src/kubectl-plugin.md
  docs/src/recovery.md
  docs/src/release_notes.md
  docs/src/release_notes/old/v1.20.md
  docs/src/release_notes/old/v1.21.md
  docs/src/replication.md
  docs/src/security.md
  docs/src/troubleshooting.md
  docs/src/wal_archiving.md
Labels: release-1.23

#4359 fix: quoting of $CONTEXT variable in k9s plugin
  docs/src/samples/k9s/plugins.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5140 docs: release notes for 1.24.0-rc1, 1.23.3, and 1.22.5
  .wordlist-en-custom.txt
  docs/mkdocs.yml
  docs/src/preview_version.md
  docs/src/release_notes.md
  docs/src/release_notes/v1.22.md
  docs/src/release_notes/v1.23.md
  docs/src/release_notes/v1.24.md
  docs/src/supported_releases.md
Labels: documentation :book:, do not backport

#5182 docs: clarify database configuration with recovery (#5167)
  .wordlist-en-custom.txt
  docs/src/bootstrap.md
  docs/src/recovery.md
  docs/src/replica_cluster.md
Labels: ok to merge :ok_hand:

#5185 docs: release notes for 1.22.5 (#5140)
  .wordlist-en-custom.txt
  docs/src/release_notes/v1.22.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, no-issue

#5181 feat: introduce `minApplyDelay` for delayed replicas
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/index.md
  docs/src/operator_capability_levels.md
  docs/src/release_notes/v1.24.md
  docs/src/replica_cluster.md
  pkg/management/postgres/configuration.go
  pkg/management/postgres/configuration_test.go
  pkg/postgres/configuration.go
  pkg/postgres/configuration_test.go
Labels: ok to merge :ok_hand:, do not backport

#5193 docs: update release date for 1.24.0-rc1
  docs/src/release_notes/v1.24.md
Labels: ok to merge :ok_hand:, no-issue

#5198 chore: remove commented code
  tests/e2e/backup_restore_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5196 fix: avoid using backticks in cobra flags
  internal/cmd/plugin/backup/cmd.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5204 test(e2e): remove workaround for anti-affinity rollout
  tests/e2e/upgrade_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, do not backport

#5195 test: some improvements to general asserts
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5207 test(e2e): prevent failures in the corruption test
  tests/e2e/pg_data_corruption_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23
