Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-05, with the labels that each got.

#4437 fix: log private key changes in refreshCertificateFilesFromSecret
  internal/management/controller/instance_controller.go
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4453 tests: do not verify pg_stat_bgwriter metrics in v17
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4455 docs: Adopt the `governance` repository
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  GOVERNANCE.md
  MAINTAINERS.md
  README.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4434 fix: instance manager stuck if PostgreSQL doesn't start
  internal/cmd/manager/instance/run/lifecycle/run.go
  internal/management/controller/instance_controller.go
  internal/management/controller/instance_startup.go
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4456 docs: fixing typo in object_stores.md
  .spellcheck.yaml
  docs/src/appendixes/object_stores.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4500 docs: update join slack link
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.md
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4520 fix: spellcheck makefile target fails if SELinux is active
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4448 test: avoid log flooding in switchover/failover tests
  tests/e2e/fixtures/base/cluster-storage-class-with-rep-slots.yaml.template
  tests/e2e/fixtures/fastfailover/cluster-fast-failover-with-repl-slots.yaml.template
  tests/e2e/fixtures/fastfailover/cluster-syncreplicas-fast-failover.yaml.template
  tests/e2e/fixtures/fastswitchover/cluster-fast-switchover-with-repl-slots.yaml.template
  tests/e2e/fixtures/replication_slot/cluster-pg-replication-slot-disable.yaml.template
  tests/e2e/fixtures/switchover/cluster-switchover-with-rep-slots.yaml.template
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4532 fix: increase the timeout for the failover/switchover tests
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4531 fix: avoid reloading Postgres when unnecessary
  pkg/configfile/configfile.go
  pkg/management/postgres/configuration.go
  pkg/stringset/stringset.go
  pkg/stringset/stringset_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4451 fix: add missing option to the AKS e2e tests
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4397 docs: support new Apple Silicon homebrew path in setup instructions
  contribute/development_environment/README.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4398 [Refactoring] refactor cluster reconciling defer
  controllers/cluster_controller.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#4446 kubernetes_upgrade.md: use --delete-emptydir-data.
  docs/src/kubernetes_upgrade.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4383 chore: setup credentials for preflight check test
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4530 [plugin] use namespace to get the PodDisruptionBudgetList
  internal/cmd/plugin/status/status.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4542 ci: k8s-versions-checker should exclude alpha versions before sorting
  .github/workflows/public-cloud-k8s-versions-check.yml
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4543 chore: stop testing on Kubernetes 1.23 and 1.24
  .github/ISSUE_TEMPLATE/bug.yml
  .github/k8s_versions_scope.json
  .github/workflows/public-cloud-k8s-versions-check.yml
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
  docs/src/e2e.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4427 chore: improve the operator deployment detection
  tests/e2e/eviction_test.go
  tests/e2e/operator_deployment_test.go
  tests/e2e/operator_ha_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/webhook_test.go
  tests/utils/operator.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4540 chore: add first group of component owners
  CODEOWNERS
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4544 ci: fix kind kubernetes version check failed
  .github/workflows/public-cloud-k8s-versions-check.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4547 chore(olm): downgrade minKubeVersion to 1.23
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4554 chore: add Niccolò as OLM component owner
  CODEOWNERS
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4562 fix: crds misaligned after Kubernetes API 0.30.1 upgrade
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4559 ci(chore): add renovate linter
  .github/workflows/continuous-integration.yml
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4557 chore: add another group to renovate "operator framework"
  .github/renovate.json5
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4567 ci: steps containing retriable code shouldn't terminate on a non-zero exit status
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4577 ci: fix `kubectl wait` command
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4579 ci: fix EKS version update check
  .github/workflows/public-cloud-k8s-versions-check.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4568 ci(fix): increase cpu requirements for the operator deployment
  hack/e2e/env_override_customized.yaml.template
Labels: no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4587 chore: enable 1.23.1 as option in bug template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4473 ci: run govulncheck only if go code changed
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4425 chore: avoid hitting the API server when updating plugins status
  controllers/cluster_plugins.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.23

#4603 docs: typo in kube-stack-config file
  docs/src/samples/monitoring/kube-stack-config.yaml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4604 test(fix): increase ginkgo timeout on upgrade test
  hack/e2e/run-e2e.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4504 fix: timeout when restarting PostgreSQL and while lifting fencing
  api/v1/cluster_types.go
  internal/management/controller/instance_controller.go
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4380 chores: use fullname for replaces value in csv file
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4607 chore: stop testing on Kubernetes 1.25
  .github/ISSUE_TEMPLATE/bug.yml
  .github/k8s_versions_scope.json
  .github/workflows/public-cloud-k8s-versions-check.yml
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4602 docs: add homebrew install method for kubectl plugin
  docs/src/kubectl-plugin.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.23

#4617 fix: typo on documentation
  .wordlist-en-custom.txt
Labels: no-issue, backport-requested :arrow_backward:, release-1.23

#4625 fix: prevent fenced instances from using all the CPUs
  internal/cmd/manager/instance/run/lifecycle/lifecycle.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, ready to test :elephant:, release-1.21, release-1.22, release-1.23

#4399 fix: replica cluster should restart after promotion
  internal/management/controller/instance_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4637 fix: avoid conflicts when registering phases
  controllers/cluster_status.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4641 fix: switch to manual build mode in CodeQL action
  .github/workflows/codeql-analysis.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4619 ci: fix variable substitution in workflow output
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4632 chore: remove stale POD_DEBUG environment variable
  internal/cmd/manager/controller/controller.go
  internal/configuration/configuration.go
  pkg/configparser/configparser_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4647 test(fix): improve readability of some errors during upgrade E2E test
  tests/e2e/upgrade_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4635 fix: stop logging about missing sync replicas when not required
  api/v1/cluster_configuration.go
  api/v1/cluster_configuration_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4707 chore(deps): update azure/setup-kubectl action to v4
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4709 test(fix): setting the default tier to `default` on AKS test
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4648 fix: avoid reloading ident map when not needed
  internal/management/controller/instance_controller.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/ident.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4670 fix: avoid shutting down the instance manager if it is not needed
  internal/cmd/manager/instance/run/lifecycle/run.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4494 chore: admit general PG booleans for configuration
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  pkg/postgres/booleans.go
  pkg/postgres/booleans_test.go
  pkg/postgres/configuration.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4702 test(fix): add the missing report failed e2e tests section
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4503 feat: implement predicate_query to validate which are the metrics to be collected
  docs/src/monitoring.md
  pkg/management/postgres/metrics/collector.go
  pkg/management/postgres/metrics/parser.go
  pkg/management/postgres/metrics/parser_test.go
  tests/e2e/asserts_test.go
  tests/e2e/fixtures/metrics/cluster-metrics-with-predicate-query.yaml.template
  tests/e2e/fixtures/metrics/custom-queries-with-predicate-query.yaml
  tests/e2e/metrics_test.go
Labels: ok to merge :ok_hand:

#4712 test(e2e): skip Drain E2E with reusePVC set to off on GKE
  tests/e2e/drain_node_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4609 test(fix): increase the short timeout
  .github/e2e_test_timeout.json
  contribute/e2e_testing_environment/README.md
  pkg/utils/logs/cluster_logs.go
  tests/utils/timeouts.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4650 test(e2e): fix backup failures for replica mode
  tests/e2e/asserts_test.go
  tests/e2e/fixtures/metrics/custom-queries-for-replica-cluster.yaml
  tests/e2e/metrics_test.go
  tests/e2e/replica_mode_cluster_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4706 test(e2e): retry statements on failure
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23
