Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-04, with the labels that each got.

#4101 chore: improve `barman-cloud-wal-restore` error detection
  pkg/management/barman/restorer/restorer.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4131 fix(plugin): percentage in physical backup progress
  internal/cmd/plugin/status/status.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4201 chore: update the base image for the operator
  Dockerfile
Labels: ok to merge :ok_hand:

#4222 chore: update Go version in go.mod file
  go.mod
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4095 Change jdbc-uri and uri in app secret
  pkg/specs/secrets.go
  pkg/specs/secrets_test.go
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22

#4223 chore: remove the UUID from the logs
  go.mod
  pkg/management/log/log.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4212 fix: align enableSuperuserAccess default
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4191 Added badges to the README
  README.md
Labels: ok to merge :ok_hand:, no-issue

#4048 chore: add external CSI components and rook to Renovate
  .github/renovate.json5
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4230 fix: create renovate group for kubernetes CSI
  .github/renovate.json5
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4243 fix: renovate should create only one PR for CSI tools
  .github/renovate.json5
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4246 fix: go back to use a fixed version for the CSI deployment
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4245 doc: improve instanceRole, podRole and role definitions
  docs/src/labels_annotations.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4196 chore: add the replace section for the CSV
  Makefile
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4161 ci: minor release improvements
  .github/workflows/release-pr.yml
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4218 feat: enable configuration of `wal_log_hints`
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  docs/src/postgresql_conf.md
  pkg/postgres/configuration.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4197 test: remove `envtest` from the controller package
  controllers/backup_controller_test.go
  controllers/cluster_controller_test.go
  controllers/cluster_create_test.go
  controllers/cluster_delete_test.go
  controllers/cluster_scale_test.go
  controllers/cluster_status_test.go
  controllers/pooler_controller_test.go
  controllers/pooler_predicates_test.go
  controllers/pooler_resources_test.go
  controllers/pooler_status_test.go
  controllers/pooler_update_test.go
  controllers/suite_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4152 refactor: improve metadata fencing code organization
  api/v1/cluster_types.go
  controllers/cluster_restore.go
  controllers/cluster_restore_test.go
  internal/cmd/plugin/fence/fence.go
  internal/cmd/plugin/hibernate/on.go
  internal/cmd/plugin/status/status.go
  pkg/reconciler/backup/volumesnapshot/offline.go
  pkg/reconciler/backup/volumesnapshot/offline_test.go
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  pkg/resources/fencing.go
  pkg/utils/fencing.go
  pkg/utils/fencing_test.go
  tests/utils/fence.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4255 fix: using right tag for UBI8 image during e2e
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4132 fix: skip updateTargetPrimary if no instance status is available
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
  controllers/cluster_upgrade.go
  controllers/replicas.go
Labels: risk :boom:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4276 docs: add CNCF Landscape badge
  README.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4269 fix: regression related to the arguments
  internal/cmd/plugin/maintenance/cmd.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4283 fix: empty LSN handling in instance sorting
  pkg/postgres/lsn.go
  pkg/postgres/lsn_test.go
  pkg/postgres/status_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4189 test: add openshift-preflight tests to the CI
  .github/renovate.json5
  .github/workflows/continuous-integration.yml
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4288 fix: wait for elected replica to be in streaming mode before a switchover
  controllers/cluster_controller.go
  controllers/cluster_upgrade.go
Labels: ok to merge :ok_hand:

#4307 chore: increase the timeout for failover test on OpenShift
  tests/e2e/asserts_test.go
  tests/e2e/fastfailover_test.go
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22

#4280 fix: destroy command show meaningful message if pod not exists
  internal/cmd/plugin/destroy/cmd.go
  internal/cmd/plugin/destroy/destroy.go
  internal/cmd/plugin/fence/cmd.go
  internal/cmd/plugin/promote/cmd.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4270 chore: add SBOMs for the operator container images and archive builds
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
  .goreleaser.yml
Labels: ok to merge :ok_hand:

#3705 fix: reload certificates on configuration update
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3384 feat: allow setting a service type and annotations for a pooler resource
  .wordlist-en-custom.txt
  api/v1/pooler_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  controllers/pooler_resources_test.go
  controllers/pooler_update.go
  controllers/pooler_update_test.go
  docs/src/cloudnative-pg.v1.md
  docs/src/connection_pooling.md
  docs/src/samples.md
  docs/src/samples/pooler-external.yaml
  pkg/management/pgbouncer/config/config.go
  pkg/servicespec/builder.go
  pkg/servicespec/builder_test.go
  pkg/servicespec/suite_test.go
  pkg/specs/pgbouncer/deployments.go
  pkg/specs/pgbouncer/services.go
  pkg/specs/pgbouncer/services_test.go
Labels: ok to merge :ok_hand:

#4279 test(e2e): more precise wildcard to match wal file
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/utils/minio.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4322 chore: correct typo in the documentation
  docs/src/connection_pooling.md
Labels: ok to merge :ok_hand:, no-issue

#4309 chore: increase waiting for a mounted secret timeout
  pkg/certs/k8s.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4330 fix: use full instance name for the destroy method
  internal/cmd/plugin/hibernate/on.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4302 fix: do not patch when object doesn't change
  internal/cnpi/plugin/operatorclient/client.go
Labels: ok to merge :ok_hand:, do not backport

#4151 feat: cleanup pgdata directory if restore job failed
  internal/cmd/manager/instance/restore/cmd.go
  pkg/fileutils/fileutils.go
  pkg/fileutils/fileutils_test.go
  pkg/management/barman/capabilities/detect.go
  pkg/management/barman/capabilities/detect_test.go
  pkg/management/barman/capabilities/type.go
  pkg/management/barman/errors.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4336 chore: fix makefile nested command
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4340 fix: regression on the creation of the bundle and catalog for OLM
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
  Makefile
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4346 fix(plugin): handle empty response in sync-sequences plugin command
  internal/cmd/plugin/logical/subscription/syncsequences/get.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4321 docs: `ClusterImageCatalog` for `postgresql` and `postgis` images
  docs/src/image_catalog.md
  docs/src/rolling_update.md
Labels: ok to merge :ok_hand:, do not backport

#4349 doc: fix typo in image catalog doc
  docs/src/image_catalog.md
Labels: ok to merge :ok_hand:, no-issue, do not backport

#4319 feat: add PDB to the plugin `status` command
  internal/cmd/plugin/status/status.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4364 fix: disable metrics from `pg_stat_bgwriter` in v17+
  config/manager/default-monitoring.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4351 docs: update README
  README.md
Labels: ok to merge :ok_hand:, do not backport

#4370 chore(CI): add 1.23 in workflows and issue template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
Labels: no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4373 fix(docs): Add user-defined replication slots to the 1.23 release
  docs/src/installation_upgrade.md
  docs/src/release_notes/v1.23.md
Labels: documentation :book:, backport-requested :arrow_backward:, release-1.23

#4385 docs: fix minor editing error in container images doc
  docs/src/container_images.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.23

#4282 fix: PodMonitor regression
  contribute/e2e_testing_environment/README.md
  hack/setup-cluster.sh
  internal/cnpi/plugin/client/lifecycle.go
  tests/e2e/fixtures/monitoring/cluster-default-monitoring.yaml
  tests/e2e/monitoring_test.go
  tests/utils/environment.go
  tests/utils/monitoring.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.23

#4401 docs: Release notes for 1.23.1
  docs/src/release_notes/v1.23.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.23
