Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-12, with the labels that each got.

#6229 chore(docs): template for release notes for a new minor
  contribute/release-notes-template.md
  contribute/release_procedure.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#4848 fix(docs): use correct value for `cnpg.io/skipWalArchiving`
  docs/src/labels_annotations.md
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#6214 feat(import): add support for extra `pg_dump` and `pg_restore` options
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/database_import.md
  docs/src/samples/cluster-import-snapshot-basicauth.yaml
  pkg/management/postgres/logicalimport/database.go
  pkg/management/postgres/logicalimport/microservice.go
  pkg/management/postgres/logicalimport/monolith.go
  tests/utils/import_db.go
Labels: ok to merge :ok_hand:, do not backport

#6219 fix(initdb): ensure `primary_slot_name` is empty on a primary
  pkg/management/postgres/configuration.go
  pkg/management/postgres/initdb.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6226 chore: add `lint-fix` to the Makefile commands
  Makefile
Labels: no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6170 fix: add `PhaseUnrecoverable` in case of no pvc left
  api/v1/cluster_types.go
  internal/controller/cluster_create.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6225 fix(status): add `restoreJobHookCapabilities` in the `PluginStatus`
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  internal/cnpi/plugin/connection/connection.go
  internal/cnpi/plugin/connection/metadata.go
  internal/controller/cluster_plugins.go
Labels: no-issue, backport-requested :arrow_backward:, release-1.24

#6107 chore: remove unknown fields and improve CSV specs
  .spellcheck.yaml
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6175 fix(docs): add default rule for PgBouncer in `pg_hba`
  docs/src/postgresql_conf.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6213 chore: make cnpg plugin commands compatible with OLM
  cmd/kubectl-cnpg/main.go
  internal/cmd/plugin/fio/cmd.go
  internal/cmd/plugin/fio/fio.go
  internal/cmd/plugin/logical/psql.go
  internal/cmd/plugin/plugin.go
  internal/cmd/plugin/psql/psql.go
  internal/cmd/plugin/psql/psql_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6220 feat(initdb): add support for ICU and built-in locale providers
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/bootstrap.md
  docs/src/cloudnative-pg.v1.md
  docs/src/samples/cluster-example-initdb-icu.yaml
  pkg/specs/jobs.go
  pkg/specs/jobs_test.go
Labels: ok to merge :ok_hand:, do not backport

#6216 feat(pooler): expand configurable options for PgBouncer
  api/v1/pooler_webhook.go
  docs/src/connection_pooling.md
  docs/src/samples/pooler-tls.yaml
Labels: ok to merge :ok_hand:, do not backport

#6253 docs(plugin): standardize the `CLUSTER` argument in plugin commands
  docs/src/kubectl-plugin.md
  internal/cmd/plugin/logical/publication/create/cmd.go
  internal/cmd/plugin/logical/publication/drop/cmd.go
  internal/cmd/plugin/logical/subscription/create/cmd.go
  internal/cmd/plugin/logical/subscription/drop/cmd.go
  internal/cmd/plugin/logical/subscription/syncsequences/cmd.go
  internal/cmd/plugin/logs/cluster.go
  internal/cmd/plugin/pgbench/cmd.go
  internal/cmd/plugin/pgbench/pgbench.go
  internal/cmd/plugin/promote/cmd.go
  internal/cmd/plugin/report/cluster.go
  internal/cmd/plugin/restart/cmd.go
  internal/cmd/plugin/snapshot/cmd.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6232 feat(plugin): report plugins in `status` command
  internal/cmd/plugin/status/status.go
Labels: ok to merge :ok_hand:, do not backport

#6255 fix: correct path for partial wal archiver
  pkg/management/postgres/webserver/remote.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24

#6266 feat(probes): enable customization of startup, liveness, and readiness probes
  .wordlist-en-custom.txt
  api/v1/cluster_funcs.go
  api/v1/cluster_funcs_test.go
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/failure_modes.md
  docs/src/instance_manager.md
  docs/src/operator_capability_levels.md
  pkg/specs/pods.go
  pkg/specs/podspec_diff.go
  pkg/specs/podspec_diff_test.go
  tests/e2e/probes_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6212 refactor: use existing error handling functions in the `DatabaseReconciler`
  api/v1/database_funcs.go
  internal/management/controller/common.go
  internal/management/controller/common_test.go
  internal/management/controller/database_controller.go
  internal/management/controller/database_controller_test.go
  internal/management/controller/publication_controller.go
  internal/management/controller/subscription_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6277 fix: eliminate redundant Cluster status updates with image catalog
  internal/controller/cluster_image.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.23, release-1.24

#6279 chore: update object status to failed when referred cluster is deleted
  api/v1/database_funcs.go
  api/v1/publication_funcs.go
  api/v1/subscription_funcs.go
  internal/controller/cluster_controller.go
  internal/controller/finalizers_delete.go
  internal/controller/finalizers_delete_test.go
Labels: ok to merge :ok_hand:, do not backport

#6257 fix(plugin): pass context in `psql` command
  internal/cmd/plugin/plugin.go
  internal/cmd/plugin/psql/cmd.go
  internal/cmd/plugin/psql/psql.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6265 fix(bootstrap): clean up the WAL volume before initializing a cluster
  internal/cmd/manager/instance/initdb/cmd.go
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/restore/restore.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/initdb_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6239 docs: define RPO and RTO
  .wordlist-en-custom.txt
  docs/src/architecture.md
  docs/src/backup.md
  docs/src/before_you_start.md
  docs/src/failover.md
  docs/src/faq.md
  docs/src/instance_manager.md
  docs/src/operator_capability_levels.md
  docs/src/replication.md
  docs/src/rolling_update.md
  docs/src/wal_archiving.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6282 docs: explain logical replication and database examples
  docs/src/samples.md
Labels: do not backport

#5678 feat: add support for `maxConcurrentReconciles`
  config/manager/manager.yaml
  internal/cmd/manager/controller/cmd.go
  internal/cmd/manager/controller/controller.go
  internal/controller/cluster_controller.go
  internal/controller/plugin_controller.go
  internal/controller/pooler_controller.go
  internal/controller/scheduledbackup_controller.go
Labels: ok to merge :ok_hand:, do not backport

#6143 add a sample file of a cluster using scaleway s3 storage
  docs/src/samples.md
  docs/src/samples/cluster-exemple-with-backup-scaleway.yaml
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5998 fix(plugin): avoid displaying physical backups block when empty
  internal/cmd/plugin/status/status.go
Labels: bug :bug:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6157 chore: drop support for `pg_rewind` in PostgreSQL 12
  internal/management/controller/instance_startup.go
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:

#6290 chore(lint): spellcheck word list
  .wordlist-en-custom.txt
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6092 chore(plugin): improve getting instance status from pod error message
  internal/plugin/resources/instance.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5898 chore(e2e): Separate forward connection from psql connection
  tests/e2e/asserts_test.go
  tests/e2e/connection_test.go
  tests/e2e/managed_roles_test.go
  tests/e2e/pg_basebackup_test.go
  tests/e2e/update_user_test.go
  tests/utils/forwardconnection/doc.go
  tests/utils/forwardconnection/forwardconnection.go
  tests/utils/psql_connection.go
  tests/utils/service.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6258 feat: ensure unique manager for declarative PostgreSQL resources
  api/v1/database_funcs.go
  api/v1/generic_funcs.go
  api/v1/publication_funcs.go
  api/v1/subscription_funcs.go
  internal/management/controller/common.go
  internal/management/controller/database_controller.go
  internal/management/controller/database_controller_test.go
  internal/management/controller/publication_controller.go
  internal/management/controller/subscription_controller.go
Labels: ok to merge :ok_hand:, do not backport

#6291 test: express the initdb unit tests coherently
  pkg/management/postgres/initdb_test.go
Labels: no-issue, do not backport

#4392 feat: add `cnpg.io/userType` label to generated secrets
  docs/src/labels_annotations.md
  internal/controller/cluster_create.go
  pkg/specs/secrets.go
  pkg/specs/secrets_test.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6249 feat(OLM): enhance UI descriptions for Database, Publication, and Subscription CRDs
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
Labels: ok to merge :ok_hand:, do not backport, olm

#6153 feat(plugin): set `User-Agent` in HTTP requests
  internal/cmd/plugin/plugin.go
  internal/cmd/plugin/plugin_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#4934 test: make sure we test port correctness for internal services
  pkg/specs/services_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5001 docs: clarify behavior of primaryUpdateStrategy for single-instance clusters
  docs/src/installation_upgrade.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#3806 Docs: Fix a couple of links and one heading level
  docs/src/cluster_conf.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6275 docs: release notes for 1.25.0-rc1
  docs/src/preview_version.md
  docs/src/release_notes.md
  docs/src/release_notes/v1.25.md
  docs/src/supported_releases.md
Labels: do not backport

#6296 docs(security): mention new CRDs
  docs/src/security.md
Labels: do not backport

#6309 fix: deadlock when a plugin is used multiple times
  internal/cnpi/plugin/client/client.go
  internal/cnpi/plugin/repository/connection.go
  internal/cnpi/plugin/repository/setup.go
  internal/controller/cluster_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24

#6312 chore(refactor): isolate plugin loading function
  internal/cnpi/plugin/client/client.go
  internal/cnpi/plugin/repository/connection.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.24

#6106 fix(olm): improve scorecard test implementing suggestions
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
  config/olm-samples/postgresql_v1_backup.yaml
  config/olm-samples/postgresql_v1_cluster.yaml
  config/olm-samples/postgresql_v1_clusterimagecatalog.yaml
  config/olm-samples/postgresql_v1_database.yaml
  config/olm-samples/postgresql_v1_imagecatalog.yaml
  config/olm-samples/postgresql_v1_pooler.yaml
  config/olm-samples/postgresql_v1_publication.yaml
  config/olm-samples/postgresql_v1_scheduledbackup.yaml
  config/olm-samples/postgresql_v1_subscription.yaml
Labels: ok to merge :ok_hand:, do not backport

#6284 tests: add unit tests to publication and subscription controllers
  internal/management/controller/database_controller.go
  internal/management/controller/database_controller_test.go
  internal/management/controller/publication_controller.go
  internal/management/controller/publication_controller_sql.go
  internal/management/controller/publication_controller_test.go
  internal/management/controller/subscription_controller.go
  internal/management/controller/subscription_controller_sql.go
  internal/management/controller/subscription_controller_test.go
Labels: ok to merge :ok_hand:, do not backport

#6328 fix: use optimistic locking when updating conditions
  api/v1/cluster_conditions.go
  internal/controller/backup_controller.go
  pkg/conditions/conditions.go
  pkg/conditions/doc.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/backup_test.go
  pkg/management/postgres/webserver/local.go
  pkg/management/postgres/webserver/plugin_backup.go
  pkg/reconciler/replicaclusterswitch/reconciler.go
  pkg/resources/status/conditions.go
  pkg/resources/status/phase.go
  pkg/resources/status/update.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6320 test(e2e): add coverage for Publication and Subscription features
  .github/workflows/continuous-delivery.yml
  tests/e2e/asserts_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/declarative_database_management_test.go
  tests/e2e/fixtures/declarative_pub_sub/destination-database.yaml
  tests/e2e/fixtures/declarative_pub_sub/source-database.yaml
  tests/e2e/managed_roles_test.go
  tests/e2e/publication_subscription_test.go
  tests/labels.go
Labels: ok to merge :ok_hand:, do not backport

#6378 test(e2e): fix a panic in publication and subscription test
  tests/e2e/publication_subscription_test.go
Labels: ok to merge :ok_hand:, do not backport

#6346 fix(roles): properly quote inRoles in SQL statements
  internal/management/controller/roles/postgres.go
  internal/management/controller/roles/postgres_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6377 fix: add missing labels in container images
  Dockerfile
  Dockerfile-ubi8
  Dockerfile-ubi9
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6390 chore: add missing kinds to `groupversion_info`
  api/v1/groupversion_info.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#5396 feat: check the number of spec.schedule fields
  api/v1/scheduledbackup_funcs_test.go
  api/v1/scheduledbackup_webhook.go
  api/v1/scheduledbackup_webhook_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6422 docs: fix genref config
  docs/config.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/samples/cluster-example-with-backup-scaleway.yaml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6425 ci: stop testing Postgres 12
  .github/pg_versions.json
  .github/postgres-versions-update.py
Labels: ok to merge :ok_hand:, no-issue, do not backport

#6426 chore: remove ExternalClusterList type
  .wordlist-en-custom.txt
  api/v1/cluster_funcs.go
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  docs/config.yaml
  docs/src/cloudnative-pg.v1.md
  internal/cmd/manager/walrestore/cmd.go
  internal/controller/cluster_controller.go
  internal/management/controller/subscription_controller_test.go
Labels: ok to merge :ok_hand:, chore, do not backport

#6431 chore: remove PluginConfigurationList type
  .wordlist-en-custom.txt
  api/v1/cluster_funcs.go
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  docs/config.yaml
  docs/src/cloudnative-pg.v1.md
  internal/cmd/manager/walrestore/cmd.go
  internal/controller/backup_controller.go
  internal/controller/cluster_controller.go
  pkg/management/postgres/archiver/archiver.go
  pkg/management/postgres/webserver/plugin_backup.go
Labels: ok to merge :ok_hand:, chore, backport-requested :arrow_backward:, release-1.24

#6424 docs: Release notes for 1.25.0, 1.24.2, 1.23.6
  .wordlist-en-custom.txt
  docs/src/backup.md
  docs/src/preview_version.md
  docs/src/recovery.md
  docs/src/release_notes.md
  docs/src/release_notes/v1.25.md
  docs/src/supported_releases.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6438 docs: Release notes for 1.24.2 and 1.23.6
  docs/src/release_notes/v1.23.md
  docs/src/release_notes/v1.24.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24

#6442 docs: upgrade info to 1.25.0
  docs/src/installation_upgrade.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6445 chore: update issue templates and backport & CI/CD workflows
  .github/ISSUE_TEMPLATE/bug.yml
  .github/renovate.json5
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  contribute/release_procedure.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24, release-1.25

#6455 test(e2e): raise `AssertClusterStandbysAreStreaming` timeout
  tests/e2e/asserts_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/fencing_test.go
  tests/e2e/pg_data_corruption_test.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25
