Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-03, with the labels that each got.

#3937 fix: use JSON patch instead of JSON Merge patches
  api/v1/cluster_plugins.go
  internal/cmd/manager/walarchive/cmd.go
  internal/cmd/manager/walrestore/cmd.go
  internal/cnpi/plugin/client/cluster.go
  internal/cnpi/plugin/client/lifecycle.go
  internal/cnpi/plugin/client/lifecycle_test.go
Labels: ok to merge :ok_hand:, no-issue

#4001 fix: add --force-conflicts options to kubectl apply
  Makefile
  tests/e2e/upgrade_test.go
  tests/utils/upgrade.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4002 chore: update devcontainer to bookworm
  .devcontainer/devcontainer.json
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3711 feat: introduce catalog of operand images
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/clusterimagecatalog_types.go
  api/v1/genericimagecatalog_types.go
  api/v1/groupversion_info.go
  api/v1/imagecatalog_funcs.go
  api/v1/imagecatalog_funcs_test.go
  api/v1/imagecatalog_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusterimagecatalogs.yaml
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_imagecatalogs.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/cluster_controller.go
  controllers/cluster_image.go
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
  docs/mkdocs.yml
  docs/src/cloudnative-pg.v1.md
  docs/src/container_images.md
  docs/src/image_catalog.md
  docs/src/operator_capability_levels.md
  docs/src/samples/cluster-example-catalog.yaml
  docs/src/security.md
  internal/management/controller/instance_startup.go
  pkg/management/client.go
  pkg/postgres/version.go
  pkg/postgres/version_test.go
  tests/e2e/rolling_update_test.go
Labels: do not backport

#3997 docs: clarify that the `role` label is deprecated
  docs/src/labels_annotations.md
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22

#3966 chore: improve logging in barman-cloud capability detection
  pkg/management/barman/capabilities/detect.go
Labels: no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4024 chore: remove unneeded restrictions
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3952 feat: support to pass extra options for barman-cloud-backup command
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/backup_barmanobjectstore.md
  docs/src/cloudnative-pg.v1.md
  docs/src/samples/cluster-example-with-backup.yaml
  pkg/management/postgres/backup.go
  pkg/management/postgres/backup_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/fixtures/backup/backup_restore_safety/cluster-with-backup-minio.yaml.template
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-legacy.yaml.template
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio.yaml.template
  tests/utils/logs.go
  tests/utils/logs_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4031 fix: major version detection while running pg_rewind
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:

#4034 fix: fixing documentation
  docs/src/cloudnative-pg.v1.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4018 test(e2e): fix the pipeline after adding image catalog
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
  config/olm-samples/kustomization.yaml
  config/olm-samples/postgresql_v1_clusterimagecatalog.yaml
  config/olm-samples/postgresql_v1_imagecatalog.yaml
  tests/e2e/rolling_update_test.go
Labels: ok to merge :ok_hand:, do not backport

#3992 docs: clarify that `PodSecurityPolicy` is now deprecated
  .wordlist-en-custom.txt
  docs/src/security.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4043 fix: unit tests for `wal_level` configuration
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22

#4044 ci: set golangci-lit timeout to 5m by default
  .github/workflows/continuous-integration.yml
  .golangci.yml
Labels: no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3930 fix: Make sure pvcs have correct value of the label `instanceRole` and 'Role'
  controllers/cluster_controller.go
  pkg/reconciler/instance/metadata.go
  pkg/reconciler/instance/metadata_test.go
  pkg/reconciler/persistentvolumeclaim/metadata.go
  pkg/reconciler/persistentvolumeclaim/reconciler.go
  pkg/reconciler/persistentvolumeclaim/reconciler_test.go
  pkg/reconciler/persistentvolumeclaim/resources_test.go
  pkg/reconciler/persistentvolumeclaim/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3663 fix: check recovery backups/snapshots readiness before cluster bootstrap
  controllers/cluster_create.go
  controllers/cluster_create_test.go
  pkg/reconciler/persistentvolumeclaim/instance.go
  pkg/reconciler/persistentvolumeclaim/storagesource.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4067 chore: go mod tidy
  go.sum
Labels: do not backport

#4055 feat: annotation to disable WAL archiving
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  docs/src/labels_annotations.md
  pkg/management/postgres/configuration.go
  pkg/postgres/configuration.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3973 test(e2e): add coverage for multi-arch in-place update
  cmd/manager/main.go
  internal/cmd/manager/debug/architectures/cmd.go
  internal/cmd/manager/debug/cmd.go
  tests/e2e/architecture_test.go
  tests/utils/operator.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3837 feat: make PDB configurable
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  controllers/cluster_create.go
  controllers/cluster_create_test.go
  docs/src/cloudnative-pg.v1.md
  docs/src/kubernetes_upgrade.md
  tests/e2e/drain_node_test.go
  tests/e2e/fixtures/drain-node/single-node-pdb-disabled.yaml.template
Labels: ok to merge :ok_hand:, ready to test :elephant:, do not backport

#3875 feat: add auto-completion to status command to retrieve clusters names
  cmd/kubectl-cnpg/main.go
  docs/src/kubectl-plugin.md
  internal/cmd/plugin/backup/cmd.go
  internal/cmd/plugin/certificate/cmd.go
  internal/cmd/plugin/fio/cmd.go
  internal/cmd/plugin/hibernate/cmd.go
  internal/cmd/plugin/logs/cluster.go
  internal/cmd/plugin/maintenance/cmd.go
  internal/cmd/plugin/pgadmin/cmd.go
  internal/cmd/plugin/plugin.go
  internal/cmd/plugin/plugin_test.go
  internal/cmd/plugin/psql/cmd.go
  internal/cmd/plugin/reload/cmd.go
  internal/cmd/plugin/report/cluster.go
  internal/cmd/plugin/snapshot/cmd.go
  internal/cmd/plugin/status/cmd.go
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22

#4091 chore: fix unit tests
  internal/cmd/plugin/logs/cluster_test.go
Labels: no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3782 docs(pooler): clarify that `user_search` requires `superuser`
  docs/src/connection_pooling.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4093 Add GKE / Google Cloud to ADOPTERS.md
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22

#4094 docs: fix missing date in GKE adoption
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22

#3947 fix: pgbasebackup cluster join wal_sender_timeout configuration
  internal/cmd/manager/instance/pgbasebackup/cmd.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4080 fix: use fully-qualified objects in pooler integration queries
  api/v1/pooler_types.go
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  controllers/pooler_controller_test.go
  docs/src/cloudnative-pg.v1.md
  docs/src/connection_pooling.md
  docs/src/samples/pooler-basic-auth.yaml
  internal/management/controller/instance_controller.go
  tests/e2e/fixtures/pgbouncer/pgbouncer-pooler-basic-auth-ro.yaml
  tests/e2e/fixtures/pgbouncer/pgbouncer-pooler-basic-auth-rw.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3970 fix: cluster phase change should not interrupt the hibernation processing
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  pkg/reconciler/hibernation/status.go
  pkg/reconciler/hibernation/status_test.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4039 feat: publish the OLM bundles in the artifacts directory
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22

#3686 feat: allow configuration of certificate duration and expiring check time
  docs/src/operator_conf.md
  docs/src/ssl_connections.md
  internal/configuration/configuration.go
  pkg/certs/certs.go
  pkg/certs/certs_test.go
  pkg/configparser/configparser.go
  pkg/configparser/configparser_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3990 fix: add the missing clusterPermissions to OLM deployment
  config/olm-manifests/kustomization.yaml
  config/olm-rbac/kustomization.yaml
  config/olm-rbac/role_binding_global.yaml
  config/olm-rbac/role_global.yaml
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22

#4029 feat: add another version of OpenShift to the list
  .github/openshift_versions.json
  Makefile
  hack/install-config.yaml.template
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4052 feat(plugin): add `subscription` and `publication` command groups
  cmd/kubectl-cnpg/main.go
  docs/src/index.md
  docs/src/kubectl-plugin.md
  docs/src/samples/cluster-example-logical-destination.yaml
  docs/src/samples/cluster-example-logical-source.yaml
  internal/cmd/plugin/logical/database.go
  internal/cmd/plugin/logical/doc.go
  internal/cmd/plugin/logical/externalcluster.go
  internal/cmd/plugin/logical/psql.go
  internal/cmd/plugin/logical/publication/cmd.go
  internal/cmd/plugin/logical/publication/create/cmd.go
  internal/cmd/plugin/logical/publication/create/doc.go
  internal/cmd/plugin/logical/publication/create/publication.go
  internal/cmd/plugin/logical/publication/create/publication_test.go
  internal/cmd/plugin/logical/publication/create/suite_test.go
  internal/cmd/plugin/logical/publication/doc.go
  internal/cmd/plugin/logical/publication/drop/cmd.go
  internal/cmd/plugin/logical/publication/drop/doc.go
  internal/cmd/plugin/logical/subscription/cmd.go
  internal/cmd/plugin/logical/subscription/create/cmd.go
  internal/cmd/plugin/logical/subscription/create/doc.go
  internal/cmd/plugin/logical/subscription/create/subscription.go
  internal/cmd/plugin/logical/subscription/doc.go
  internal/cmd/plugin/logical/subscription/drop/cmd.go
  internal/cmd/plugin/logical/subscription/drop/doc.go
  internal/cmd/plugin/logical/subscription/syncsequences/cmd.go
  internal/cmd/plugin/logical/subscription/syncsequences/doc.go
  internal/cmd/plugin/logical/subscription/syncsequences/get.go
  internal/cmd/plugin/logical/subscription/syncsequences/update.go
  internal/cmd/plugin/psql/cmd.go
  internal/cmd/plugin/psql/psql.go
  internal/cmd/plugin/psql/psql_test.go
  pkg/management/external/external.go
  pkg/management/external/utils.go
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22

#4099 docs: Release notes for 1.22.2 and 1.21.4
  .wordlist-en-custom.txt
  docs/src/release_notes/v1.21.md
  docs/src/release_notes/v1.22.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, do not backport

#4104 fix(docs): typo in recovery documentation
  docs/src/recovery.md
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22

#4108 ci: wrong field `naem` instead of name
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22

#4114 fix(docs): uncomment section about `--server-side` in upgrades
  docs/src/installation_upgrade.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#3846 chore: use cluster reference while creating instance volumes
  pkg/specs/jobs.go
  pkg/specs/pods.go
  pkg/specs/volumes.go
  pkg/specs/volumes_test.go
Labels: no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3849 test: add basic test coverage for offline snapshot executor
  pkg/reconciler/backup/volumesnapshot/offline.go
  pkg/reconciler/backup/volumesnapshot/offline_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4117 chore: enable unit tests on Kubernetes 1.29
  .github/k8s_versions_scope.json
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4054 chore: update the pyroscope version
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4130 chore: update K8s and CNPG versions in issue templates
  .github/ISSUE_TEMPLATE/bug.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3959 test(E2E): Use only one MinIO service for all the tests
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/commons_test.go
  tests/e2e/fixtures/backup/backup_restore_safety/external-clusters-minio-2.yaml.template
  tests/e2e/fixtures/backup/backup_restore_safety/external-clusters-minio-3.yaml.template
  tests/e2e/fixtures/backup/backup_restore_safety/external-clusters-minio-4.yaml.template
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-custom-servername.yaml.template
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-primary.yaml.template
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-standby.yaml.template
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-with-wal-max-parallel.yaml.template
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio.yaml.template
  tests/e2e/fixtures/backup/recovery_external_clusters/external-clusters-minio-03.yaml.template
  tests/e2e/fixtures/backup/recovery_external_clusters/external-clusters-minio-replica-04.yaml.template
  tests/e2e/fixtures/backup/recovery_external_clusters/source-cluster-minio-01.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-archive-mode-always.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-from-backup.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-from-snapshot.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-src-with-backup.yaml.template
  tests/e2e/fixtures/tablespaces/cluster-volume-snapshot-tablespaces-pitr.yaml.template
  tests/e2e/fixtures/tablespaces/cluster-volume-snapshot-tablespaces.yaml.template
  tests/e2e/fixtures/tablespaces/cluster-with-tablespaces.yaml.template
  tests/e2e/fixtures/upgrade/cluster1.yaml.template
  tests/e2e/fixtures/upgrade/cluster2.yaml.template
  tests/e2e/fixtures/volume_snapshot/cluster-pvc-hot-restore.yaml.template
  tests/e2e/fixtures/volume_snapshot/cluster-pvc-hot-snapshot.yaml.template
  tests/e2e/fixtures/volume_snapshot/cluster-pvc-snapshot-restore.yaml.template
  tests/e2e/fixtures/volume_snapshot/cluster-pvc-snapshot.yaml.template
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/suite_test.go
  tests/e2e/tablespaces_test.go
  tests/e2e/upgrade_test.go
  tests/e2e/volume_snapshot_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/utils/backup.go
  tests/utils/commons.go
  tests/utils/minio.go
  tests/utils/pod.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4146 test: fix backup and restore e2e test case failure
  tests/e2e/asserts_test.go
  tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-legacy.yaml.template
  tests/e2e/fixtures/upgrade/cluster1.yaml.template
  tests/e2e/fixtures/upgrade/cluster2.yaml.template
  tests/e2e/fixtures/upgrade/scheduled-backup.yaml
  tests/e2e/upgrade_test.go
  tests/e2e/volume_snapshot_test.go
  tests/utils/minio.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4154 Updated documentation to point to the new Grafana Repository
  docs/src/images/grafana-local.png
  docs/src/monitoring.md
  docs/src/quickstart.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4141 fix: ensure pods with no ownership are deleted during cluster restore
  controllers/cluster_controller.go
  controllers/cluster_restore.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#4178 chores: add infrastructure feature annotations to olm bundle
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4184 chore: replace deprecated configuration for golangci-lint
  .golangci.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22

#4162 ci: fix the publish of OLM bundles
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22
