Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-09, with the labels that each got.

#5399 fix: remove `LoadClusterUnsafe`
  internal/management/cache/cache.go
  internal/management/cache/client/client.go
  internal/management/controller/cache.go
  pkg/management/postgres/webserver/metricserver/pg_collector.go
  pkg/management/postgres/webserver/metricserver/pg_collector_test.go
  pkg/management/postgres/webserver/metricserver/wal.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5431 test: remove redundant test for cobra library functionality
  internal/cmd/plugin/logs/cluster_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5340 fix: wrong type in 'exclude-files' field in golangci.yml configuration
  .golangci.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5407 fix: prioritize full rollout over inplace restarts
  internal/controller/cluster_upgrade.go
  internal/controller/cluster_upgrade_test.go
  tests/e2e/replica_mode_cluster_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5414 chore(lint): use coopyloopvar instead of exportloopref
  .golangci.yml
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  internal/controller/cluster_controller.go
  internal/management/controller/tablespaces/reconciler.go
  internal/management/controller/tablespaces/tablespaces.go
  pkg/management/barman/backupdelete.go
  pkg/reconciler/persistentvolumeclaim/calculator.go
  tests/e2e/asserts_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/tablespaces_test.go
  tests/e2e/upgrade_test.go
  tests/utils/openshift.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5437 test(e2e): ensure AssertSwitchoverWithHistory() waits for cluster readiness
  tests/e2e/asserts_test.go
  tests/e2e/replica_mode_cluster_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5429 fix: avoid skipping log lines longer than 64k
  internal/cmd/manager/pgbouncer/run/log.go
  pkg/fileutils/fileutils.go
  pkg/management/execlog/execlog.go
  pkg/management/postgres/logpipe/linelogpipe.go
  pkg/utils/logs/logs.go
  tests/e2e/suite_test.go
  tests/utils/namespace.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5447 chore(goreleaser): change deprecated variable in GoReleaser template
  .goreleaser.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5379 fix: ensure orphan services are reconciled after restoring a cluster
  internal/controller/cluster_restore.go
  internal/controller/cluster_restore_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5430 test(e2e): add tests for metrics with TLS enabled
  tests/e2e/asserts_test.go
  tests/e2e/config_support_test.go
  tests/e2e/fixtures/metrics/cluster-metrics-tls.yaml.template
  tests/e2e/metrics_test.go
  tests/e2e/pgbouncer_metrics_test.go
  tests/utils/proxy.go
  tests/utils/yaml.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24

#5075 test(e2e): add stern-based watcher for capturing pod logs
  .github/workflows/continuous-delivery.yml
  .gitignore
  go.mod
  go.sum
  tests/e2e/affinity_test.go
  tests/e2e/apparmor_test.go
  tests/e2e/architecture_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/certificates_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/cluster_monolithic_test.go
  tests/e2e/cluster_setup_test.go
  tests/e2e/config_support_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/connection_test.go
  tests/e2e/declarative_hibernation_test.go
  tests/e2e/disk_space_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/eviction_test.go
  tests/e2e/failover_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fencing_test.go
  tests/e2e/hibernation_test.go
  tests/e2e/initdb_test.go
  tests/e2e/logs_test.go
  tests/e2e/managed_roles_test.go
  tests/e2e/managed_services_test.go
  tests/e2e/metrics_test.go
  tests/e2e/monitoring_test.go
  tests/e2e/nodeselector_test.go
  tests/e2e/openshift_upgrade_test.go
  tests/e2e/operator_ha_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/pg_basebackup_test.go
  tests/e2e/pg_data_corruption_test.go
  tests/e2e/pg_wal_volume_test.go
  tests/e2e/pgbouncer_metrics_test.go
  tests/e2e/pgbouncer_test.go
  tests/e2e/pgbouncer_types_test.go
  tests/e2e/pvc_deletion_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/replication_slot_test.go
  tests/e2e/rolling_update_test.go
  tests/e2e/scaling_test.go
  tests/e2e/storage_expansion_test.go
  tests/e2e/suite_test.go
  tests/e2e/switchover_test.go
  tests/e2e/syncreplicas_test.go
  tests/e2e/tablespaces_test.go
  tests/e2e/tolerations_test.go
  tests/e2e/update_user_test.go
  tests/e2e/upgrade_test.go
  tests/e2e/volume_snapshot_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/e2e/webhook_test.go
  tests/utils/environment.go
  tests/utils/namespace.go
  tests/utils/sternmultitailer/cluster_logs.go
  tests/utils/sternmultitailer/doc.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5441 chore: add E2E test backup tools to Renovate
  .github/renovate.json5
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5459 chore(ci): Avoid goreleaser-action warning
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5418 feat: predefined cnpg-i plugins
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/operator_conf.md
  internal/cmd/manager/walarchive/cmd.go
  internal/cmd/manager/walrestore/cmd.go
  internal/configuration/configuration.go
  internal/configuration/configuration_test.go
  internal/controller/backup_controller.go
  internal/controller/cluster_controller.go
  pkg/management/postgres/webserver/plugin_backup.go
Labels: ok to merge :ok_hand:, do not backport

#5424 fix: possible race in AvailableArchitecture.GetHash() function
  pkg/utils/discovery.go
  pkg/utils/discovery_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5425 test: upgrade tests should not pick RC versions as starting point
  tests/utils/release.go
  tests/utils/release_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5422 chore: improve inplace updates observability
  internal/controller/cluster_upgrade.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5297 test: improve upgrade E2E test traceability
  tests/e2e/upgrade_test.go
  tests/utils/proxy.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5389 fix(instance): increase timeout to get cluster from Kubernetes API server
  docs/src/troubleshooting.md
  internal/cmd/manager/instance/initdb/cmd.go
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/cmd/manager/instance/restore/cmd.go
  internal/cmd/manager/instance/restoresnapshot/cmd.go
  internal/cmd/manager/instance/run/cmd.go
  pkg/management/client.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5487 fix(PDB): remove replicas PDB when scaling down to 2 instances
  docs/src/kubernetes_upgrade.md
  internal/controller/cluster_create.go
  internal/controller/cluster_create_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5397 fix(webserver): use manager client and recorder
  internal/cmd/manager/instance/run/cmd.go
  pkg/management/postgres/webserver/local.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5496 chore(tests): remove ignore-fails tests
  .github/generate-test-artifacts.py
  .github/report-failed-test.sh
  hack/e2e/filter-failures.jq
  hack/e2e/filter-ignorable-failures.jq
  hack/e2e/run-e2e-local.sh
  hack/e2e/run-e2e.sh
  hack/e2e/test-report.jq
  tests/e2e/ignorefails_test.go
  tests/labels.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5508 fix(docs): typo in before_you_start.md
  docs/src/before_you_start.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5520 docs: clarify certificates automated renewal process
  docs/src/certificates.md
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5325 feat: declarative database management
  .wordlist-en-custom.txt
  PROJECT
  api/v1/database_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_databases.yaml
  config/crd/kustomization.yaml
  config/rbac/database_editor_role.yaml
  config/rbac/database_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/declarative_database_management.md
  docs/src/samples/database-example-fail.yaml
  docs/src/samples/database-example.yaml
  internal/cmd/manager/instance/run/cmd.go
  internal/management/controller/database_controller.go
  pkg/resources/instance/client.go
  pkg/specs/roles.go
  pkg/specs/roles_test.go
  tests/e2e/declarative_database_management_test.go
  tests/e2e/fixtures/declarative_databases/cluster.yaml.template
  tests/e2e/fixtures/declarative_databases/database.yaml.template
  tests/e2e/managed_roles_test.go
Labels: ok to merge :ok_hand:, do not backport

#5528 chore: re-add kubebuilder version to the project
  PROJECT
Labels: ok to merge :ok_hand:, chore, no-issue, do not backport

#5457 tests(e2e): catch operator logs during the tests run
  .github/workflows/continuous-delivery.yml
  .gitignore
  Makefile
  tests/e2e/certificates_test.go
  tests/e2e/cluster_setup_test.go
  tests/e2e/suite_test.go
  tests/e2e/tablespaces_test.go
  tests/utils/cluster.go
  tests/utils/environment.go
  tests/utils/namespace.go
  tests/utils/sternmultitailer/doc.go
  tests/utils/sternmultitailer/multitailer.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5403 fix: remove unused superuser and app secret volumes
  pkg/specs/podspec_diff.go
  pkg/specs/podspec_diff_test.go
  pkg/specs/volumes.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5351 docs: improve release procedure documentation
  contribute/release_procedure.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5550 fix: skip internal ginkgo report entries
  .github/generate-test-artifacts.py
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5549 fix: use `Patch` instead of `Update` during cluster scaledown
  internal/controller/cluster_scale.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5547 chore: refactor database controller to add unit-tests
  internal/management/controller/database_controller.go
  internal/management/controller/database_controller_sql.go
  internal/management/controller/database_controller_sql_test.go
  internal/management/controller/database_controller_test.go
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5536 chore: encapsulate barman delete and backup time logic
  api/v1/cluster_types_test.go
  go.mod
  go.sum
  pkg/management/postgres/backup.go
  pkg/management/postgres/backup_test.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#5529 chore: use barman webhook validator
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  go.mod
  go.sum
Labels: ok to merge :ok_hand:, no-issue, do not backport

#5551 feat(pgadmin4): add support for specifying Docker image with `--image` flag
  internal/cmd/plugin/pgadmin/cmd.go
  internal/cmd/plugin/pgadmin/pgadmin.go
  internal/cmd/plugin/pgadmin/pgadmin_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5558 fix: add the missing CRD examples for OLM build
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
  config/olm-samples/kustomization.yaml
  config/olm-samples/postgresql_v1_database.yaml
Labels: ok to merge :ok_hand:, do not backport

#5566 chore: improve logging messages
  internal/cnpi/plugin/operatorclient/client.go
  internal/controller/cluster_controller.go
  internal/controller/cluster_create.go
  internal/controller/cluster_restore.go
  internal/controller/cluster_scale.go
  internal/controller/cluster_status.go
  pkg/resources/status/phase.go
  pkg/utils/job_conditions.go
  pkg/utils/job_conditions_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5507 ci(release): sign rpm and deb packages
  .github/workflows/release-publish.yml
  .gitignore
  .goreleaser.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5576 test(e2e): prevent VolumeSnapshot E2E to fail because of "tar"
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5517 chore: mute gosec linter in some cases
  internal/controller/cluster_status.go
  pkg/management/postgres/metrics/histogram/histogram.go
  pkg/management/postgres/utils/utils.go
  pkg/management/postgres/utils/version.go
  pkg/postgres/wal.go
  pkg/reconciler/persistentvolumeclaim/status.go
  pkg/specs/poddisruptionbudget.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5539 chore: remove callback from barman `WALArchiver`
  go.mod
  go.sum
  internal/cmd/manager/walarchive/cmd.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5604 docs: add Telnyx to ADOPTERS.md
  ADOPTERS.md
Labels: no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5361 chore: ensure the proper version of OLM tools is being executed
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5594 chore: move PodStatus to API package
  api/v1/base_funcs.go
  api/v1/base_funcs_test.go
  api/v1/base_types.go
  api/v1/base_types_test.go
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  internal/controller/replicas.go
  pkg/postgres/replication/explicit_test.go
  pkg/postgres/replication/legacy.go
  pkg/postgres/replication/legacy_test.go
  pkg/postgres/replication/suite_test.go
  pkg/reconciler/persistentvolumeclaim/status.go
  pkg/utils/pod_conditions.go
  pkg/utils/pod_conditions_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5622 docs: add Alpcot to `ADOPTERS.md`
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5624 docs: Add Cambium to ADOPTERS.md
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5628 docs: improve instructions for `ADOPTERS.md`
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5626 docs: add Mind Informatica to `ADOPTERS.md`
  ADOPTERS.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5631 docs: fix latest minor snapshot installation instructions
  docs/src/installation_upgrade.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.24

#5623 Add GEICO Tech to ADOPTERS.md
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5634 chore: remove image catalog interface from API
  api/v1/clusterimagecatalog_types.go
  api/v1/genericimagecatalog_iface.go
  api/v1/imagecatalog_types.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.23, release-1.24

#5559 fix: use patch while setting the new primary instance
  internal/controller/cluster_status.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5639 chore(refactor): isolate API types
  api/v1/backup_funcs.go
  api/v1/backup_funcs_test.go
  api/v1/backup_types.go
  api/v1/cluster_conditions.go
  api/v1/cluster_funcs.go
  api/v1/cluster_funcs_test.go
  api/v1/cluster_types.go
  api/v1/pooler_funcs.go
  api/v1/pooler_funcs_test.go
  api/v1/pooler_types.go
  api/v1/scheduledbackup_funcs.go
  api/v1/scheduledbackup_funcs_test.go
  api/v1/scheduledbackup_types.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#5650 fix(docs): broken disk-full link
  docs/src/instance_manager.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5391 feat: spread Pod rollout
  api/v1/cluster_types.go
  docs/src/installation_upgrade.md
  docs/src/operator_capability_levels.md
  docs/src/operator_conf.md
  internal/configuration/configuration.go
  internal/configuration/configuration_test.go
  internal/controller/cluster_controller.go
  internal/controller/cluster_upgrade.go
  internal/controller/cluster_upgrade_test.go
  internal/controller/rollout/doc.go
  internal/controller/rollout/rollout.go
  internal/controller/rollout/rollout_test.go
  internal/controller/rollout/suite_test.go
  tests/e2e/fixtures/configmap-support/configmap.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5570 fix(docs): example `xid_age` alert
  docs/src/samples/monitoring/alerts.yaml
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5226 fix(docs): increase `xid_age` alerting limit
  docs/src/samples/monitoring/prometheusrule.yaml
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23

#5641 chore: add names to controllers
  internal/cmd/manager/instance/run/cmd.go
  internal/controller/backup_controller.go
  internal/controller/cluster_controller.go
  internal/controller/plugin_controller.go
  internal/controller/pooler_controller.go
  internal/controller/scheduledbackup_controller.go
  internal/management/controller/database_controller.go
  internal/management/controller/externalservers/manager.go
  internal/management/controller/tablespaces/manager.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5638 ci: avoid testing deprecated versions of AKS
  .github/workflows/k8s-versions-check.yml
Labels: chore, no-issue

#5555 chore: remove `deleteOldCustomQueriesConfigmap`
  internal/controller/cluster_controller.go
  internal/controller/cluster_create.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5516 feat: enable configuration of `full_page_writes`
  docs/src/postgresql_conf.md
  pkg/postgres/configuration.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24
