Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-08, with the labels that each got.

#5210 fix: synchronous replication self-healing for terminating Pods
  pkg/utils/pod_conditions.go
  pkg/utils/pod_conditions_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5154 fix(CNPG-I): correctly evaluate the resource `Kind` inside `reconcilerHook`
  internal/cnpi/plugin/client/reconciler.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.23

#5301 Fix typo in quickstart.md
  docs/src/quickstart.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23

#5320 chore: fix versions in issue template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: do not backport

#5206 feat: stricter readiness probe for replicas
  internal/management/controller/tablespaces/reconciler.go
  pkg/management/postgres/probes.go
  pkg/management/postgres/readiness/doc.go
  pkg/management/postgres/readiness/readiness.go
  pkg/management/postgres/webserver/remote.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#5318 docs: proposal for standard node labels and taints
  .wordlist-en-custom.txt
  docs/src/architecture.md
  docs/src/before_you_start.md
  docs/src/scheduling.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23

#5332 test: fix regexp used in metrics collector test
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5111 feat: add support for CNPG-I `SetStatusInCluster` capability
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  go.mod
  go.sum
  internal/cnpi/plugin/client/cluster.go
  internal/cnpi/plugin/client/cluster_test.go
  internal/cnpi/plugin/client/contracts.go
  internal/cnpi/plugin/client/lifecycle_test.go
  internal/cnpi/plugin/client/suite_test.go
  internal/controller/cluster_controller.go
  internal/controller/plugins.go
  internal/controller/plugins_test.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#5335 docs: add REWE International to ADOPTERS.md
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23

#5334 fix(docs): correct annotation name for `skipWalArchiving`
  docs/src/labels_annotations.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23

#5298 fix(plugin): delete jobs with `destroy` command
  internal/cmd/plugin/destroy/destroy.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5271 feat(plugin): `--control-plane` option with `install generate`
  docs/src/kubectl-plugin.md
  internal/cmd/plugin/install/generate.go
Labels: enhancement :magic_wand:, do not backport

#5036 docs: considerations on block storage solutions
  docs/src/storage.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23

#5343 ci: use full linter version for testing
  .github/renovate.json5
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5209 fix: drop stale replica cluster connections
  internal/management/controller/instance_controller.go
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-tls.yaml.template
  tests/e2e/replica_mode_cluster_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5347 fix: allow `smartShutdownTimeout` to be set to 0
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5321 docs: general update of docs for 1.24.0 release
  contribute/release_procedure.md
  docs/src/failure_modes.md
  docs/src/installation_upgrade.md
  docs/src/kubectl-plugin.md
  docs/src/monitoring.md
  docs/src/operator_conf.md
  docs/src/preview_version.md
  docs/src/release_notes.md
  docs/src/release_notes/old/v1.22.md
  docs/src/release_notes/v1.23.md
  docs/src/release_notes/v1.24.md
  docs/src/supported_releases.md
  docs/src/troubleshooting.md
Labels: ok to merge :ok_hand:, do not backport

#5353 Added adopter reference for Microsoft Azure
  ADOPTERS.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5357 fix: box in installation document about snapshots
  docs/src/installation_upgrade.md
Labels: no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5355 chore: improve `TryInvokeQuitEndpoint` logging
  internal/management/istio/istio.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5374 docs: add PZU (Poland) to ADOPTERS.md
  ADOPTERS.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5372 fix(plugin): restrict `cnpg destroy` job deletion to the specified namespace
  internal/cmd/plugin/destroy/destroy.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#5378 chore: add branch release-1.24 to: renovate, CI, CD and backport workflows
  .github/renovate.json5
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#5274 feat: improve `PhaseUnknownPlugin`
  api/v1/cluster_types.go
  internal/cnpi/plugin/repository/setup.go
  internal/controller/cluster_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24

#5387 fix(webserver): obtain the cluster from the informer for the`/cache/` endpoint
  pkg/management/postgres/webserver/local.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5376 chore: enable unit tests on Kubernetes 1.31
  .github/k8s_versions_scope.json
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23
