Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-06, with the labels that each got.

#4754 chore: gather spellchecks PRs into one
  .github/renovate.json5
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4564 fix: allow raising replication parameters when restoring a backup
  internal/management/controller/instance_controller.go
  pkg/management/postgres/probes.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/restore_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4735 chore: remove unused systemUID detection
  internal/cmd/manager/controller/controller.go
  pkg/utils/systemid.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4766 chore: remove leftover main.go symlink
  cmd/main.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4753 feat: stop requiring namespace object permissions
  config/olm-rbac/role_global.yaml
  config/rbac/role.yaml
  internal/controller/cluster_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4738 chore: adjust goreleaser deprecated option
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4768 fix: volume snapshot backup random failures
  pkg/management/postgres/webserver/remote.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4780 chore: remove stale example file
  docs/src/samples/cluster-restore-pvc.yaml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4765 fix: avoid to check backup container ID if pod container statuses are missing
  api/v1/backup_types.go
  api/v1/backup_types_test.go
  internal/controller/backup_controller.go
  pkg/utils/pod_conditions.go
  tests/e2e/upgrade_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4788 chore: remove stale comment
  api/v1/cluster_types.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4801 chore: update goreleaser to v2
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
  .goreleaser.yml
  Makefile
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4803 chore: fix goreleaser installation from makefile
  Makefile
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4764 test(feat): Add executed command to error output
  pkg/utils/exec.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4811 fix: ensure HA slots don't hold xmin
  internal/management/controller/slots/infrastructure/postgresmanager.go
  internal/management/controller/slots/infrastructure/postgresmanager_test.go
  internal/management/controller/slots/infrastructure/replicationslot.go
  internal/management/controller/slots/runner/runner.go
  internal/management/controller/slots/runner/runner_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4812 ci: send Ciclops thermometer via slack
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4827 fix(docs): remove any mention to `cnp-bench`
  docs/src/operator_capability_levels.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4817 chore(deps): remove `golang.org/x/exp` dependency
  go.mod
  internal/cmd/plugin/backup/cmd.go
  internal/controller/cluster_create.go
  internal/controller/replicas.go
  pkg/reconciler/persistentvolumeclaim/instance.go
  pkg/specs/pods.go
  pkg/specs/roles.go
  pkg/stringset/stringset.go
  pkg/utils/math.go
  tests/e2e/managed_roles_test.go
  tests/utils/logs.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4744 docs: minor updates to the quickstart
  docs/src/quickstart.md
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4775 feat(plugin): support color control via flags and TTY detection
  cmd/kubectl-cnpg/main.go
  docs/src/kubectl-plugin.md
  go.mod
  internal/cmd/plugin/color.go
  internal/cmd/plugin/color_test.go
Labels: backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4394 fix(pgaudit): support `pgaudit.log_rows`option
  pkg/management/postgres/logpipe/CSVReadWriter.go
  pkg/management/postgres/logpipe/pgaudit.go
  pkg/management/postgres/logpipe/pgaudit_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4832 docs: release notes for 1.23.2, 1.22.4, and 1.21.6 (EOL)
  .github/ISSUE_TEMPLATE/bug.yml
  docs/src/release_notes.md
  docs/src/release_notes/v1.21.md
  docs/src/release_notes/v1.22.md
  docs/src/release_notes/v1.23.md
  docs/src/release_notes/v1.24.md
  docs/src/security.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, do not backport

#4856 chore: remove release 1.21 from backport workflow
  .github/renovate.json5
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4844 ci(fix): create operatorhub.io pr only on latest release
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4845 fix: set PVC default `AccessModes` in the template only when unspecified
  pkg/reconciler/persistentvolumeclaim/build.go
  pkg/reconciler/persistentvolumeclaim/build_test.go
  pkg/resources/persistentvolumeclaim.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.21, release-1.22, release-1.23

#4779 feat: allow metric renaming
  config/manager/default-monitoring.yaml
  docs/src/monitoring.md
  pkg/management/postgres/metrics/collector.go
  pkg/management/postgres/metrics/collector_test.go
  pkg/management/postgres/metrics/mapping_test.go
  pkg/management/postgres/metrics/mappings.go
  pkg/management/postgres/metrics/parser.go
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4886 chore: add scorecard-test image to the renovate updates
  .github/renovate.json5
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4909 chore: add another group to renovate
  .github/renovate.json5
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#4411 feat: introduce controlled switchover of a replica cluster
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/architecture.md
  docs/src/cloudnative-pg.v1.md
  docs/src/index.md
  docs/src/operator_capability_levels.md
  docs/src/replica_cluster.md
  docs/src/samples/dc/cluster-dc-a.yaml
  docs/src/samples/dc/cluster-dc-b.yaml
  docs/src/samples/dc/cluster-test.yaml
  internal/cmd/manager/walarchive/cmd.go
  internal/controller/backup_controller.go
  internal/controller/cluster_controller.go
  internal/controller/cluster_delete_test.go
  internal/controller/cluster_status.go
  internal/controller/cluster_status_test.go
  internal/controller/cluster_upgrade.go
  internal/controller/suite_test.go
  internal/management/controller/instance_controller.go
  internal/management/controller/instance_token.go
  pkg/management/postgres/constants/constants.go
  pkg/management/postgres/webserver/remote.go
  pkg/management/url/url.go
  pkg/promotiontoken/doc.go
  pkg/promotiontoken/promotion_token.go
  pkg/promotiontoken/promotion_token_test.go
  pkg/promotiontoken/suite_test.go
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  pkg/reconciler/replicaclusterswitch/reconciler.go
  pkg/reconciler/replicaclusterswitch/shutdown_wal.go
  pkg/resources/instance/client.go
  pkg/utils/parser.go
  pkg/utils/parser_test.go
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-switchover-restart-1.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-switchover-restart-2.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-switchover-switchover-1.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-switchover-switchover-2.yaml.template
  tests/e2e/replica_mode_cluster_test.go
Labels: ok to merge :ok_hand:

#4913 chore: allow run-e2e-local.sh script to run rolling updates
  hack/e2e/run-e2e-local.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#4912 ci: restrict test artifact download
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#4836 chore: centralize `HTTPClient` creation
  pkg/management/postgres/webserver/backup_client.go
  pkg/resources/client.go
  pkg/resources/instance/client.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#4908 chore: use the PAT token when adding or checking labels
  .github/workflows/backport.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/latest-postgres-version-check.yml
  .github/workflows/public-cloud-k8s-versions-check.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4849 fix: always use `RegisterPhase` to change the phase
  internal/cmd/plugin/promote/promote.go
  internal/cmd/plugin/restart/restart.go
  internal/controller/cluster_status.go
  internal/management/controller/instance_controller.go
  pkg/resources/status/doc.go
  pkg/resources/status/phase.go
Labels: risk :boom:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4915 feat: support TLS for status command
  internal/cmd/manager/instance/status/cmd.go
Labels: ok to merge :ok_hand:, do not backport

#4924 fix(docs): text outside warning box
  docs/src/recovery.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#4898 chore: remove the need of the CustomResourceDefinitions
  config/rbac/role.yaml
  internal/cmd/manager/controller/controller.go
  internal/controller/cluster_controller.go
  pkg/certs/k8s.go
  pkg/certs/k8s_test.go
  tests/utils/webhooks.go
Labels: ok to merge :ok_hand:, do not backport

#4920 fix: prevent concurrent postmaster lifecycle loops
  internal/cmd/manager/instance/run/lifecycle/run.go
  pkg/management/execlog/execlog.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23

#4911 chore(security): removed non required permissions
  config/rbac/role.yaml
  internal/controller/cluster_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4388 feat: add `.spec.replicaCluster.primary` field
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/samples/cluster-replica-tls.yaml
  docs/src/samples/dc/cluster-dc-a.yaml
  docs/src/samples/dc/cluster-dc-b.yaml
  internal/cmd/manager/walrestore/cmd_test.go
  internal/controller/cluster_status.go
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-switchover-restart-1.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-switchover-restart-2.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-switchover-switchover-1.yaml.template
  tests/e2e/fixtures/replica_mode_cluster/cluster-replica-switchover-switchover-2.yaml.template
  tests/e2e/replica_mode_cluster_test.go
Labels: ok to merge :ok_hand:

#4926 test: fix race in operator unavailable e2e
  tests/e2e/operator_unavailable_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4938 fix: wait for postmaster to shut down before restarting
  internal/cmd/manager/instance/run/lifecycle/lifecycle.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4895 fix: ignore ServerName mismatch in internal TLS
  docs/src/certificates.md
  internal/cmd/manager/instance/status/cmd.go
  internal/controller/backup_controller.go
  internal/controller/cluster_controller.go
  pkg/certs/tls.go
  pkg/certs/tls_test.go
Labels: ok to merge :ok_hand:, do not backport

#4769 feat: managed services support
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/common_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
  docs/mkdocs.yml
  docs/src/applications.md
  docs/src/architecture.md
  docs/src/cloudnative-pg.v1.md
  docs/src/expose_pg_services.md
  docs/src/index.md
  docs/src/operator_capability_levels.md
  docs/src/release_notes/v1.24.md
  docs/src/samples.md
  docs/src/samples/cluster-example-managed-services.yaml
  docs/src/service_management.md
  docs/src/use_cases.md
  internal/controller/cluster_controller.go
  internal/controller/cluster_create.go
  internal/controller/cluster_create_test.go
  pkg/servicespec/builder.go
  pkg/servicespec/builder_test.go
  pkg/specs/pgbouncer/services.go
  pkg/specs/services.go
  pkg/specs/services_test.go
  pkg/utils/labels_annotations.go
  tests/e2e/fixtures/managed_services/cluster-managed-services-no-default.yaml.template
  tests/e2e/fixtures/managed_services/cluster-managed-services-rw.yaml.template
  tests/e2e/managed_services_test.go
  tests/utils/timeouts.go
Labels: ok to merge :ok_hand:, do not backport

#4892 fix: improve error handling in `EnsureDirectoryExists` function
  pkg/fileutils/fileutils.go
  pkg/fileutils/fileutils_test.go
  pkg/management/postgres/instance_test.go
  pkg/management/postgres/logpipe/linelogpipe.go
  pkg/management/postgres/logpipe/logpipe.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4948 test: fix replica mode e2e
  tests/e2e/replica_mode_cluster_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.23

#4846 fix: ensure pooler service template can override the default service
  docs/src/connection_pooling.md
  pkg/servicespec/builder.go
  pkg/servicespec/builder_test.go
  pkg/specs/pgbouncer/services.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.23

#4882 fix(plugin): handle errors during the `status` command execution
  internal/cmd/plugin/status/status.go
  internal/plugin/resources/instance.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4943 chore: remove the use of cURL pod in the e2e tests
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/config_support_test.go
  tests/e2e/metrics_test.go
  tests/e2e/pgbouncer_metrics_test.go
  tests/utils/curl.go
  tests/utils/proxy.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4360 feat: allow additionalCommandArgs to be passed to barman-cloud-wal-archive
  api/v1/cluster_types.go
  api/v1/cluster_types_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/backup_barmanobjectstore.md
  docs/src/cloudnative-pg.v1.md
  internal/cmd/manager/walarchive/cmd.go
  internal/cmd/manager/walarchive/cmd_test.go
  internal/cmd/manager/walarchive/suite_test.go
  pkg/management/postgres/backup.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23

#4906 docs: link to CNPG-I in README.md
  README.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23

#4953 test: increase query timeout in replica switchover e2e
  tests/e2e/replica_mode_cluster_test.go
Labels: no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23
