Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-10, with the labels that each got.

#5689 fix: remove `pg_database_size` from status probe
  internal/cmd/plugin/status/status.go
  pkg/management/postgres/probes.go
  pkg/postgres/status.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5533 add Standby (potential sync) to status
  internal/cmd/plugin/status/status.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5684 refactor: use PostgreSQL functions from machinery
  api/v1/cluster_funcs.go
  api/v1/cluster_funcs_test.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  docs/src/supported_releases.md
  go.mod
  go.sum
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/management/controller/instance_startup.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/join.go
  pkg/postgres/configuration.go
  pkg/postgres/configuration_test.go
  pkg/postgres/version.go
  pkg/postgres/version_test.go
  pkg/utils/imagename.go
  pkg/utils/imagename_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/rolling_update_test.go
  tests/utils/environment.go
  tests/utils/version.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5509 chore: add a new way to connect to the clusters from tests
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/cluster_monolithic_test.go
  tests/e2e/cluster_setup_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/connection_test.go
  tests/e2e/declarative_hibernation_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/hibernation_test.go
  tests/e2e/managed_roles_test.go
  tests/e2e/metrics_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/pg_basebackup_test.go
  tests/e2e/pg_data_corruption_test.go
  tests/e2e/pgbouncer_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/suite_test.go
  tests/e2e/tablespaces_test.go
  tests/e2e/update_user_test.go
  tests/e2e/volume_snapshot_test.go
  tests/utils/psql_client.go
  tests/utils/psql_connection.go
  tests/utils/time.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5679 ci: sync api to api repo
  .github/workflows/sync-api.yml
  api/v1/cluster_funcs.go
  api/v1/zz_api_repo_funcs_to_copy.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5697 fix(backup): add `BackupStartingCondition` condition to cluster while using the plugin method
  pkg/management/postgres/backup.go
  pkg/management/postgres/webserver/plugin_backup.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5720 docs: clarify use cases for `pg_basebackup` bootstrap
  .wordlist-en-custom.txt
  docs/src/bootstrap.md
Labels: documentation :book:, ok to merge :ok_hand:

#5726 fix(backup,plugin): keep plugin connection open while running a backup
  api/v1/backup_funcs.go
  pkg/management/postgres/webserver/local.go
  pkg/management/postgres/webserver/plugin_backup.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5573 feat(database): add support for encoding, collate, and locale fields
  .wordlist-en-custom.txt
  api/v1/database_types.go
  config/crd/bases/postgresql.cnpg.io_databases.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/samples/database-example-icu.yaml
  internal/management/controller/database_controller_sql.go
  internal/management/controller/database_controller_sql_test.go
  tests/e2e/declarative_database_management_test.go
  tests/e2e/fixtures/declarative_databases/database.yaml.template
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5630 feat(database): prevent creation of Database objects on reserved PG databases
  api/v1/database_types.go
  config/crd/bases/postgresql.cnpg.io_databases.yaml
Labels: ok to merge :ok_hand:, do not backport

#5728 chore: move stringset to machinery
  api/v1/cluster_funcs.go
  api/v1/cluster_funcs_test.go
  api/v1/cluster_webhook.go
  api/v1/pooler_webhook.go
  go.mod
  go.sum
  internal/cmd/plugin/status/status.go
  pkg/configfile/configfile.go
  pkg/multicache/multinamespaced_cache.go
  pkg/specs/roles.go
  pkg/stringset/stringset.go
  pkg/stringset/stringset_test.go
  pkg/stringset/suite_test.go
  pkg/utils/fencing.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5712 docs: provide guidelines for commercial support
  README.md
  SUPPORT.md
  docs/mkdocs.yml
  docs/src/commercial_support.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5724 docs: mention OpenShift certified operator by EDB
  docs/src/installation_upgrade.md
  docs/src/supported_releases.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5727 chore: move time management functions to machinery
  api/v1/cluster_funcs.go
  go.mod
  go.sum
  internal/cmd/plugin/backup/cmd.go
  internal/cmd/plugin/promote/promote.go
  internal/cmd/plugin/reload/reload.go
  internal/controller/cluster_status.go
  internal/controller/replicas.go
  internal/controller/scheduledbackup_controller.go
  internal/management/controller/instance_controller.go
  internal/management/controller/instance_startup.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/webserver/plugin_backup.go
  pkg/utils/strings.go
  pkg/utils/time.go
  pkg/utils/time_test.go
  tests/e2e/tablespaces_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5685 refactor: use getters for main fields in postgres.Instance
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/run/cmd.go
  internal/management/controller/cache.go
  internal/management/controller/database_controller_test.go
  internal/management/controller/externalservers/manager.go
  internal/management/controller/instance_controller.go
  internal/management/controller/instance_startup.go
  internal/management/controller/manager.go
  internal/management/controller/roles/runnable.go
  internal/management/controller/roles/runnable_test.go
  internal/management/controller/slots/runner/runner.go
  internal/management/controller/tablespaces/controller_test.go
  internal/management/controller/tablespaces/manager.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/instance_replica.go
  pkg/management/postgres/probes.go
  pkg/management/postgres/probes_test.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/webserver/local.go
  pkg/management/postgres/webserver/metricserver/pg_collector.go
  pkg/management/postgres/webserver/remote.go
  pkg/management/upgrade/upgrade.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5574 chore: abort certificate creation upon fatal error detection
  internal/controller/cluster_pki.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5596 fix(database): remove 'deleteDatabase' finalizer from orphan Database CRD
  internal/controller/cluster_controller.go
  internal/controller/finalizers_delete.go
  internal/controller/finalizers_delete_test.go
  internal/management/controller/database_controller.go
  pkg/utils/finalizers.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5772 fix(database): SetupLogger must be called only once per reconciliation cycle
  internal/management/controller/database_controller_sql.go
Labels: ok to merge :ok_hand:, do not backport

#5711 feat: enforce only one Database object can manage a given PG database
  internal/management/controller/database_controller.go
  internal/management/controller/database_controller_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5775 fix(plugin): avoid jamming JSON logs with `logs` command
  pkg/utils/logs/cluster_logs.go
  pkg/utils/logs/cluster_logs_test.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5748 docs(fix): add missing links to APIs machinery and barman-cloud
  docs/config.yaml
  docs/src/cloudnative-pg.v1.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5745 feat(database): add support for PG17 builtin_locale
  api/v1/database_types.go
  config/crd/bases/postgresql.cnpg.io_databases.yaml
  docs/src/cloudnative-pg.v1.md
  internal/management/controller/database_controller_sql.go
  internal/management/controller/database_controller_sql_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5651 fix(cnpg-i): ensure instance manager invokes only the available plugins
  go.mod
  go.sum
  internal/cmd/manager/controller/controller.go
  internal/cmd/manager/walarchive/cmd.go
  internal/cmd/manager/walrestore/cmd.go
  internal/cnpi/plugin/repository/setup.go
  pkg/management/postgres/webserver/plugin_backup.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24

#5765 feat(plugin): compact output of `status` command
  docs/src/kubectl-plugin.md
  internal/cmd/plugin/status/cmd.go
  internal/cmd/plugin/status/status.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5800 fix(plugin): ensure pgadmin4 has a writable home directory
  internal/cmd/plugin/pgadmin/pgadmin.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5814 chore: switch to dl.k8s.io on the E2E tests
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5763 ci: fix the registry-clean workflow
  .github/workflows/registry-clean.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5783 chore(logging): avoid creating multiple loggers
  api/v1/cluster_funcs.go
  cmd/manager/main.go
  docs/src/logging.md
  internal/cmd/manager/backup/cmd.go
  internal/cmd/manager/bootstrap/cmd.go
  internal/cmd/manager/debug/architectures/cmd.go
  internal/cmd/manager/instance/initdb/cmd.go
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/cmd/manager/instance/restore/cmd.go
  internal/cmd/manager/instance/restoresnapshot/cmd.go
  internal/cmd/manager/instance/run/cmd.go
  internal/cmd/manager/instance/run/lifecycle/run.go
  internal/cmd/manager/instance/status/cmd.go
  internal/cmd/manager/pgbouncer/run/cmd.go
  internal/cmd/manager/show/walarchivequeue/cmd.go
  internal/cmd/manager/walarchive/cmd.go
  internal/cmd/manager/walrestore/cmd.go
  internal/controller/cluster_pki.go
  internal/controller/cluster_status.go
  internal/management/controller/cache.go
  internal/management/controller/database_controller.go
  internal/management/controller/instance_controller.go
  internal/pgbouncer/management/controller/manager.go
  internal/pgbouncer/management/controller/refresh.go
  internal/pgbouncer/management/controller/refresh_test.go
  pkg/management/pgbouncer/metricsserver/lists.go
  pkg/management/pgbouncer/metricsserver/metricsserver.go
  pkg/management/pgbouncer/metricsserver/metricsserver_test.go
  pkg/management/pgbouncer/metricsserver/pgbouncer_collector.go
  pkg/management/pgbouncer/metricsserver/pools.go
  pkg/management/pgbouncer/metricsserver/pools_test.go
  pkg/management/pgbouncer/metricsserver/stats.go
  pkg/management/pgbouncer/metricsserver/stats_test.go
  pkg/management/postgres/backup.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/join.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/webserver/webserver.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5801 Fix typo in architecture.md
  docs/src/architecture.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5788 fix(failover): prevent double failover in case of lost connectivity
  internal/controller/cluster_controller.go
  pkg/postgres/status.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5503 fix: define a `TMPDIR` environment
  internal/cmd/manager/instance/cmd.go
  pkg/postgres/configuration.go
  pkg/specs/pods.go
  pkg/specs/pods_test.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5794 chore: remove code to support PostgreSQL 11
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  docs/src/replication.md
  docs/src/ssl_connections.md
  pkg/management/postgres/configuration.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5790 docs: refactor logging page, mentioning `stern`
  docs/src/logging.md
  docs/src/operator_conf.md
  docs/src/troubleshooting.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5796 chore(plugin): organise plugin commands into groups
  cmd/kubectl-cnpg/main.go
  internal/cmd/plugin/backup/cmd.go
  internal/cmd/plugin/certificate/cmd.go
  internal/cmd/plugin/color.go
  internal/cmd/plugin/destroy/cmd.go
  internal/cmd/plugin/fence/cmd.go
  internal/cmd/plugin/fio/cmd.go
  internal/cmd/plugin/hibernate/cmd.go
  internal/cmd/plugin/install/cmd.go
  internal/cmd/plugin/logical/publication/cmd.go
  internal/cmd/plugin/logical/subscription/cmd.go
  internal/cmd/plugin/logs/cmd.go
  internal/cmd/plugin/maintenance/cmd.go
  internal/cmd/plugin/pgadmin/cmd.go
  internal/cmd/plugin/pgbench/cmd.go
  internal/cmd/plugin/plugin.go
  internal/cmd/plugin/promote/cmd.go
  internal/cmd/plugin/psql/cmd.go
  internal/cmd/plugin/reload/cmd.go
  internal/cmd/plugin/report/cmd.go
  internal/cmd/plugin/restart/cmd.go
  internal/cmd/plugin/snapshot/cmd.go
  internal/cmd/plugin/status/cmd.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5833 chore: avoid uselessly patching the ContinuousArchivingSuccess condition
  pkg/conditions/conditions.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5826 fix(plugin): collect sidecars' log from `kubectl cnpg logs cluster`
  pkg/utils/logs/cluster_logs.go
  pkg/utils/logs/cluster_logs_test.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5838 test(e2e): workaround for pod rollout
  tests/e2e/upgrade_test.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5831 fix: preserve `synchronous_standby_names` when no replica is reachable
  docs/src/samples/cluster-example-syncreplicas-explicit.yaml
  docs/src/samples/cluster-example-syncreplicas-legacy.yaml
  pkg/postgres/replication/explicit.go
  pkg/postgres/replication/explicit_test.go
  pkg/postgres/replication/suite_test.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24

#5768 docs: release notes for 1.24.1 and 1.23.5
  .wordlist-en-custom.txt
  docs/src/container_images.md
  docs/src/index.md
  docs/src/release_notes/v1.23.md
  docs/src/release_notes/v1.24.md
  docs/src/supported_releases.md
Labels: backport-requested :arrow_backward:, release-1.24

#5857 docs: move v1.21 to old releases (1.22)
  docs/src/release_notes.md
  docs/src/release_notes/old/v1.20.md
  docs/src/release_notes/old/v1.21.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue

#5858 docs: move v1.21 to old releases (1.23)
  docs/src/release_notes/old/v1.20.md
  docs/src/release_notes/old/v1.21.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue

#5862 fix(docs): update header for 1.24 upgrade procedure
  docs/src/installation_upgrade.md
Labels: backport-requested :arrow_backward:, release-1.24

#5875 fix(tests): missing comma and extra comma in gke and kind json files
  .github/gke_versions.json
  .github/kind_versions.json
Labels: ok to merge :ok_hand:

#5854 test(e2e): prevent namespace deletion timeout
  tests/utils/namespace.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24, E2E tests

#5879 ci: collect apiserver audit logs
  .github/workflows/continuous-delivery.yml
  hack/e2e/audit-policy.yaml
  hack/e2e/run-e2e-kind.sh
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24, E2E tests

#5759 test(e2e): refactor assertions to create, insert and validate data
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/cluster_monolithic_test.go
  tests/e2e/cluster_setup_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/declarative_hibernation_test.go
  tests/e2e/disk_space_test.go
  tests/e2e/drain_node_test.go
  tests/e2e/failover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fencing_test.go
  tests/e2e/hibernation_test.go
  tests/e2e/managed_roles_test.go
  tests/e2e/metrics_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/pg_basebackup_test.go
  tests/e2e/pg_data_corruption_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/replication_slot_test.go
  tests/e2e/tablespaces_test.go
  tests/e2e/update_user_test.go
  tests/e2e/upgrade_test.go
  tests/e2e/volume_snapshot_test.go
  tests/utils/environment.go
  tests/utils/pod.go
  tests/utils/postgres.go
  tests/utils/psql_connection.go
  tests/utils/replication_slots.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5914 test: replace temp directory handling with GinkgoT().TempDir()
  pkg/executablehash/executablehash_test.go
  pkg/utils/discovery_test.go
  tests/e2e/upgrade_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5850 chore(logging): add logs to `pre` and `post` reconcile hooks
  internal/cnpi/plugin/client/contracts.go
  internal/cnpi/plugin/client/reconciler.go
  internal/controller/cluster_controller.go
Labels: ok to merge :ok_hand:, do not backport

#5735 chore(tests): split backup tests into file per backend
  hack/setup-cluster.sh
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_azure_test.go
  tests/e2e/backup_restore_azurite_test.go
  tests/e2e/backup_restore_minio_test.go
  tests/e2e/backup_restore_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/suite_test.go
  tests/e2e/tablespaces_test.go
  tests/e2e/upgrade_test.go
  tests/e2e/volume_snapshot_test.go
  tests/e2e/wal_restore_parallel_test.go
  tests/utils/azurite.go
  tests/utils/backup.go
  tests/utils/minio/minio.go
  tests/utils/secrets.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5781 test: remove redundant log capture in tablespace tests
  tests/e2e/tablespaces_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5931 fix(plugin): handle multiple containers in `kubectl cnpg logs`
  pkg/utils/logs/cluster_logs.go
  pkg/utils/logs/cluster_logs_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5936 test: improve unit tests and add race condition detection
  Makefile
  api/v1/cluster_funcs_test.go
  api/v1/scheduledbackup_funcs_test.go
  internal/cmd/manager/instance/run/suite_test.go
  internal/cmd/manager/walarchive/suite_test.go
  internal/cmd/plugin/logs/cluster_logs_test.go
  internal/cmd/plugin/logs/cluster_test.go
  internal/cmd/plugin/logs/suite_test.go
  internal/cmd/plugin/suite_test.go
  internal/controller/cluster_controller_test.go
  internal/controller/cluster_create_test.go
  internal/controller/cluster_restore_test.go
  internal/controller/cluster_scale_test.go
  internal/controller/pooler_update_test.go
  internal/management/controller/roles/postgres_test.go
  internal/management/controller/roles/reconciler_test.go
  internal/management/controller/slots/reconciler/replicationslot_test.go
  internal/management/controller/slots/runner/runner_test.go
  pkg/certs/certs_test.go
  pkg/certs/k8s_test.go
  pkg/certs/tls_test.go
  pkg/management/postgres/configuration_test.go
  pkg/management/postgres/logicalimport/database_test.go
  pkg/management/postgres/logicalimport/role_test.go
  pkg/management/postgres/logpipe/logpipe_test.go
  pkg/management/postgres/metrics/collector_test.go
  pkg/management/postgres/restore_test.go
  pkg/reconciler/persistentvolumeclaim/reconciler_test.go
  pkg/reconciler/persistentvolumeclaim/resources_test.go
  pkg/resources/retry_test.go
  pkg/utils/discovery_test.go
  pkg/utils/logs/logs_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5903 docs: fix minor issues
  api/v1/backup_types.go
  api/v1/cluster_types.go
  api/v1/common_types.go
  api/v1/database_types.go
  api/v1/pooler_types.go
  api/v1/scheduledbackup_types.go
  docs/config.yaml
  docs/src/backup_barmanobjectstore.md
  docs/src/cloudnative-pg.v1.md
  docs/src/wal_archiving.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5951 docs: add Walkbase to `ADOPTERS.md`
  ADOPTERS.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5749 test(database): increase coverage of corner cases
  internal/management/controller/database_controller_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5750 feat(database): introduce `ensure` field for controlling database presence
  api/v1/database_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_databases.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/declarative_database_management.md
  internal/management/controller/database_controller.go
  internal/management/controller/database_controller_sql.go
  internal/management/controller/database_controller_test.go
  tests/e2e/declarative_database_management_test.go
Labels: ok to merge :ok_hand:, do not backport

#5955 fix(metrics): handle FIRST keyword in synchronousStandbyNames parsing
  pkg/management/postgres/webserver/metricserver/pg_collector.go
  pkg/management/postgres/webserver/metricserver/pg_collector_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5836 fix(plugin): improve plugin errors
  internal/cmd/plugin/hibernate/on.go
  internal/cmd/plugin/logical/database.go
  internal/cmd/plugin/logical/externalcluster.go
  internal/cmd/plugin/logical/subscription/syncsequences/cmd.go
  internal/cmd/plugin/maintenance/maintenance.go
  internal/cmd/plugin/pgbench/cmd.go
  internal/cmd/plugin/promote/promote.go
  internal/cmd/plugin/psql/cmd.go
  internal/cmd/plugin/status/status.go
  pkg/utils/fencing.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5829 docs: add permissions required by kubectl CNPG plugin
  .wordlist-en-custom.txt
  docs/mkdocs.yml
  docs/src/kubectl-plugin.md
  internal/cmd/plugin/report/olm.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5970 fix(docs): properly indent a block in logging page
  docs/src/logging.md
Labels: documentation :book:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5985 fix(webhook): validate the number of `synchronous` replicas
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24

#5878 feat: make data durability configurable for sync replication
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/replication.md
  pkg/postgres/replication/explicit.go
  pkg/postgres/replication/explicit_test.go
  pkg/postgres/replication/legacy.go
  tests/e2e/fixtures/sync_replicas/preferred.yaml.template
  tests/e2e/syncreplicas_test.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:
