Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-11, with the labels that each got.

#6023 fix(plugin): check for empty pod list in "cnpg psql"
  internal/cmd/plugin/psql/psql.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5821 feat: restore job hooks
  .wordlist-en-custom.txt
  api/v1/cluster_funcs.go
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  internal/cmd/manager/instance/restore/cmd.go
  internal/cmd/manager/walrestore/cmd.go
  internal/cnpi/plugin/client/backup.go
  internal/cnpi/plugin/client/contracts.go
  internal/cnpi/plugin/client/restore_job.go
  internal/cnpi/plugin/client/suite_test.go
  internal/cnpi/plugin/connection/connection.go
  internal/cnpi/plugin/connection/unix.go
  internal/controller/cluster_controller.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/webserver/local.go
  pkg/utils/context.go
Labels: ok to merge :ok_hand:, no-issue

#5958 refactor: bring role reconciler Postgres functions in line with other reconcilers
  internal/management/controller/roles/contract.go
  internal/management/controller/roles/postgres.go
  internal/management/controller/roles/postgres_test.go
  internal/management/controller/roles/reconciler.go
  internal/management/controller/roles/reconciler_test.go
  internal/management/controller/roles/runnable.go
  internal/management/controller/roles/runnable_test.go
  internal/management/controller/roles/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6026 docs(kubectl-plugin): update formatting and version
  docs/src/kubectl-plugin.md
  hack/release.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6003 refactor: simplify replication slots, clarify tests
  internal/management/controller/instance_controller.go
  internal/management/controller/slots/infrastructure/contract.go
  internal/management/controller/slots/infrastructure/postgresmanager.go
  internal/management/controller/slots/infrastructure/postgresmanager_test.go
  internal/management/controller/slots/infrastructure/suite_test.go
  internal/management/controller/slots/reconciler/replicationslot.go
  internal/management/controller/slots/reconciler/replicationslot_test.go
  internal/management/controller/slots/runner/runner.go
  internal/management/controller/slots/runner/runner_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6062 fix(test): avoid checking permissions in cloud services
  hack/install-config.yaml.template
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6064 fix: correct transaction code and resolve non deterministic role apply
  internal/management/controller/roles/postgres.go
  internal/management/controller/roles/runnable.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6059 chore(security): improve Snyk scan
  .github/workflows/snyk.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6101 fix(tests): update the way we check the EKS versions
  .github/workflows/k8s-versions-check.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#5635 chore: simplify tablespaces interfaces for testing
  internal/management/controller/tablespaces/actions.go
  internal/management/controller/tablespaces/controller_test.go
  internal/management/controller/tablespaces/infrastructure/contract.go
  internal/management/controller/tablespaces/infrastructure/postgres.go
  internal/management/controller/tablespaces/infrastructure/postgres_test.go
  internal/management/controller/tablespaces/manager.go
  internal/management/controller/tablespaces/reconciler.go
  internal/management/controller/tablespaces/storage.go
  pkg/management/postgres/readiness/readiness.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6000 chore(perf): Use controller-runtime pprof server
  config/manager/env_override.yaml
  internal/cmd/manager/controller/controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6142 Add Novo Nordisk as CloudNativePG adoptors
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6045 feat(plugin): allow "plugin" backup method in kubectl cnpg backup
  internal/cmd/plugin/backup/cmd.go
  internal/cmd/plugin/backup/parameters.go
  internal/cmd/plugin/backup/parameters_test.go
  internal/cmd/plugin/backup/suite_test.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#5647 docs: complete the database feature documentation
  .wordlist-en-custom.txt
  api/v1/cluster_webhook.go
  docs/mkdocs.yml
  docs/src/declarative_database_management.md
  docs/src/declarative_role_management.md
  docs/src/index.md
  docs/src/operator_capability_levels.md
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, do not backport

#6145 docs: add Docaposte to ADOPTERS.md
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6162 docs: add Obmondo to `ADOPTERS.md`
  ADOPTERS.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6141 fix: ensure former primary WALs are flushed before resyncing
  go.mod
  go.sum
  internal/cmd/manager/walarchive/cmd.go
  internal/management/controller/instance_controller.go
  internal/management/controller/instance_startup.go
  pkg/management/postgres/archiver/archiver.go
  pkg/management/postgres/archiver/doc.go
  pkg/management/postgres/constants/constants.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6169 fix: remove spurious log line on walarchive failure
  internal/cmd/manager/walarchive/cmd.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#6147 perf(restore): add informers and local webserver cache
  internal/cmd/manager/instance/restore/cmd.go
  internal/cmd/manager/instance/restore/doc.go
  internal/cmd/manager/instance/restore/restore.go
  internal/cmd/manager/walrestore/cmd.go
  internal/cnpi/plugin/client/contracts.go
  internal/cnpi/plugin/client/wal.go
  pkg/management/client.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#6198 fix(linter): prepare code for golangci-lint 1.62.2
  tests/e2e/asserts_test.go
  tests/e2e/certificates_test.go
  tests/e2e/logs_test.go
  tests/e2e/managed_services_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/rolling_update_test.go
  tests/e2e/storage_expansion_test.go
  tests/e2e/syncreplicas_test.go
  tests/utils/backup.go
  tests/utils/environment.go
  tests/utils/pod.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6202 docs: clarify support for PostgreSQL 17
  docs/src/supported_releases.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24

#6217 docs: update join slack link
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.23, release-1.24
