Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2024-01, with the labels that each got.

#3613 test: enforce backup from primary in upgrade e2e
  tests/e2e/fixtures/upgrade/backup1.yaml
  tests/e2e/fixtures/upgrade/scheduled-backup.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3648 test: add unit test coverage for `cluster_cleanup`
  controllers/cluster_cleanup_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3625 test: add unit tests for volumesnapshot `prepare` method
  pkg/reconciler/backup/volumesnapshot/online_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3662 fix: Check the method ReconcilePods's Result
  controllers/cluster_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3647 fix: correctly compare zero and nil `.spec.projectedVolumeTemplate.sources`
  controllers/cluster_upgrade.go
  controllers/cluster_upgrade_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3622 feat: add OpenShift tests to the CD
  .github/e2e-matrix-generator.py
  .github/e2e_test_timeout.json
  .github/k8s_versions_scope.json
  .github/openshift_versions.json
  .github/workflows/continuous-delivery.yml
  .woke.yaml
  Makefile
  hack/e2e/run-e2e-ocp.sh
  hack/e2e/run-e2e.sh
  hack/install-config.yaml.template
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.21, release-1.22

#3534 feat: configuration of PostgreSQL ident map file
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/postgresql_conf.md
  docs/src/security.md
  internal/management/controller/instance_controller.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/restore.go
  pkg/postgres/configuration.go
  pkg/postgres/configuration_test.go
  tests/e2e/configuration_update_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3690 fix: properly quote comment lines
  pkg/postgres/configuration.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3694 fix(e2e): avoid uploading multiple artifacts with same name in gke,aks,eks
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3685 fix: default values for VolumenSnapshot tests
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3624 test: support upgrade test from the current version
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .woke.yaml
  Makefile
  controllers/cluster_upgrade.go
  hack/e2e/run-e2e.sh
  hack/setup-cluster.sh
  tests/e2e/fixtures/upgrade/.gitignore
  tests/e2e/upgrade_test.go
  tests/utils/namespace.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3668 Use ubi9 base images in addition to ubi8
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
  Dockerfile-ubi9
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3585 feat(pooler): warn and log manual integration required
  api/v1/pooler_types.go
  api/v1/pooler_webhook.go
  controllers/cluster_status.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21

#3692 refactor: centralize the get current Postgres user logic
  pkg/management/postgres/configuration.go
  pkg/management/postgres/ident.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3693 fix: tests tablespaces file from the RunAsUser spec from container
  tests/e2e/tablespaces_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3701 feat: add `pgadmin4` command to `cnpg` plugin
  .wordlist-en-custom.txt
  cmd/kubectl-cnpg/main.go
  docs/src/images/pgadmin4.png
  docs/src/kubectl-plugin.md
  internal/cmd/plugin/pgadmin/cmd.go
  internal/cmd/plugin/pgadmin/doc.go
  internal/cmd/plugin/pgadmin/pgadmin.go
  internal/cmd/plugin/pgadmin/pgadmin_test.go
  internal/cmd/plugin/pgadmin/suite_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3676 k9s plugins.yaml update
  docs/src/kubectl-plugin.md
  docs/src/samples/k9s/plugins.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3678 feat: add ephemeralVolumeSource option to cluster spec.
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  api/v1/cluster_webhook.go
  api/v1/cluster_webhook_test.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/cluster_conf.md
  pkg/specs/volumes.go
  pkg/specs/volumes_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3713 fix: escape reserved characters in pgpass fields (resolves #3712)
  pkg/management/external/internal/pgpass/conninfo.go
  pkg/management/external/internal/pgpass/conninfo_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3703 ci: re-establish cloud providers on scheduled E2Es
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3706 fix: use semantic compare in pod spec drift detection
  pkg/specs/pods_test.go
  pkg/specs/podspec_diff.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3737 docs: fix spelling of --watch-namespace plugin option
  docs/src/installation_upgrade.md
  docs/src/kubectl-plugin.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3728 fix: enforce postgres.auto.conf to rw before run rewind
  internal/management/controller/instance_controller.go
  internal/management/controller/instance_startup.go
  pkg/management/postgres/instance.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3744 ci: fix EKS tests storageclass defaults
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3740 fix: skip deleting ha replicationslot when it is active
  internal/management/controller/slots/reconciler/replicationslot.go
  internal/management/controller/slots/reconciler/replicationslot_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3730 add office hours meeting
  CONTRIBUTING.md
Labels: backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3634 Edits to storage topic and light touch on supported releases
  .wordlist-en-custom.txt
  docs/src/storage.md
  docs/src/supported_releases.md
Labels: documentation :book:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3633 docs: edits to samples and ssl_connections topics
  docs/src/bootstrap.md
  docs/src/failure_modes.md
  docs/src/samples.md
  docs/src/security.md
  docs/src/ssl_connections.md
Labels: documentation :book:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22

#3743 fix: disable WAL archiving during import bootstrap
  docs/src/database_import.md
  docs/src/samples/cluster-import-schema-only-basicauth.yaml
  docs/src/samples/cluster-import-snapshot-basicauth.yaml
  docs/src/samples/cluster-import-snapshot-tls.yaml
  pkg/configfile/configfile.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.20, release-1.21, release-1.22
