Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2025-09, with the labels that each got.

#7826 chore: add usestdlibvars linter
  .golangci.yml
  internal/cmd/manager/backup/cmd.go
  internal/cmd/manager/instance/status/cmd.go
  pkg/management/postgres/webserver/client/remote/backup.go
  pkg/management/postgres/webserver/client/remote/instance.go
Labels: go, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:S, lgtm, release-1.26, release-1.27

#8486 fix(backup): do not check Cluster `spec.backup` if method is `plugin`
  internal/controller/backup_controller.go
  internal/controller/backup_controller_test.go
Labels: bug :bug:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, size:M, lgtm, release-1.27

#8485 fix(webhook): use correct API group in webhook errors
  internal/webhook/v1/backup_webhook.go
  internal/webhook/v1/pooler_webhook.go
Labels: bug :bug:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26, release-1.27

#8506 fix(persistentvolumeclaim): consider WAL-archiver plugins for replica recovery source
  pkg/reconciler/persistentvolumeclaim/storagesource.go
  pkg/reconciler/persistentvolumeclaim/storagesource_test.go
  tests/e2e/volume_snapshot_test.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:M, lgtm, release-1.26, release-1.27

#8543 docs: update LFX Mentorship Program with 2025 term 3
  contribute/lfx-mentorship-program.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.25, size:S, lgtm, release-1.26, release-1.27

#8554 fix(cnpgi,connection): improve retry algorithm
  internal/cnpi/plugin/repository/connection.go
  internal/controller/plugin_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:M, lgtm, release-1.26, release-1.27

#7876 chore(cluster): add support for pprof via `alpha.cnpg.io/enableInstancePprof` annotation
  .wordlist-en-custom.txt
  contribute/e2e_testing_environment/README.md
  docs/src/operator_conf.md
  docs/src/troubleshooting.md
  hack/setup-cluster.sh
  internal/cmd/manager/instance/run/cmd.go
  pkg/specs/pods.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, chore, backport-requested :arrow_backward:, release-1.25, size:L, lgtm, release-1.26, release-1.27

#8606 chore(linter): gofumpt 0.9.1 changes
  internal/configuration/configuration.go
  internal/controller/pooler_controller.go
  pkg/utils/discovery.go
  tests/utils/run/run.go
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.25, size:S, lgtm, release-1.26, release-1.27

#8589 feat(cluster): add `spec.postgresql.synchronous.failoverQuorum` field
  .wordlist-en-custom.txt
  api/v1/cluster_defaults.go
  api/v1/cluster_defaults_test.go
  api/v1/cluster_funcs.go
  api/v1/cluster_funcs_test.go
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/failover.md
  docs/src/samples/cluster-example-syncreplicas-quorum.yaml
  internal/controller/replicas.go
  internal/controller/replicas_quorum.go
  internal/management/controller/instance_sync.go
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:, do not backport, size:L, lgtm

#8670 fix: correct Barman Cloud deprecation warning version
  internal/webhook/v1/cluster_webhook.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, size:XS, lgtm, release-1.26, release-1.27

#8680 fix: allow quorum-based failover with two instances
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, size:S, lgtm, release-1.27
