Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2025-10, with the labels that each got.

#8241 feat(rollout): support changing image and PostgreSQL settings simultaneously
  docs/src/rolling_update.md
  internal/management/controller/instance_controller.go
  internal/management/controller/manager.go
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/fixtures/config_update/primary_update_method/primary-update-restart.yaml.template
  tests/e2e/imagevolume_extensions_test.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:, do not backport, size:XL, lgtm

#8663 fix: wait for app user secret before starting initdb
  pkg/specs/jobs.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:S, lgtm, release-1.26, release-1.27

#8691 docs: add TrueFullstaq to `ADOPTERS.md`
  ADOPTERS.md
Labels: documentation :book:, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26, release-1.27

#8748 fix(docs): clarify default value of `smartShutdownTimeout`
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26, release-1.27

#8178 feat: "unrecoverable" annotation
  docs/src/labels_annotations.md
  internal/controller/cluster_controller.go
  internal/controller/cluster_scale.go
  internal/controller/cluster_unrecoverable.go
  internal/controller/cluster_unrecoverable_test.go
  pkg/utils/labels_annotations.go
  tests/e2e/destroy_instance_test.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:, no-issue, do not backport, E2E tests, size:L, lgtm
