Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2025-08, with the labels that each got.

#8212 docs: list 2025-3 term LFX Mentorships
  contribute/lfx-mentorship-program.md
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26

#8217 docs: add a new k9s shortcut to view the logs in "pretty" format
  docs/src/samples/k9s/plugins.yml
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.25, size:S, lgtm, release-1.26

#8210 chore: `startedAt` vs `started at` in log messages key
  internal/controller/backup_controller.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26

#8254 chore(renovate): create a group for distroless digests images
  .github/renovate.json5
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26

#8236 fix: unblock rollout of former primary Pod when WAL archiving plugin is missing
  api/v1/cluster_types.go
  internal/cmd/manager/instance/run/cmd.go
  internal/cmd/manager/instance/run/lifecycle/run.go
  internal/controller/cluster_controller.go
  internal/controller/cluster_status.go
  internal/management/controller/instance_startup.go
  pkg/concurrency/executed.go
  pkg/management/postgres/archiver/archiver.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.25, size:L, lgtm, release-1.26

#8245 fix: correctly wrap `startBackup` `pg_create_physical_replication_slot` errors
  pkg/management/postgres/webserver/backup_connection.go
Labels: bug :bug:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26

#8265 fix: always consider `WALArchiver` as a valid instance sidecar for metrics
  pkg/management/postgres/metrics/collector.go
Labels: bug :bug:, ok to merge :ok_hand:, no-issue, do not backport, size:S, lgtm

#8304 chore: fix cloudnative-pg grouping test dependencies
  .github/renovate.json5
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26

#8317 docs: add Brella to `ADOPTERS.md`
  ADOPTERS.md
Labels: documentation :book:, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26

#8333 chore: fix azure tests for backup and PITR
  tests/e2e/backup_restore_azure_test.go
  tests/e2e/fixtures/backup/recovery_external_clusters/backup-azure-blob-pitr.yaml
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26, release-1.27

#8400 chore: set `STANDBY_TCP_USER_TIMEOUT` from e2e manifests
  hack/e2e/env_override_customized.yaml.template
Labels: ok to merge :ok_hand:, chore, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26, release-1.27

#8456 chore: ignore shellcheck warnings for SC2329
  hack/e2e/run-e2e-kind.sh
  hack/install-cnpg-plugin.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, release-1.26, release-1.27
