Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2025-07, with the labels that each got.

#7902 fix(probes): avoid liveness probe to timeout when not needed
  pkg/management/postgres/webserver/probes/liveness.go
  tests/e2e/fixtures/self-fencing/cluster-liveness-pinger-disabled.yaml.template
  tests/e2e/fixtures/self-fencing/cluster-liveness-pinger-enabled.yaml.template
  tests/e2e/self_fencing_test.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, size:L, lgtm, release-1.26

#7978 fix(docs): remove version 13 from cluster-example.yaml
  docs/src/samples/cluster-example.yaml
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, size:XS, lgtm, release-1.26

#7845 feat(spec,probes): primary isolation check in the liveness probe
  .wordlist-en-custom.txt
  api/v1/cluster_defaults.go
  api/v1/cluster_defaults_test.go
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/installation_upgrade.md
  docs/src/instance_manager.md
  internal/webhook/v1/cluster_webhook.go
  pkg/management/postgres/webserver/probes/liveness.go
  pkg/management/postgres/webserver/probes/pinger.go
  pkg/management/postgres/webserver/remote.go
  tests/e2e/probes_test.go
Labels: documentation :book:, enhancement :magic_wand:, ok to merge :ok_hand:, do not backport, size:XL, lgtm

#7980 fix(pg_rewind): typo in an error message
  internal/management/controller/instance_startup.go
Labels: chore, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26

#7944 fix(backup,online): fail backup if targetPod becomes unhealthy
  api/v1/backup_funcs.go
  internal/controller/backup_controller.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:M, lgtm, release-1.26

#7987 chore(backup,logging): log the correct namespace value
  pkg/management/postgres/webserver/plugin_backup.go
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26

#7931 feat(replication): add `synchronizeLogicalDecoding` for HA logical slots
  .wordlist-en-custom.txt
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/index.md
  docs/src/logical_replication.md
  docs/src/operator_capability_levels.md
  docs/src/replication.md
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
  pkg/management/postgres/configuration.go
  pkg/postgres/configuration.go
Labels: documentation :book:, enhancement :magic_wand:, ok to merge :ok_hand:, do not backport, size:L, lgtm

#7994 docs(examples): use synchronizeLogicalDecoding in the examples
  docs/src/samples/cluster-example-logical-destination.yaml
  docs/src/samples/cluster-example-logical-source.yaml
Labels: documentation :book:, no-issue, do not backport, size:S, lgtm

#8025 fix(webhooks): clarify rejection of multiple bootstrap methods
  docs/src/bootstrap.md
  internal/webhook/v1/cluster_webhook.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26

#7903 docs: clarify the defaults for microservice imports
  docs/src/database_import.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.25, size:S, lgtm, release-1.26

#7891 fix(postgres,instance): set postgres workers `oom_score_adj`
  docs/src/resource_management.md
  pkg/management/postgres/instance.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.25, size:M, lgtm, release-1.26

#8060 chore: azurite test failing due to API versions mismatch
  tests/utils/backups/azurite.go
Labels: ok to merge :ok_hand:, chore, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26

#8071 fix(webserver): make routines not blocking
  pkg/management/postgres/webserver/webserver.go
Labels: bug :bug:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26

#7922 fix(pooler): apply `resources` to the `bootstrap-controller`
  api/v1/pooler_funcs.go
  internal/controller/pooler_status_test.go
  pkg/podspec/builder.go
  pkg/specs/pgbouncer/deployments.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:M, lgtm, release-1.26

#8082 fix(upgrade): stop testing `max_slot_wal_keep_size`
  docs/src/postgres_upgrades.md
  internal/cmd/manager/instance/upgrade/execute/cmd.go
  tests/e2e/cluster_major_upgrade_test.go
Labels: bug :bug:, documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, size:S, lgtm, release-1.26

#7844 fix(subscriptions): restrict subscription parameter updates to valid PostgreSQL options
  api/v1/subscription_types.go
  config/crd/bases/postgresql.cnpg.io_subscriptions.yaml
  docs/src/cloudnative-pg.v1.md
  internal/management/controller/subscription_controller.go
  internal/management/controller/subscription_controller_sql.go
  internal/management/controller/subscription_controller_sql_test.go
  internal/management/controller/subscription_controller_test.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:L, lgtm, release-1.26

#8064 docs(contributing): clarify instructions for external contributors
  CONTRIBUTING.md
  contribute/README.md
  contribute/e2e_testing_environment/README.md
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.25, size:M, lgtm, release-1.26

#8036 test: support beta versions in major upgrade E2Es
  .github/pg_versions.json
  tests/e2e/cluster_major_upgrade_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, E2E tests, release-1.25, size:L, lgtm, release-1.26

#8088 test(logpipe): improve extra logs test reliability
  pkg/podlogs/cluster_writer_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26

#7988 feat(cluster,status): add `PhaseFailurePlugin` phase
  api/v1/cluster_types.go
  internal/cnpi/plugin/client/backup.go
  internal/cnpi/plugin/client/cluster.go
  internal/cnpi/plugin/client/create.go
  internal/cnpi/plugin/client/errors.go
  internal/cnpi/plugin/client/errors_test.go
  internal/cnpi/plugin/client/lifecycle.go
  internal/cnpi/plugin/client/postgres.go
  internal/cnpi/plugin/client/postgres_test.go
  internal/cnpi/plugin/client/reconciler.go
  internal/cnpi/plugin/client/restore_job.go
  internal/cnpi/plugin/client/wal.go
  internal/controller/cluster_controller.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:, do not backport, size:L, lgtm

#8033 feat(instance): add cnpgi `metrics` capabilities to the instance webserver
  go.mod
  go.sum
  internal/cmd/manager/instance/run/cmd.go
  internal/cnpi/plugin/client/contracts.go
  internal/cnpi/plugin/client/interfaces.go
  internal/cnpi/plugin/client/metrics.go
  internal/cnpi/plugin/client/postgres.go
  internal/cnpi/plugin/client/suite_test.go
  internal/cnpi/plugin/connection/connection.go
  pkg/management/postgres/metrics/collector.go
  pkg/management/postgres/metrics/collector_test.go
  pkg/management/postgres/webserver/metricserver/pg_collector.go
  pkg/management/postgres/webserver/metricserver/pg_collector_test.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:, do not backport, size:XL, lgtm, priority:high

#8108 fix(replica_cluster): correctly detect designated primary while ordering instances
  internal/cmd/plugin/status/status.go
  internal/controller/backup_controller.go
  internal/controller/replicas.go
  internal/plugin/resources/instance.go
  pkg/management/postgres/webserver/client/remote/instance.go
  pkg/postgres/status.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:M, lgtm, release-1.26

#8129 docs: release notes for 1.26.1 and 1.25.3
  .wordlist-en-custom.txt
  docs/src/release_notes/v1.25.md
  docs/src/release_notes/v1.26.md
  docs/src/supported_releases.md
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, size:L, lgtm, release-1.26

#8130 docs: Cilium grammar and yaml fixes
  docs/src/cncf-projects/cilium.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.25, size:L, lgtm, release-1.26

#7801 fix(import): do not create default user and database in monolith mode
  api/v1/cluster_defaults.go
  docs/src/database_import.md
  tests/e2e/cluster_monolithic_test.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.25, size:L, lgtm, release-1.26

#8137 chore: update issue template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26

#8142 test(e2e): fix expected entry count in pg_ident_file_mappings
  tests/e2e/configuration_update_test.go
Labels: ok to merge :ok_hand:, do not backport, E2E tests, size:XS, lgtm

#8127 feat(webhook): add warnings for storage configuration
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:, no-issue, do not backport, size:L, lgtm

#8138 fix(slots): handle context cancellation in `Replicator` `Start`
  internal/management/controller/slots/runner/runner.go
Labels: bug :bug:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26

#8106 docs: release notes for 1.27.0-rc1
  .wordlist-en-custom.txt
  docs/src/installation_upgrade.md
  docs/src/preview_version.md
  docs/src/release_notes.md
  docs/src/release_notes/v1.27.md
  docs/src/supported_releases.md
  hack/check-pr-in-release-branches.sh
Labels: documentation :book:, do not backport, size:L, lgtm

#8173 chore: add missing CRD owned definition to CSV
  .wordlist-en-custom.txt
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
Labels: ok to merge :ok_hand:, chore, no-issue, do not backport, size:S, lgtm

#8171 docs(development_environment): add helm requirement
  contribute/development_environment/README.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26
