Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2025-06, with the labels that each got.

#7640 feat: allow postgres executable name customization
  internal/cmd/manager/instance/run/lifecycle/reaper.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/pidfile_test.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:, do not backport, size:S, lgtm

#7655 test: adjust E2E tests to run with minimal images
  tests/e2e/fixtures/declarative_databases/database.yaml.template
  tests/e2e/fixtures/initdb/cluster-custom-locale.yaml.template
  tests/e2e/initdb_test.go
  tests/e2e/replica_mode_cluster_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, E2E tests, release-1.25, size:S, lgtm, release-1.26

#7770 chore(lint): strict nil check in termination grace period comparison
  pkg/specs/podspec_diff.go
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm, release-1.26

#7754 chore: add MinIO to Renovate
  .github/renovate.json5
  tests/utils/minio/minio.go
Labels: dependencies :twisted_rightwards_arrows:, ok to merge :ok_hand:, chore, backport-requested :arrow_backward:, release-1.22, release-1.25, size:S, lgtm, release-1.26

#7803 docs: provide information about the LFX Mentorship Program
  contribute/lfx-mentorship-program.md
Labels: documentation :book:, backport-requested :arrow_backward:, release-1.22, release-1.25, size:M, lgtm, LFX Mentorship, release-1.26

#7837 docs: add Vera Rubin Observatory to ADOPTERS.md
  ADOPTERS.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26

#7897 chore(typo): fix spelling of ParameterRecoveryMinApplyDelay
  pkg/postgres/configuration.go
  pkg/postgres/configuration_test.go
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.25, size:S, lgtm, release-1.26
