Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2025-05, with the labels that each got.

#7294 docs: add "CNCF Project Integration" section for External Secrets
  .wordlist-en-custom.txt
  docs/mkdocs.yml
  docs/src/cncf-projects/external-secrets.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:L, lgtm

#7471 docs: add Giant Swarm to ADOPTERS.md
  ADOPTERS.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7254 ci(security): implement least privilege for GitHub Workflows
  .github/workflows/backport.yml
  .github/workflows/chatops.yml
  .github/workflows/close-inactive-issues.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/k8s-versions-check.yml
  .github/workflows/latest-postgres-version-check.yml
  .github/workflows/pr_verify_linked_issue.yml
  .github/workflows/refresh-licenses.yml
  .github/workflows/registry-clean.yml
  .github/workflows/release-pr.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-tag.yml
  .github/workflows/require-labels.yml
  .github/workflows/snyk.yml
  .github/workflows/spellcheck.yml
  .github/workflows/sync-api.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:M, lgtm

#7461 test(e2e): do not remove the stern directory on success
  tests/e2e/suite_test.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, E2E tests, release-1.25, size:S, lgtm

#7483 fix: fail fast during WAL archiving on primary demotion
  pkg/management/postgres/wal.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:S, lgtm

#7498 ci(security): implement least privilege for GitHub Workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/registry-clean.yml
  .github/workflows/release-pr.yml
  .github/workflows/snyk.yml
Labels: github_actions, ok to merge :ok_hand:, backport-requested :arrow_backward:, security :police_officer:, release-1.22, release-1.24, release-1.25, size:S, lgtm

#7502 docs: fix missing storage spec in tablespaces definitions
  docs/src/tablespaces.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:S, lgtm

#7507 fix: don't fail on missing wal in plugin wal restore
  internal/cmd/manager/walrestore/cmd.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:S, lgtm

#7496 fix(cnpg-i): avoid timeout in local CNPG-i entrypoints
  internal/cnpi/plugin/connection/connection.go
  internal/cnpi/plugin/connection/remote.go
  internal/cnpi/plugin/connection/unix.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/webserver/local.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24, release-1.25, size:S, lgtm

#7506 fix(kubectl-cnpg): require plugin-name for plugin backups
  internal/cmd/plugin/backup/cmd.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm

#7298 fix(instance_replica): include dbname in primary_conninfo for replication configuration
  pkg/management/postgres/instance.go
  pkg/management/postgres/instance_replica.go
  pkg/management/postgres/wal.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:S, lgtm

#7511 docs(fix): image_catalog major version inconsistencies
  docs/src/image_catalog.md
Labels: documentation :book:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7509 docs: fix value for skipEmptyWalArchiveCheck annotation
  docs/src/labels_annotations.md
Labels: documentation :book:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7501 fix: typo in backup plugin message
  internal/cmd/plugin/backup/cmd.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7534 chore(golangci): migrate to golangci-lint v2
  .github/workflows/continuous-integration.yml
  .golangci.yml
  api/v1/backup_funcs.go
  api/v1/base_funcs.go
  api/v1/cluster_funcs.go
  internal/cmd/manager/walrestore/cmd.go
  internal/cmd/plugin/status/status.go
  internal/cnpi/plugin/mapping.go
  internal/controller/backup_predicates.go
  internal/controller/cluster_controller_test.go
  internal/controller/cluster_create.go
  internal/controller/cluster_create_test.go
  internal/controller/cluster_delete_test.go
  internal/controller/cluster_image.go
  internal/controller/cluster_restore.go
  internal/controller/cluster_upgrade.go
  internal/controller/cluster_upgrade_test.go
  internal/controller/plugin_controller.go
  internal/controller/pooler_update_test.go
  internal/management/controller/database_controller.go
  internal/management/controller/publication_controller.go
  internal/management/controller/roles/postgres.go
  internal/management/controller/subscription_controller.go
  internal/plugin/resources/instance.go
  internal/webhook/v1/cluster_webhook.go
  pkg/certs/certs.go
  pkg/configfile/configfile_test.go
  pkg/management/postgres/logpipe/CSVReadWriter.go
  pkg/management/postgres/logpipe/pgaudit.go
  pkg/management/postgres/webserver/client/remote/instance.go
  pkg/reconciler/hibernation/status_test.go
  pkg/reconciler/instance/metadata.go
  pkg/reconciler/majorupgrade/reconciler.go
  pkg/reconciler/persistentvolumeclaim/metadata.go
  pkg/reconciler/persistentvolumeclaim/status.go
  pkg/reconciler/persistentvolumeclaim/storagesource.go
  pkg/specs/pods.go
  pkg/specs/podspec_diff.go
  pkg/specs/roles.go
  pkg/utils/labels_annotations_test.go
  tests/e2e/apparmor_test.go
  tests/e2e/asserts_test.go
  tests/e2e/nodeselector_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/tablespaces_test.go
  tests/utils/sternmultitailer/multitailer.go
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:L, lgtm

#7410 chore(volumesnapshot): correct `getBackupVolumeSnapshots` parameter typo
  pkg/reconciler/backup/volumesnapshot/resources.go
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7350 docs: update quickstart and monitoring pages with Grafana dashboard
  docs/src/monitoring.md
  docs/src/quickstart.md
Labels: documentation :book:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:L, lgtm

#7546 feat(cluster,status): track latest `Instance` IP
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  internal/controller/cluster_status.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:, no-issue, do not backport, size:S, lgtm

#7545 build: remove deprecated GoReleaser parameters
  .goreleaser.yml
Labels: ok to merge :ok_hand:, chore, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7466 feat(instance): liveness probe isolation checker
  docs/src/instance_manager.md
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
  pkg/certs/tls.go
  pkg/management/postgres/webserver/probes/liveness.go
  pkg/management/postgres/webserver/probes/pinger.go
  pkg/management/postgres/webserver/remote.go
  pkg/management/url/url.go
  pkg/utils/labels_annotations.go
  tests/e2e/fixtures/self-fencing/cluster-self-fencing.yaml.template
  tests/e2e/self_fencing_test.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:, do not backport, size:XL, lgtm

#7500 feat: in-tree barman-cloud support deprecation notice
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
Labels: enhancement :magic_wand:, ok to merge :ok_hand:, do not backport, size:L, lgtm

#7562 ci: fix permissions on release publish workflow
  .github/workflows/release-publish.yml
Labels: github_actions, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7552 chore(ci): add missing permissions to workflow
  .github/workflows/latest-postgres-version-check.yml
Labels: github_actions, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7571 docs: fix release announcement link in preview page
  docs/src/preview_version.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, do not backport, size:XS, lgtm

#7303 test: allow configuring a custom image repository in major upgrade E2Es
  tests/e2e/cluster_major_upgrade_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:L, lgtm

#7588 feat: allow customization of in-place upgrades from a CNPG-I plugin
  internal/cmd/manager/instance/upgrade/execute/cmd.go
Labels: ok to merge :ok_hand:, do not backport, size:M, lgtm

#7470 docs: add OpenBao as OSS alternative to Vault
  .wordlist-en-custom.txt
  docs/src/cncf-projects/external-secrets.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:S, lgtm

#7594 docs: clarify example in distributed topology
  docs/src/replica_cluster.md
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24, release-1.25, size:S, lgtm

#7606 test: enable unit test on 1.33
  .github/k8s_versions_scope.json
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7582 chore: remove regexp cache from API
  api/v1/cluster_funcs.go
  api/v1/cluster_funcs_test.go
  api/v1/cluster_types.go
  api/v1/zz_api_repo_funcs_to_copy.go
  api/v1/zz_generated.deepcopy.go
  internal/webhook/v1/cluster_webhook.go
Labels: ok to merge :ok_hand:, chore, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:L, lgtm

#7608 chore: stop testing Kubernetes versions older than 1.29
  .github/k8s_versions_scope.json
Labels: ok to merge :ok_hand:, chore, do not backport, size:XS, lgtm

#7581 docs: restructure backup and recovery section for CNPG-I plugins
  .wordlist-en-custom.txt
  docs/mkdocs.yml
  docs/src/appendixes/backup_barmanobjectstore.md
  docs/src/appendixes/backup_volumesnapshot.md
  docs/src/appendixes/object_stores.md
  docs/src/backup.md
  docs/src/bootstrap.md
  docs/src/index.md
  docs/src/operator_capability_levels.md
  docs/src/recovery.md
  docs/src/replica_cluster.md
  docs/src/wal_archiving.md
Labels: documentation :book:, ok to merge :ok_hand:, do not backport, size:XXL, lgtm

#7602 fix: guard for nil pgDataImageInfo in major version upgrades reconciler
  pkg/reconciler/majorupgrade/reconciler.go
Labels: ok to merge :ok_hand:, do not backport, size:XS, lgtm

#7600 chore: move dataDurability defaulting logic to webhook to avoid OLM issues
  api/v1/cluster_defaults.go
  api/v1/cluster_defaults_test.go
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
Labels: ok to merge :ok_hand:, chore, backport-requested :arrow_backward:, olm, release-1.25, size:M, lgtm

#7617 chore: improve OLM interface by adding fields
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, olm, release-1.24, release-1.25, size:S, lgtm

#7595 docs: Release Notes for 1.26.0, 1.25.2, and 1.24.4
  docs/src/installation_upgrade.md
  docs/src/preview_version.md
  docs/src/release_notes/v1.26.md
  docs/src/supported_releases.md
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, do not backport, size:L, lgtm

#7620 docs: fix missing Release Notes for 1.25.2 and 1.24.4
  docs/src/release_notes.md
  docs/src/release_notes/v1.24.md
  docs/src/release_notes/v1.25.md
  docs/src/release_notes/v1.26.md
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:L, lgtm

#7626 docs: fix 1.26 release date in supported releases
  docs/src/supported_releases.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7636 docs: update operator capability levels page
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
  docs/src/operator_capability_levels.md
  docs/src/release_notes/v1.26.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, do not backport, size:M, lgtm

#7621 Update ADOPTERS.md
  ADOPTERS.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7603 test(e2e): strenghten readiness checks
  tests/e2e/asserts_test.go
  tests/e2e/config_support_test.go
  tests/e2e/openshift_upgrade_test.go
  tests/e2e/operator_deployment_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/self_fencing_test.go
  tests/e2e/webhook_test.go
  tests/utils/deployments/deployment.go
  tests/utils/nodes/nodes.go
  tests/utils/operator/operator.go
  tests/utils/operator/webhooks.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, E2E tests, release-1.25, size:L, lgtm, release-1.26

#7652 ci: add missing permissions for the catalog creation
  .github/workflows/continuous-delivery.yml
Labels: github_actions, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26

#7701 docs: add Xata to `ADOPTERS.md`
  ADOPTERS.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.25, size:XS, lgtm, release-1.26
