Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2025-03, with the labels that each got.

#7047 chore(setup-cluster): fix the integration with bake
  Makefile
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7059 test: run EKS e2e on x86_64 instead of arm64
  hack/e2e/eks-cluster.yaml.template
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, E2E tests, release-1.25

#7056 chore(setup-cluster.sh): remove `k3d` support
  .devcontainer/devcontainer.json
  .github/renovate.json5
  Makefile
  contribute/e2e_testing_environment/README.md
  hack/e2e/run-e2e-k3d.sh
  hack/setup-cluster.sh
  tests/utils/cloudvendors/cloud_vendor.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7054 chore(setup-cluster.sh): remove `-r` flag
  Makefile
  contribute/e2e_testing_environment/README.md
  hack/e2e/run-e2e-kind.sh
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7078 ci(deps): remove 4.13 from the list of version for OpenShift
  .github/openshift_versions.json
  .github/workflows/k8s-versions-check.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7029 fix: reload plugin certificates when secret changes
  internal/cmd/manager/controller/controller.go
  internal/cnpi/plugin/repository/setup.go
  internal/cnpi/plugin/repository/setup_test.go
  internal/cnpi/plugin/repository/suite_test.go
  internal/controller/plugin_controller.go
  internal/controller/plugin_predicates.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6991 fix: delay rollout until every Pods received the same configuration
  internal/controller/cluster_controller.go
  pkg/management/postgres/probes.go
  pkg/postgres/status.go
  pkg/postgres/status_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7082 chore(deps): update Go version in go.mod
  go.mod
Labels: risk :boom:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7072 chore(webserver,remote): rename `ongoingRequest` parameter
  pkg/management/postgres/webserver/remote.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.24, release-1.25

#7095 fix(plugin,backup): close plugin connection
  pkg/management/postgres/webserver/plugin_backup.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.24, release-1.25

#7096 fix(repository,plugin): ensure that `repository` is closed
  internal/cmd/manager/controller/controller.go
  pkg/management/postgres/webserver/plugin_backup.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6902 refactor(backup-client): move the backup client to the remote client
  pkg/management/postgres/webserver/client/local/local.go
  pkg/management/postgres/webserver/client/remote/backup.go
  pkg/management/postgres/webserver/client/remote/instance.go
  pkg/management/postgres/webserver/client/remote/remote.go
  pkg/management/postgres/webserver/client/remote/request.go
  pkg/reconciler/backup/volumesnapshot/online.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.24, release-1.25

#7063 fix(PodMonitor): add proper `matchLabels` constraints
  pkg/specs/pgbouncer/podmonitor.go
  pkg/specs/pgbouncer/podmonitor_test.go
  pkg/specs/podmonitor.go
  pkg/specs/podmonitor_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6884 chore(webserver,update): get instance architecture without using using a sql connection
  pkg/management/postgres/instance.go
  pkg/management/postgres/probes.go
  pkg/management/upgrade/upgrade.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7005 fix(metrics): adapt pg_stat_wal metrics collection for PostgreSQL 18 compatibility
  pkg/management/postgres/probes.go
  pkg/management/postgres/webserver/metricserver/pg_collector.go
  pkg/management/postgres/webserver/metricserver/wal.go
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7121 chore: add the release notes type of issue
  .github/ISSUE_TEMPLATE/release-notes.yml
Labels: backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6959 docs(k9s): do not use bashisms in k9s integration sample
  docs/src/samples/k9s/plugins.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6809 refactor: move the multi-container logging to a dedicated package
  docs/src/kubectl-plugin.md
  internal/cmd/plugin/logs/cluster_logs.go
  internal/cmd/plugin/logs/cluster_logs_test.go
  internal/cmd/plugin/logs/cluster_test.go
  internal/cmd/plugin/report/logs.go
  pkg/podlogs/cluster_writer.go
  pkg/podlogs/cluster_writer_test.go
  pkg/podlogs/suite_test.go
  pkg/podlogs/writer.go
  pkg/podlogs/writer_test.go
  pkg/utils/discovery_test.go
  pkg/utils/logs/logs.go
  pkg/utils/logs/logs_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7141 docs: update README.md with Mastodon & Bluesky links
  README.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7036 feat: add support for configuring `tcp_user_timeout` on replicas
  .wordlist-en-custom.txt
  Makefile
  docs/src/operator_conf.md
  docs/src/postgresql_conf.md
  docs/src/release_notes/v1.26.md
  docs/src/ssl_connections.md
  docs/src/troubleshooting.md
  hack/e2e/run-e2e-ocp.sh
  hack/setup-cluster.sh
  internal/configuration/configuration.go
  internal/webhook/v1/cluster_webhook.go
  pkg/management/postgres/instance.go
  pkg/specs/pods.go
  tests/e2e/asserts_test.go
  tests/e2e/backup_restore_azure_test.go
  tests/e2e/backup_restore_azurite_test.go
  tests/e2e/backup_restore_minio_test.go
  tests/e2e/certificates_test.go
  tests/e2e/config_support_test.go
  tests/e2e/eviction_test.go
  tests/e2e/failover_test.go
  tests/e2e/fastfailover_test.go
  tests/e2e/fastswitchover_test.go
  tests/e2e/fixtures/fastfailover/apache-benchmark-webtest.yaml
  tests/e2e/fixtures/fastfailover/webtest-syncreplicas.yaml
  tests/e2e/fixtures/fastfailover/webtest.yaml
  tests/e2e/fixtures/fastswitchover/apache-benchmark-webtest.yaml
  tests/e2e/fixtures/fastswitchover/webtest.yaml
  tests/e2e/fixtures/sync_replicas/cluster-pgstatstatements.yaml.template
  tests/e2e/fixtures/sync_replicas/cluster-sync-replica-legacy.yaml.template
  tests/e2e/fixtures/sync_replicas/cluster-sync-replica.yaml.template
  tests/e2e/fixtures/sync_replicas/preferred.yaml.template
  tests/e2e/fixtures/sync_replicas/readiness-probe-lag-control.yaml.template
  tests/e2e/fixtures/sync_replicas/startup-probe-lag-control.yaml.template
  tests/e2e/managed_roles_test.go
  tests/e2e/metrics_test.go
  tests/e2e/nodeselector_test.go
  tests/e2e/operator_unavailable_test.go
  tests/e2e/publication_subscription_test.go
  tests/e2e/syncreplicas_test.go
  tests/e2e/tablespaces_test.go
  tests/e2e/update_user_test.go
  tests/e2e/upgrade_test.go
Labels: ok to merge :ok_hand:, do not backport

#7146 docs: update PostGIS instructions
  docs/src/postgis.md
  docs/src/samples/postgis-example.yaml
Labels: do not backport

#7155 feat(cmd,plugin): make `hibernate` command declarative
  docs/src/declarative_hibernation.md
  docs/src/kubectl-plugin.md
  docs/src/release_notes/v1.26.md
  internal/cmd/plugin/hibernate/cmd.go
  internal/cmd/plugin/hibernate/cmd_test.go
  internal/cmd/plugin/hibernate/off.go
  internal/cmd/plugin/hibernate/on.go
  internal/cmd/plugin/hibernate/output.go
  internal/cmd/plugin/hibernate/resources.go
  internal/cmd/plugin/hibernate/status.go
  internal/cmd/plugin/hibernate/suite_test.go
  internal/cmd/plugin/status/status.go
  tests/e2e/hibernation_test.go
  tests/e2e/tablespaces_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7164 chore: update go version to 1.24 in devcontainer configuration
  .devcontainer/devcontainer.json
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7161 fix(docs): EOL dates
  docs/src/supported_releases.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6989 feat(operator): introduce `KUBERNETES_CLUSTER_DOMAIN` configuration option
  .wordlist-en-custom.txt
  api/v1/cluster_funcs.go
  api/v1/cluster_funcs_test.go
  docs/src/certificates.md
  docs/src/operator_conf.md
  docs/src/release_notes/v1.26.md
  internal/configuration/configuration.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7177 fix(log): use the correct variable when logging mostAdvancedInstanceName
  internal/controller/cluster_controller.go
Labels: no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7186 chore(Makefile): remove targets for `kind` clusters
  Makefile
  contribute/development_environment/README.md
Labels: backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7126 fix: consider plugin changes while evaluating instance rollout
  go.mod
  go.sum
  internal/cnpi/plugin/mapping.go
  internal/controller/cluster_create.go
  internal/controller/cluster_upgrade.go
  internal/controller/cluster_upgrade_test.go
  internal/controller/suite_test.go
  internal/webhook/v1/cluster_webhook.go
  pkg/specs/pg_pods_test.go
  pkg/specs/pods.go
  pkg/specs/pods_test.go
  pkg/specs/podspec_diff.go
  pkg/utils/labels_annotations.go
Labels: risk :boom:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.25

#7142 test: wait for tablespace owner change
  tests/e2e/tablespaces_test.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7184 test(e2e): wait for webhook to work after disruption
  tests/e2e/operator_unavailable_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7010 fix(backup,VolumeSnapshots): treat timeout errors as retryable
  api/v1/backup_funcs.go
  api/v1/scheduledbackup_funcs.go
  api/v1/scheduledbackup_funcs_test.go
  docs/src/backup_volumesnapshot.md
  docs/src/labels_annotations.md
  internal/controller/backup_controller.go
  internal/webhook/v1/backup_webhook.go
  internal/webhook/v1/backup_webhook_test.go
  pkg/reconciler/backup/volumesnapshot/errors.go
  pkg/reconciler/backup/volumesnapshot/errors_test.go
  pkg/reconciler/backup/volumesnapshot/reconciler.go
  pkg/reconciler/backup/volumesnapshot/reconciler_test.go
  pkg/reconciler/backup/volumesnapshot/resources.go
  pkg/utils/labels_annotations.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7151 feat(barman-cloud): support lz4, xz, and zstd compression
  .wordlist-en-custom.txt
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/backup_barmanobjectstore.md
  go.mod
  go.sum
  pkg/management/postgres/backup_test.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7191 ci(ocp): retry oc secret link calls
  hack/e2e/run-e2e-ocp.sh
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7199 test(e2e): fix lag control probe threshold
  tests/e2e/fixtures/sync_replicas/startup-probe-lag-control.yaml.template
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7195 feat(metrics): check if extensions have updates
  config/manager/default-monitoring.yaml
Labels: ok to merge :ok_hand:

#7207 docs : Fix script's name in development_environment README
  contribute/development_environment/README.md
Labels: documentation :book:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7200 chore(instance,reconcile): avoid logging the cluster while in debug mode
  internal/management/controller/instance_controller.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7215 doc(operator_conf): add missing ConfigMap fields
  docs/src/operator_conf.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.24, release-1.25

#6928 feat: allow customization of taints for node drain detection
  docs/src/operator_conf.md
  internal/cmd/manager/controller/controller.go
  internal/configuration/configuration.go
  internal/controller/cluster_controller.go
  internal/controller/cluster_controller_test.go
  internal/controller/cluster_predicates.go
  internal/controller/cluster_predicates_test.go
  internal/controller/replicas.go
  internal/webhook/v1/cluster_webhook.go
  tests/e2e/drain_node_test.go
  tests/e2e/fixtures/drain-node/cluster-drain-node-karpenter.yaml.template
Labels: ok to merge :ok_hand:, do not backport

#7234 docs: fix spellcheck error
  .wordlist-en-custom.txt
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, do not backport

#7228 test: update csi-driver-host-path to v1.16.1
  hack/setup-cluster.sh
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7217 test: cleanup leftover logs from db management E2Es
  tests/e2e/declarative_database_management_test.go
  tests/utils/namespaces/namespace.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7143 docs: various updates
  README.md
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
  docs/src/architecture.md
  docs/src/e2e.md
  docs/src/index.md
  docs/src/installation_upgrade.md
  docs/src/replication.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, do not backport

#7214 ci: add workflow to automate the refresh of the licenses directory
  .github/workflows/refresh-licenses.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7220 feat(barman-cloud): remove support for Barman <= 3.4
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  go.mod
  go.sum
  pkg/management/postgres/backup.go
  pkg/management/postgres/backup_test.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, do not backport

#6664 feat: declarative offline in-place major upgrades of PostgreSQL
  .github/workflows/continuous-delivery.yml
  .wordlist-en-custom.txt
  api/v1/cluster_funcs.go
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  contribute/e2e_testing_environment/README.md
  docs/mkdocs.yml
  docs/src/cloudnative-pg.v1.md
  docs/src/e2e.md
  docs/src/index.md
  docs/src/operator_capability_levels.md
  docs/src/postgres_upgrades.md
  docs/src/release_notes/v1.26.md
  docs/src/samples/cluster-example.yaml
  internal/cmd/manager/instance/cmd.go
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/cmd/manager/instance/upgrade/cmd.go
  internal/cmd/manager/instance/upgrade/execute/cmd.go
  internal/cmd/manager/instance/upgrade/prepare/cmd.go
  internal/cmd/plugin/pgbench/pgbench.go
  internal/cmd/plugin/promote/promote.go
  internal/cmd/plugin/restart/restart.go
  internal/cmd/plugin/status/status.go
  internal/controller/cluster_controller.go
  internal/controller/cluster_image.go
  internal/controller/cluster_image_test.go
  internal/controller/cluster_scale.go
  internal/controller/cluster_scale_test.go
  internal/controller/cluster_status.go
  internal/controller/cluster_upgrade.go
  internal/controller/cluster_upgrade_test.go
  internal/controller/suite_test.go
  internal/management/controller/instance_controller.go
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/join.go
  pkg/reconciler/majorupgrade/doc.go
  pkg/reconciler/majorupgrade/job.go
  pkg/reconciler/majorupgrade/job_test.go
  pkg/reconciler/majorupgrade/reconciler.go
  pkg/reconciler/majorupgrade/reconciler_test.go
  pkg/reconciler/majorupgrade/suite_test.go
  pkg/resources/status/patch.go
  pkg/resources/status/transactions.go
  pkg/specs/containers.go
  pkg/specs/jobs.go
  pkg/specs/pg_pods_test.go
  pkg/specs/pods.go
  pkg/specs/pods_test.go
  pkg/specs/volumes.go
  pkg/specs/volumes_test.go
  tests/e2e/cluster_major_upgrade_test.go
  tests/e2e/cluster_microservice_test.go
  tests/labels.go
  tests/utils/postgres/postgres.go
Labels: ok to merge :ok_hand:, do not backport

#7249 chore: add FOSSA badge to the README.md
  README.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7128 docs: release notes for 1.26.0-rc1
  .wordlist-en-custom.txt
  docs/src/appendixes/object_stores.md
  docs/src/backup.md
  docs/src/backup_barmanobjectstore.md
  docs/src/backup_volumesnapshot.md
  docs/src/container_images.md
  docs/src/installation_upgrade.md
  docs/src/preview_version.md
  docs/src/recovery.md
  docs/src/release_notes.md
  docs/src/release_notes/v1.26.md
  docs/src/replica_cluster.md
  docs/src/wal_archiving.md
Labels: do not backport

#7258 fix(security): switch to pinDigest to follow OSSF recommendations
  .github/renovate.json5
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25
