Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2025-02, with the labels that each got.

#6695 feat: add kubernetes `client-gen` tool support
  api/v1/backup_funcs.go
  api/v1/cluster_funcs.go
  api/v1/clusterimagecatalog_types.go
  api/v1/groupversion_info.go
  internal/cmd/plugin/report/operator_utils.go
  internal/controller/cluster_controller.go
  internal/controller/cluster_create_test.go
  internal/controller/cluster_image.go
  internal/controller/cluster_restore_test.go
  internal/controller/pooler_controller.go
  internal/controller/scheduledbackup_controller.go
  internal/controller/suite_test.go
  pkg/management/client.go
  tests/e2e/rolling_update_test.go
  tests/utils/operator/upgrade.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6436 chore: remove unused yaml files
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6817 chore: introduce the `no-stale` label to issues
  .github/workflows/close-inactive-issues.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6636 fix(cnpg-plugin): collect logs from all containers, including sidecars, in instance pods
  internal/cmd/plugin/report/logs.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6810 fix: handle `load_balance_hosts` null value
  pkg/management/pgbouncer/metricsserver/pools.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6802 chore: stop building UBI8 operator images
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
  Dockerfile-ubi8
  docs/src/index.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6808 fix(bootstrap): ensure `override.conf` is included in replica setup
  pkg/management/postgres/configuration.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6871 chore(deps): pin genref version
  .github/renovate.json5
  Makefile
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6547 Use targetPod.Name in WithValues() instead of targetPod
  internal/controller/backup_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6784 docs: fix broken url in Image Catalog
  docs/src/image_catalog.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6496 fix: ensure operator version is reconciled
  api/v1/cluster_funcs.go
  internal/controller/cluster_create.go
  pkg/reconciler/instance/metadata_test.go
  pkg/reconciler/persistentvolumeclaim/reconciler_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6816 fix(metrics): ensure WAL metrics load after instance restart
  pkg/management/postgres/configuration.go
  pkg/management/postgres/webserver/metricserver/wal.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6622 chore: add `pg_catalog` schema where needed
  internal/cmd/manager/instance/run/lifecycle/run.go
  internal/cmd/plugin/logical/subscription/syncsequences/update.go
  internal/management/controller/database_controller_sql.go
  internal/management/controller/database_controller_sql_test.go
  internal/management/controller/database_controller_test.go
  internal/management/controller/instance_controller.go
  internal/management/controller/publication_controller_sql.go
  internal/management/controller/publication_controller_test.go
  internal/management/controller/roles/postgres.go
  internal/management/controller/roles/suite_test.go
  internal/management/controller/slots/infrastructure/postgresmanager.go
  internal/management/controller/slots/infrastructure/postgresmanager_test.go
  internal/management/controller/slots/reconciler/replicationslot_test.go
  internal/management/controller/slots/runner/runner_test.go
  internal/management/controller/subscription_controller_sql.go
  internal/management/controller/subscription_controller_test.go
  internal/management/controller/tablespaces/controller_test.go
  internal/management/controller/tablespaces/infrastructure/postgres.go
  internal/management/controller/tablespaces/infrastructure/postgres_test.go
  pkg/management/postgres/initdb.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/logicalimport/database.go
  pkg/management/postgres/logicalimport/database_test.go
  pkg/management/postgres/logicalimport/role.go
  pkg/management/postgres/logicalimport/role_test.go
  pkg/management/postgres/logicalimport/roleinheritance.go
  pkg/management/postgres/logicalimport/roleinheritance_test.go
  pkg/management/postgres/probes.go
  pkg/management/postgres/readiness/readiness.go
  pkg/management/postgres/restore.go
  pkg/management/postgres/utils/utils.go
  pkg/management/postgres/wal.go
  pkg/management/postgres/wal_test.go
  pkg/management/postgres/webserver/backup_connection.go
  pkg/management/postgres/webserver/metricserver/pg_collector.go
  pkg/management/postgres/webserver/metricserver/wal.go
  pkg/management/postgres/webserver/metricserver/wal_test.go
  tests/e2e/asserts_test.go
  tests/e2e/cluster_microservice_test.go
  tests/e2e/cluster_monolithic_test.go
  tests/e2e/configuration_update_test.go
  tests/e2e/declarative_database_management_test.go
  tests/e2e/disk_space_test.go
  tests/e2e/failover_test.go
  tests/e2e/fencing_test.go
  tests/e2e/initdb_test.go
  tests/e2e/managed_roles_test.go
  tests/e2e/publication_subscription_test.go
  tests/e2e/replica_mode_cluster_test.go
  tests/e2e/replication_slot_test.go
  tests/e2e/syncreplicas_test.go
  tests/e2e/tablespaces_test.go
  tests/e2e/update_user_test.go
  tests/e2e/upgrade_test.go
  tests/utils/postgres/postgres.go
  tests/utils/replicationslot/replication_slots.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6440 fix: improve efficiency of replication-sensitive parameter updates
  api/v1/cluster_funcs.go
  internal/management/controller/instance_controller.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6739 refactor: simplify configparser by removing redundant logic
  internal/configuration/configuration.go
  pkg/configparser/configparser.go
  pkg/configparser/configparser_test.go
  pkg/configparser/environment.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6701 feat(plugin): add `--ttl` option to `pgbench` command
  internal/cmd/plugin/pgbench/cmd.go
  internal/cmd/plugin/pgbench/cmd_test.go
  internal/cmd/plugin/pgbench/pgbench.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6879 fix: prevent leaking connection when snapshot backup fail
  pkg/management/postgres/webserver/backup_connection.go
  pkg/management/postgres/webserver/remote.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6882 fix(backup): clean unused backup connections
  pkg/management/postgres/webserver/remote.go
  pkg/management/postgres/webserver/webserver.go
  tests/e2e/volume_snapshot_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6800 feat: allow using '-r' service for Pooler
  api/v1/pooler_types.go
  config/crd/bases/postgresql.cnpg.io_poolers.yaml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6303 docs: Remove deprecated Pod Security Policies from docs
  docs/src/operator_capability_levels.md
  docs/src/security.md
Labels: ok to merge :ok_hand:, do not backport

#6866 docs: fix files names in report archive
  docs/src/kubectl-plugin.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6889 docs: add doc on pgbench ttl option
  docs/src/benchmarking.md
  internal/cmd/plugin/pgbench/pgbench.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6868 fix(cnpg-plugin): pbench job when a Cluster is using an ImageCatalog
  internal/cmd/plugin/pgbench/pgbench.go
  internal/controller/cluster_upgrade.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6607 fix: ensure cluster dependant resources reconcile after cluster rehydratation
  api/v1/database_funcs.go
  api/v1/publication_funcs.go
  api/v1/subscription_funcs.go
  internal/controller/finalizers_delete.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24, release-1.25

#6908 test(snapshot): dump VolumeSnapshot objects when E2e test fail
  tests/utils/namespaces/namespace.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6898 chore(backup): remove force parameter
  pkg/management/postgres/webserver/remote.go
  pkg/reconciler/backup/volumesnapshot/online.go
Labels: no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6921 ci: fix regexp to retrieve EKS versions
  .github/workflows/k8s-versions-check.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6930 chore: enable unit tests on Kubernetes 1.32
  .github/k8s_versions_scope.json
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6897 test(e2e): fix race condition in replica mode test
  tests/e2e/replica_mode_cluster_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6593 fix(cnpgi-plugins): add archive and backup capabilities fields to configuration
  .wordlist-en-custom.txt
  api/v1/cluster_funcs.go
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  internal/controller/backup_controller.go
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
  pkg/management/postgres/archiver/archiver.go
  pkg/management/postgres/webserver/plugin_backup.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.24, release-1.25

#6890 fix(backup,snapshot): avoid parallel actions on endpoints
  pkg/management/postgres/webserver/backup_connection.go
  pkg/management/postgres/webserver/client/local/backup.go
  pkg/management/postgres/webserver/remote.go
  pkg/management/postgres/webserver/webserver.go
  pkg/reconciler/backup/volumesnapshot/online.go
  pkg/reconciler/backup/volumesnapshot/online_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6749 docs: clarify the bootstrap section
  docs/src/bootstrap.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6969 test: fix race in metrics tests
  tests/e2e/metrics_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6967 fix: remove any replaces or skipRange in the OLM config
  Makefile
  config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6964 fix(plugin): do not append pgData if walName already contains it
  pkg/management/postgres/archiver/archiver.go
Labels: ok to merge :ok_hand:

#6982 chore: fix word list
  .wordlist-en-custom.txt
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6974 test: log the pod in the replication slot aligned check
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6987 test: fix tests remaining stuck waiting for portforward
  tests/utils/forwardconnection/forwardconnection.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, E2E tests, release-1.25

#6972 test: fix race on drain e2e
  tests/e2e/drain_node_test.go
Labels: backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7002 chore(deps): downgrade go-grpc-middleware to v2.2.0
  go.mod
  go.sum
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6806 ci: move the container build process to bake
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
  Dockerfile
  Dockerfile-ubi9
  Makefile
  docker-bake.hcl
  hack/setup-cluster.sh
  pkg/utils/discovery.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7019 docs: update Slack channel invite
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6945 docs: streamline documentation on failure modes
  docs/src/failure_modes.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7015 fix: update dependencies
  go.mod
  go.sum
Labels: backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7011 docs: improve tcp_syn_retry troubleshooting section
  .wordlist-en-custom.txt
  docs/src/troubleshooting.md
Labels: documentation :book:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7008 fix: provide the operator extra time to start
  config/manager/manager.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6878 test(e2e): retry failures on imperative backup
  tests/e2e/tablespaces_test.go
  tests/e2e/volume_snapshot_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7023 docs: document image signatures and attestations
  .wordlist-en-custom.txt
  docs/src/security.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7028 chore: align OLM image's tags in the Makefile
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7033 ci(release): build specific ids during release process
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7038 ci(release): build race only when RACE env is set
  .github/workflows/continuous-integration.yml
  .github/workflows/release-publish.yml
  .goreleaser.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7042 ci(release): fix cosign invocation
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25
