Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2025-01, with the labels that each got.

#6489 fix: linter errors for golangci-lint 1.63.1
  internal/cmd/plugin/psql/psql_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6492 fix: add missing release-1.25 branch to backport workflow
  .github/workflows/backport.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6497 test(e2e): fix initdb test
  tests/e2e/initdb_test.go
Labels: no-issue

#6456 test(e2e): ensure unique namespaces during parallel tests
  tests/utils/environment/environment.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6448 test(e2e): add a higher timeout and better error descriptions to `switchWalAndGetLatestArchive`
  tests/e2e/asserts_test.go
  tests/utils/exec/exec.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6474 fix(managed-services): preserve user specified port settings
  pkg/specs/services.go
  pkg/specs/services_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.24, release-1.25

#6477 test(e2e): retry `AssertWritesToPrimarySucceeds` and `AssertWritesToReplicaFails`
  tests/e2e/asserts_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6435 test(e2e): remove redudant `AssertPostgresNoPendingRestart` calls
  tests/e2e/asserts_test.go
  tests/e2e/configuration_update_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6473 docs: fix typo in prometheus rules example
  docs/src/samples/monitoring/prometheusrule.yaml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#4745 doc: add kubectl plugin instructions for Arch Linux User Repository (AUR)
  docs/src/kubectl-plugin.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6526 chore: fix spell checker
  .wordlist-en-custom.txt
  docs/src/kubectl-plugin.md
Labels: no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6525 chore: introduce `stale` GitHub action
  .github/workflows/stale.yml
Labels: ok to merge :ok_hand:, do not backport

#6529 ci: update stale github action
  .github/workflows/close-inactive-issues.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6531 chore(ci): remove debug only flag from stale github action
  .github/workflows/close-inactive-issues.yml
Labels: no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6533 ci(workflow): set right comment in stale issues
  .github/workflows/close-inactive-issues.yml
Labels: no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6534 change color to green if replication slots are enabled
  internal/cmd/plugin/status/status.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6476 fix: restore functionality of promote plugin command
  internal/cmd/plugin/promote/cmd.go
  internal/cmd/plugin/promote/promote.go
  internal/cmd/plugin/promote/promote_test.go
  internal/cmd/plugin/promote/suite_test.go
  internal/cmd/plugin/restart/restart.go
  internal/controller/cluster_status.go
  internal/management/controller/instance_controller.go
  pkg/resources/status/phase.go
  pkg/resources/status/transactions.go
  pkg/resources/status/update.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6543 chore: correct typos in the `resource/status` pkg
  pkg/resources/status/conditions.go
  pkg/resources/status/patch.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6472 refactor: move webhooks in a dedicated package
  api/v1/backup_webhook.go
  api/v1/cluster_defaults.go
  api/v1/cluster_defaults_test.go
  api/v1/cluster_funcs.go
  api/v1/cluster_funcs_test.go
  api/v1/cluster_types.go
  api/v1/pooler_webhook.go
  api/v1/scheduledbackup_funcs_test.go
  api/v1/scheduledbackup_webhook.go
  api/v1/scheduledbackup_webhook_test.go
  internal/cmd/manager/controller/controller.go
  internal/webhook/v1/backup_webhook.go
  internal/webhook/v1/backup_webhook_test.go
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
  internal/webhook/v1/doc.go
  internal/webhook/v1/pooler_webhook.go
  internal/webhook/v1/pooler_webhook_test.go
  internal/webhook/v1/scheduledbackup_webhook.go
  internal/webhook/v1/scheduledbackup_webhook_test.go
  internal/webhook/v1/suite_test.go
  tests/e2e/asserts_test.go
  tests/e2e/webhook_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6627 docs: add OpenSSF best practices badge
  README.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6629 docs: clarify readiness probe for replicas
  docs/src/instance_manager.md
  docs/src/replication.md
Labels: backport-requested :arrow_backward:, release-1.24, release-1.25

#5690 chore(test): add preflight check for operator in cd workflow
  .github/workflows/continuous-delivery.yml
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6656 fix: consistent threshold calculation for probes
  api/v1/cluster_funcs.go
  api/v1/cluster_funcs_test.go
  docs/src/instance_manager.md
  pkg/specs/pods.go
  pkg/specs/pods_test.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6666 fix(ci): make sure to run only on created comments
  .github/workflows/continuous-delivery.yml
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6646 fix(import): skip role import if no roles are specified
  pkg/management/postgres/logicalimport/monolith.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6635 docs(fix): use the correct dataDurability in the preferred section example
  docs/src/replication.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6673 docs: tcp_syn_retries behaviour
  .wordlist-en-custom.txt
  docs/src/troubleshooting.md
Labels: documentation :book:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6634 test(e2e): enable race detector in the E2e tests
  .github/workflows/continuous-integration.yml
  .goreleaser.yml
  Makefile
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6630 fix: add support for PgBouncer 1.24
  docs/src/connection_pooling.md
  pkg/management/pgbouncer/metricsserver/pools.go
  pkg/management/pgbouncer/metricsserver/stats.go
  pkg/specs/pgbouncer/deployments.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6659 fix(instance-manager): use pgdata content to discover PostgreSQL version
  internal/cmd/manager/instance/run/lifecycle/run.go
  pkg/management/postgres/configuration.go
  pkg/management/postgres/configuration_test.go
  pkg/management/postgres/utils/version.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6716 docs: Typo in Service Management documentation: updateStrategy: replace
  docs/src/service_management.md
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6676 docs: fix formatting of disk-full-failure section
  docs/src/instance_manager.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6707 docs: fixed typo in Connection Pooling documentation
  docs/src/connection_pooling.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6706 docs: fix formatting of reconcilePodSpec annotation
  docs/src/labels_annotations.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6323 feat: support customizable pod patches via annotations
  .wordlist-en-custom.txt
  docs/src/labels_annotations.md
  internal/controller/cluster_create.go
  internal/controller/cluster_upgrade_test.go
  internal/controller/suite_test.go
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
  pkg/specs/pg_pods_test.go
  pkg/specs/pods.go
  pkg/specs/pods_test.go
  pkg/utils/labels_annotations.go
  tests/e2e/pod_patch_test.go
Labels: ok to merge :ok_hand:, no-issue, do not backport

#6579 fix(webhook): return warnings alongside errors in webhook responses
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/scheduledbackup_webhook.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#6598 chore: remove unused code
  api/v1/cluster_types.go
  api/v1/zz_generated.deepcopy.go
Labels: no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25
