Repository cloudnative-pg/cloudnative-pg, pull requests merged in 2025-04, with the labels that each got.

#7251 feat(security): add OSSF Scorecard action
  .github/workflows/ossf_scorecard.yml
  README.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7267 test(major_upgrade): refetch cluster while executing image update
  tests/e2e/cluster_major_upgrade_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25

#7311 fix: add missing pinDigest into renovate for spellcheck group
  .github/renovate.json5
Labels: dependencies :twisted_rightwards_arrows:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7297 feat: remove Azure CSI driver resize workaround
  api/v1/cluster_types.go
  config/crd/bases/postgresql.cnpg.io_clusters.yaml
  docs/src/cloudnative-pg.v1.md
  docs/src/operator_conf.md
  docs/src/storage.md
  internal/configuration/configuration.go
  internal/controller/cluster_create.go
  internal/controller/cluster_upgrade.go
Labels: ok to merge :ok_hand:, do not backport, size:L, lgtm

#7304 feat: Switch Slack Channel links to the CNCF Slack
  CONTRIBUTING.md
  README.md
  contribute/README.md
  docs/src/supported_releases.md
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:M, lgtm

#7327 feat(security): pin digest and group updates
  .github/renovate.json5
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, security :police_officer:, release-1.22, release-1.24, release-1.25, size:S, lgtm

#7256 chore(cluster): add `GetCurrentDataImage` method
  internal/controller/cluster_image.go
  internal/controller/cluster_image_test.go
Labels: ok to merge :ok_hand:, no-issue, do not backport, size:M, lgtm

#7334 fix(security): ignore pgbouncer path for the digest updater
  .github/renovate.json5
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, security :police_officer:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7250 fix(security): add imagePullPolicy to operator deployment
  config/manager/manager.yaml
Labels: backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, lgtm

#7260 fix(instance): improve error handling for `RefreshSecrets`
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/upgrade/execute/cmd.go
  internal/management/controller/instance_controller.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:M, lgtm

#7274 fix(upgrades): consider previous controldata when creating the new datadir
  internal/cmd/manager/instance/upgrade/execute/cmd.go
  pkg/management/postgres/instance.go
  pkg/utils/parser.go
  tests/e2e/cluster_major_upgrade_test.go
Labels: bug :bug:, ok to merge :ok_hand:, do not backport, size:L, lgtm

#7265 refactor(instance,secrets): extract sub-reconciler for instance secrets management
  internal/cmd/manager/instance/join/cmd.go
  internal/cmd/manager/instance/upgrade/execute/cmd.go
  internal/management/controller/instance_controller.go
  internal/management/controller/instance_startup.go
  internal/management/controller/manager.go
  pkg/management/postgres/instance.go
  pkg/management/postgres/webserver/metricserver/metrics.go
  pkg/management/postgres/webserver/remote.go
  pkg/reconciler/instance/certificate/doc.go
  pkg/reconciler/instance/certificate/reconciler.go
  pkg/reconciler/instance/certificate/reconciler_test.go
  pkg/reconciler/instance/certificate/suite_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.24, release-1.25, size:XL, lgtm

#7343 fix(docs): typo in benchmarking.md
  docs/src/benchmarking.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7266 refactor(instance,storage): extract sub-reconciler for instance storage
  internal/cmd/manager/instance/run/cmd.go
  internal/cmd/manager/instance/upgrade/execute/cmd.go
  internal/management/controller/instance_startup.go
  internal/webhook/v1/cluster_webhook.go
  pkg/reconciler/instance/storage/doc.go
  pkg/reconciler/instance/storage/reconciler.go
  pkg/reconciler/instance/storage/reconciler_test.go
  pkg/reconciler/instance/storage/suite_test.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.24, release-1.25, size:L, lgtm

#7342 fix: avoid returning non-zero and error in reconcilers
  internal/controller/backup_controller.go
  internal/controller/cluster_controller.go
  internal/controller/cluster_create.go
  internal/controller/plugins.go
  internal/management/controller/instance_controller.go
  pkg/reconciler/hibernation/reconciler.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:M, lgtm

#7364 chore: avoid using a magic constant for the imageCatalog indexed field
  internal/controller/cluster_image.go
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, lgtm

#7348 ci: add digest to operator manifest for testing
  .github/workflows/continuous-delivery.yml
  Makefile
  hack/e2e/run-e2e-kind.sh
  hack/e2e/run-e2e.sh
Labels: github_actions, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:S, lgtm

#7284 feat(cnpgi,snapshot): support WAL recovery via plugins during snapshot restore
  internal/cmd/manager/instance/restore/cmd.go
  internal/cmd/manager/instance/restoresnapshot/cmd.go
  internal/cmd/manager/instance/restoresnapshot/restore.go
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:L, lgtm

#7378 docs: release notes for 1.26.0-rc2
  docs/src/preview_version.md
  docs/src/release_notes/v1.26.md
Labels: documentation :book:, ok to merge :ok_hand:, do not backport, size:M, lgtm

#7387 fix(catalog): ensure image catalog takes priority over image names
  api/v1/cluster_funcs.go
  api/v1/cluster_funcs_test.go
Labels: bug :bug:, ok to merge :ok_hand:, do not backport, size:M, lgtm

#7389 fix: off by 1 error in parallel wal archive
  pkg/management/postgres/archiver/archiver.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:S, lgtm

#7399 chore: change default PgBouncer version to 1.24.1
  pkg/specs/pgbouncer/deployments.go
Labels: ok to merge :ok_hand:, chore, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7396 feat: drop support for pg12
  docs/src/database_import.md
  docs/src/postgresql_conf.md
  internal/cmd/manager/instance/pgbasebackup/cmd.go
  internal/cmd/manager/instance/run/lifecycle/run.go
  internal/controller/cluster_image_test.go
  internal/webhook/v1/cluster_webhook.go
  internal/webhook/v1/cluster_webhook_test.go
  pkg/management/postgres/join.go
  pkg/management/postgres/logpipe/logpipe_test.go
  pkg/management/postgres/logpipe/testdata/two_lines_12.csv
  pkg/management/postgres/probes_test.go
  pkg/postgres/configuration.go
  pkg/postgres/configuration_test.go
  tests/e2e/replication_slot_test.go
Labels: bug :bug:, ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:L, lgtm

#7383 docs/architecture: fix typo
  docs/src/architecture.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7358 chore: update OpenShift metadata version to 4.19
  Makefile
Labels: ok to merge :ok_hand:, chore, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7430 adding 1.26.0-rc2 to git template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm

#7411 ci: select a single UBI tag during the OLM release process
  .github/workflows/release-publish.yml
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:S, lgtm

#7281 fix(plugin): expand `logs pretty` cmd buffer size
  internal/cmd/plugin/logs/pretty/pretty.go
Labels: ok to merge :ok_hand:, backport-requested :arrow_backward:, release-1.25, size:XS, lgtm

#7388 refactor(restore): remove duplicate code
  pkg/management/postgres/restore.go
Labels: ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.25, size:M, lgtm

#7450 Fix typo in role name
  docs/src/database_import.md
Labels: documentation :book:, ok to merge :ok_hand:, no-issue, backport-requested :arrow_backward:, release-1.22, release-1.24, release-1.25, size:XS, lgtm
